In [13]:
import pandas as pd

desert = pd.read_csv(
    "data/raw/airnb_desert.csv",
    encoding="cp1252"
)

In [14]:
desert.head()
desert.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Desert name       280 non-null    object
 1   Date              280 non-null    object
 2   Price(In dollar)  280 non-null    object
 3   Details           280 non-null    object
 4   Rating            168 non-null    float64
dtypes: float64(1), object(4)
memory usage: 11.1+ KB

In [12]:
desert = pd.read_csv(
    "data/raw/airnb_desert.csv",
    encoding="cp1252"
)

In [15]:
import pandas as pd

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", None)

In [16]:
display(desert)

,Desert name,Date,Price(In dollar),Details,Rating
0,"Mhamid, Morocco",May 1 – 29,479.00,Near Sahara Desert,4.79
1,"Aqaba City, Jordan",May 1 – 29,"2,168.00",Near Arabian Desert,4.92
2,"Tamesluht, Morocco",May 1 – 29,"17,752.00","9,404 kilometers away",4.95
3,"Al Bairat, Egypt",May 1 – 29,"1,982.00",Near Sahara Desert,4.88
4,"Tamesluht, Morocco",May 1 – 29,"17,752.00","9,404 kilometers away",4.87
5,"Mitzpe Ramon, Israel",May 1 – 29,"2,502.00",Near Arabian Desert,4.81
6,"M'Hamid El Ghizlane, Morocco",May 1 – 29,415.00,Near Sahara Desert,4.81
7,"Tinghir, Morocco",May 1 – 29,"1,346.00",Near Sahara Desert,4.92
8,"Skoura, Morocco",May 1 – 29,928.00,"9,293 kilometers away",4.91
9,"MA, Morocco",May 1 – 29,857.00,Near Sahara Desert,4.86
10,"Mitzpe Ramon, Israel",May 1 – 29,"2,945.00",Near Arabian Desert,4.81
11,"Wadi Rum, Jordan",May 1 – 29,898.00,Near Arabian Desert,4.84
12,"Jaisalmer, India",May 1 – 29,449.00,Near Thar Desert,4.79
13,"Siwa, Egypt",May 1 – 29,991.00,Near Sahara Desert,4.90
14,"Merzouga, Morocco",May 1 – 29,"2,937.00",Near Sahara Desert,4.83
15,"Essaouira, Morocco",May 1 – 29,"5,386.00","9,536 kilometers away",4.90
16,"Jaisalmer, India",May 1 – 29,284.00,Near Thar Desert,4.86
17,"Tzofar, Israel",May 1 – 29,"1,821.00",Near Arabian Desert,4.77
18,"Ait Bihi, Morocco",May 1 – 29,"1,096.00","9,586 kilometers away",4.94
19,"Jaisalmer, India",May 1 – 29,677.00,Near Thar Desert,4.79
20,"Al Bairat, Egypt",May 5 – Jun 2,"1,670.00",Near Sahara Desert,5.00
21,"Órzola, Spain",May 1 – 29,"2,396.00","9,976 kilometers away",4.90
22,"Hassilabied, Morocco",May 1 – 29,970.00,Near Sahara Desert,4.94
23,"Aglou, Morocco",May 1 – 29,"2,792.00","9,637 kilometers away",5.00
24,"Takojt, Morocco",May 1 – 29,371.00,Near Sahara Desert,5.00
25,"Ouarzazate, Morocco",May 1 – 29,530.00,"9,327 kilometers away",4.67
26,"Wadi Rum Village, Jordan",May 1 – 29,823.00,Near Arabian Desert,5.00
27,"Marrakech, Morocco",May 1 – 29,"3,561.00","9,391 kilometers away",4.94
28,"Wadi Rum Village, Jordan",May 1 – 29,898.00,Near Arabian Desert,4.86
29,"M'Hamid El Ghizlane, Morocco",May 1 – 29,340.00,Near Sahara Desert,5.00
30,"Tamesluht, Morocco",May 1 – 29,"12,800.00","9,406 kilometers away",4.77
31,"Mhamid, Morocco",May 1 – 29,179.00,Near Sahara Desert,4.89
32,"Arad, Israel",May 1 – 29,"3,737.00",Near Arabian Desert,4.82
33,"Merzouga, Morocco",May 1 – 29,840.00,Near Sahara Desert,4.98
34,"Mhamid, Morocco",May 1 – 29,"1,145.00",Near Sahara Desert,4.87
35,"???????, Morocco",May 1 – 29,"1,149.00","9,586 kilometers away",4.96
36,"Wadi Rum Village, Jordan",May 1 – 29,294.00,Near Arabian Desert,4.89
37,"Marrakesh, Morocco",May 1 – 29,"7,515.00","9,414 kilometers away",4.94
38,"Triopetra, Greece",May 1 – 29,"3,209.00","6,390 kilometers away",4.82
39,"Ksar Bounou (Oasis de M´hamid Alguizlane ), Morocco",May 1 – 29,285.00,Near Sahara Desert,4.95
40,"????, Israel",May 1 – 29,"2,082.00",Near Arabian Desert,4.88
41,"Arad, Israel",May 1 – 29,"1,734.00",Near Arabian Desert,5.00
42,"???? ?????, Egypt",May 1 – 29,598.00,Near Arabian Desert,4.94
43,"Midreshet Ben-Gurion, Israel",May 1 – 29,"2,994.00",Near Arabian Desert,5.00
44,"M'HAMID, Morocco",May 1 – 29,305.00,Near Sahara Desert,4.86
45,"Hassilabied, Morocco",May 1 – 29,997.00,Near Sahara Desert,4.76
46,"Khuri, India",May 1 – 29,375.00,Near Thar Desert,4.82
47,"???? ???? ??, Jordan",May 1 – 29,279.00,Near Arabian Desert,4.83
48,"Mhamid, Morocco",May 1 – 29,731.00,Near Sahara Desert,4.92
49,"Tamesluht, Morocco",May 1 – 29,"17,752.00","9,404 kilometers away",5.00
50,"Tamesluht, Morocco",May 1 – 29,"10,473.00","9,406 kilometers away",4.85
51,"Kalya, Israel",May 1 – 29,"7,228.00",Near Syrian Desert,5.00
52,"Birkat al Maraqi, Egypt",May 1 – 29,249.00,Near Sahara Desert,5.00
53,"Aqaba, Jordan",May 1 – 29,"2,061.00",Near Arabian Desert,5.00
54,"Luxor, Egypt",May 1 – 29,347.00,Near Sahara Desert,5.00
55,"Jaisalmer, India",May 1 – 29,562.00,Near Thar Desert,4.88
56,"Oued El Khil, Tunisia",May 1 – 29,749.00,Near Sahara Desert,4.94
57,"Mhamid, Morocco",May 1 – 29,207.00,Near Sahara Desert,5.00
58,"commune rurale Fritissa, Morocco",May 1 – 29,587.00,"8,935 kilometers away",5.00
59,"Tiznit, Morocco",May 1 – 29,"7,687.00","9,635 kilometers away",5.00
60,"Wadi Rum Village, Jordan",May 1 – 29,368.00,Near Arabian Desert,5.00
61,"Hassilabied, Morocco",May 1 – 29,822.00,Near Sahara Desert,5.00
62,"Fint, Morocco",May 1 – 29,831.00,"9,328 kilometers away",4.67
63,"Arad, Israel",May 1 – 29,"8,080.00",Near Arabian Desert,5.00
64,"Tamesluht, Morocco",May 1 – 29,"10,473.00","9,406 kilometers away",5.00
65,"Marrakech Alentours, Morocco",May 1 – 29,"35,293.00","9,379 kilometers away",5.00
66,"Merzouga, Morocco",May 1 – 29,877.00,Near Sahara Desert,5.00
67,"Zagora, Morocco",May 1 – 29,256.00,Near Sahara Desert,5.00
68,"Hassilabied, Morocco",May 1 – 29,263.00,Near Sahara Desert,4.67
69,"Es Sabria, Tunisia",May 1 – 29,932.00,Near Sahara Desert,4.62
70,"MA, Morocco",May 1 – 29,542.00,Near Sahara Desert,4.78
71,"Al Ula, Saudi Arabia",May 1 – 29,"16,519.00",Near Arabian Desert,4.87
72,"Nazlet El-Semman, Egypt",May 1 – 29,"1,370.00",Near Sahara Desert,4.63
73,"Douz, Tunisia",May 1 – 29,"1,896.00",Near Sahara Desert,4.78
74,"Arad, Israel",May 1 – 29,"4,209.00",Near Arabian Desert,4.78
75,"Jaisalmer, India",May 1 – 29,449.00,Near Thar Desert,4.74
76,"Zagora, Morocco",May 1 – 29,190.00,Near Sahara Desert,4.76
77,"Hassilabied, Morocco",May 1 – 29,455.00,Near Sahara Desert,4.73
78,"Zagora, Morocco",May 1 – 29,798.00,Near Sahara Desert,4.52
79,"Merzouga, Morocco",May 1 – 29,780.00,Near Sahara Desert,4.79
80,"Tinghir, Morocco",May 1 – 29,"1,346.00",Near Sahara Desert,4.67
81,"Siwa Oasis, Egypt",May 1 – 29,867.00,Near Sahara Desert,4.70
82,"Zagora, Morocco",May 1 – 29,466.00,Near Sahara Desert,4.67
83,"Zagora, Morocco",May 1 – 29,425.00,Near Sahara Desert,4.43
84,"Jaisalmer, India",May 1 – 29,"1,198.00",Near Thar Desert,4.52
85,"Marrakech, Morocco",May 1 – 29,648.00,"9,390 kilometers away",4.76
86,"Qesm Siwah, Egypt",May 1 – 29,790.00,Near Sahara Desert,4.76
87,"Aoufous, Morocco",May 1 – 29,663.00,Near Sahara Desert,4.75
88,"Wadi Rum Village, Jordan",May 1 – 29,244.00,Near Arabian Desert,4.50
89,"Marrakech, Morocco",May 1 – 29,"3,061.00","9,391 kilometers away",4.83
90,"Sam, India",May 1 – 29,628.00,Near Thar Desert,4.23
91,"Hassilabied, Morocco",May 1 – 29,"1,515.00",Near Sahara Desert,4.76
92,"Kfar Adumim, Israel",May 1 – 29,"4,248.00",Near Syrian Desert,4.59
93,"Essaouira, Morocco",May 1 – 29,"8,977.00","9,536 kilometers away",4.89
94,"Stavros, Greece",May 1 – 29,"9,601.00","6,425 kilometers away",4.57
95,"Merzouga, Morocco",May 1 – 29,812.00,Near Sahara Desert,4.84
96,"Dahab, Egypt",May 1 – 29,"1,512.00",Near Arabian Desert,4.76
97,"Ouarzazate, Morocco",May 1 – 29,897.00,"9,349 kilometers away",4.68
98,"Tamesluht, Morocco",May 1 – 29,"10,473.00","9,406 kilometers away",4.38
99,"Merzouga, Morocco",May 1 – 29,"2,061.00",Near Sahara Desert,4.51
100,"Boumalne Dades, Morocco",May 1 – 29,"2,359.00",Near Sahara Desert,4.50
101,"Hassilabied, Morocco",May 1 – 29,"1,184.00",Near Sahara Desert,4.71
102,"Bawity, Egypt",May 1 – 29,"1,239.00",Near Sahara Desert,4.75
103,"Wadi rum, Jordan",May 1 – 29,217.00,Near Arabian Desert,4.70
104,"Nador, Morocco",May 1 – 29,"1,225.00","8,770 kilometers away",4.62
105,"Hassilabied, Morocco",May 1 – 29,426.00,Near Sahara Desert,4.67
106,"Ezuz, Israel",May 1 – 29,"5,545.00",Near Arabian Desert,4.00
107,"Mhamid, Morocco",May 1 – 29,744.00,Near Sahara Desert,4.56
108,"Mhamid, Morocco",May 1 – 29,565.00,Near Sahara Desert,4.67
109,"Wadi Rum Village, Jordan",May 1 – 29,232.00,Near Arabian Desert,4.68
110,"Merzouga, Morocco",May 1 – 29,299.00,Near Sahara Desert,4.82
111,"Zagora, Morocco",May 1 – 29,220.00,Near Sahara Desert,4.60
112,"M'Hamid El Ghizlane, Morocco",May 1 – 29,764.00,Near Sahara Desert,4.30
113,"Mhamid, Morocco",May 1 – 29,"1,163.00",Near Sahara Desert,4.50
114,"Khamlia, Morocco",May 1 – 29,"1,442.00",Near Sahara Desert,3.67
115,"Ouarzazate, Morocco",May 1 – 29,"2,326.00","9,341 kilometers away",4.68
116,"Jaisalmer, India",May 1 – 29,"1,310.00",Near Thar Desert,4.71
117,"Wadi Rum Village, Jordan",May 1 – 29,350.00,Near Arabian Desert,4.71
118,"Zagora, Morocco",May 1 – 29,930.00,Near Sahara Desert,4.25
119,"Quairah District, Jordan",May 1 – 29,155.00,Near Arabian Desert,4.84
120,"Jaisalmer, India",May 1 – 29,"2,039.00",Near Thar Desert,4.20
121,"Wadi Rum Village, Jordan",May 1 – 29,294.00,Near Arabian Desert,4.50
122,"Merzouga, Morocco",May 1 – 29,"2,966.00",Near Sahara Desert,4.11
123,"Mhamid, Morocco",May 1 – 29,295.00,Near Sahara Desert,4.53
124,"Jaisalmer, India",May 1 – 29,233.00,Near Thar Desert,3.67
125,"Ouled Arbia, Morocco",May 1 – 29,"2,758.00","9,295 kilometers away",4.15
126,"Merzouga, Morocco",May 1 – 29,"1,848.00",Near Sahara Desert,4.00
127,"Bikaner, India",May 1 – 29,"1,514.00",Near Thar Desert,4.67
128,"Tighza/Telouet, Morocco",May 1 – 29,523.00,"9,328 kilometers away",4.47
129,"Merzouga, Morocco",May 1 – 29,989.00,Near Sahara Desert,4.74
130,"Aqaba City, Jordan",May 1 – 29,341.00,Near Arabian Desert,4.64
131,"Marrakesh, Morocco",May 1 – 29,"2,612.00","9,391 kilometers away",4.67
132,"Taghia, Morocco",May 1 – 29,580.00,"9,215 kilometers away",4.63
133,"Mhamid, Morocco",May 1 – 29,665.00,Near Sahara Desert,4.58
134,"Merzouga,Morocco, Morocco",May 1 – 29,"1,330.00",Near Sahara Desert,4.76
135,"Mhamid, Morocco",May 1 – 29,155.00,Near Sahara Desert,4.87
136,"Hassilabied, Morocco",May 1 – 29,"2,534.00",Near Sahara Desert,4.52
137,"Kanoi, India",May 1 – 29,"2,353.00",Near Thar Desert,4.82
138,"Merzouga, Morocco",May 1 – 29,537.00,Near Sahara Desert,4.75
139,"erg chebbi, Morocco",May 1 – 29,"1,115.00",Near Sahara Desert,4.83
140,"Zagora, Morocco",May 1 – 29,"1,163.00",Near Sahara Desert,4.82
141,"Merzouga, Morocco",May 1 – 29,"2,991.00",Near Sahara Desert,4.71
142,"Wadi Rum Village, Jordan",May 1 – 29,350.00,Near Arabian Desert,4.60
143,"Quairah District, Jordan",May 1 – 29,374.00,Near Arabian Desert,4.77
144,"Bawity, Egypt",May 1 – 29,"1,549.00",Near Sahara Desert,4.67
145,"Mhamid, Morocco",May 1 – 29,339.00,Near Sahara Desert,4.17
146,"Ghewara, India",May 1 – 29,"1,049.00",Near Thar Desert,4.53
147,"Merzouga, Morocco",May 1 – 29,399.00,Near Sahara Desert,4.58
148,"Province de Ouarzazate, Morocco",May 1 – 29,509.00,"9,336 kilometers away",4.59
149,"Quairah District, Jordan",May 1 – 29,"1,260.00",Near Arabian Desert,4.66
150,"Agdz, Morocco",May 1 – 29,819.00,Near Sahara Desert,4.67
151,"Jaisalmer, India",May 1 – 29,"1,523.00",Near Thar Desert,4.75
152,"Qesm Siwah, Egypt",May 1 – 29,"2,369.00",Near Sahara Desert,4.74
153,"Merzouga, Morocco",May 1 – 29,"2,425.00",Near Sahara Desert,4.86
154,"Marrakesh, Morocco",May 1 – 29,"2,326.00",Near Sahara Desert,4.76
155,"Zagora, Morocco",May 1 – 29,"3,153.00",Near Sahara Desert,4.67
156,"Jaisalmer, India",May 1 – 29,"2,039.00",Near Thar Desert,4.46
157,"Zagora, Morocco",May 1 – 29,"2,542.00",Near Sahara Desert,4.69
158,"Khamlia, Morocco",May 1 – 29,"1,442.00",Near Sahara Desert,4.69
159,"Marrakesh, Morocco",May 1 – 29,"2,922.00","9,391 kilometers away",3.50
160,"Erg Chebbi, Morocco",May 1 – 29,"9,969.00",Near Sahara Desert,4.86
161,"Wadi Rum Village, Jordan",May 1 – 29,"1,260.00",Near Arabian Desert,4.74
162,"Todra River, Morocco",May 1 – 29,335.00,Near Sahara Desert,4.82
163,"Mhamid, Morocco",May 1 – 29,"1,163.00",Near Sahara Desert,4.63
164,"Mhamid, Morocco",May 1 – 29,392.00,Near Sahara Desert,4.58
165,"Jaisalmer, India",May 1 – 29,"1,252.00",Near Thar Desert,4.60
166,"Mhamid, Morocco",May 1 – 29,759.00,Near Sahara Desert,4.56
167,"Hassilabied, Morocco",May 1 – 29,"1,188.00",Near Sahara Desert,4.38
168,"Wadi Rum Village, Jordan",May 1 – 29,339.00,Near Arabian Desert,NaN
169,"Wadi Rum Village, Jordan",May 1 – 29,836.00,Near Arabian Desert,NaN
170,"Mhamid, Morocco",May 1 – 29,"1,163.00",Near Sahara Desert,NaN
171,"Mhamid, Morocco",May 1 – 29,"1,330.00",Near Sahara Desert,NaN
172,"Mhamid, Morocco",May 1 – 29,"1,371.00",Near Sahara Desert,NaN
173,"Marrakesh, Morocco",May 19 – Jun 16,"51,071.00","9,412 kilometers away",NaN
174,"Mhamid, Morocco",May 1 – 29,"1,196.00",Near Sahara Desert,NaN
175,"Tagounite, Morocco",May 1 – 29,997.00,Near Sahara Desert,NaN
176,"merzouga, Morocco",May 1 – 29,276.00,Near Sahara Desert,NaN
177,"Zagora, Morocco",May 1 – 29,"1,469.00",Near Sahara Desert,NaN
178,"Merzouga, Morocco",May 1 – 29,"7,976.00",Near Sahara Desert,NaN
179,"Wadi Rum Village, Jordan",May 1 – 29,"1,993.00",Near Arabian Desert,NaN
180,"Essaouira, Morocco",May 1 – 29,"5,386.00","9,536 kilometers away",NaN
181,"Santorini, Greece",May 1 – 29,"7,477.00","6,291 kilometers away",NaN
182,"Oumnass, Morocco",May 1 – 29,"3,745.00","9,405 kilometers away",NaN
183,"Marrakesh, Morocco",May 1 – 29,"8,307.00","9,373 kilometers away",NaN
184,"Essaouira, Morocco",May 1 – 29,"5,386.00","9,536 kilometers away",NaN
185,"Marrakesh, Morocco",May 5 – Jun 2,"19,440.00","9,387 kilometers away",NaN
186,"?????Marrakech, Morocco",May 1 – 29,"49,610.00","9,406 kilometers away",NaN
187,"Marrakech, Morocco",May 1 – 29,"5,360.00","9,389 kilometers away",NaN
188,"Tidzi, Morocco",May 1 – 29,"6,320.00","9,548 kilometers away",NaN
189,"Aqaba City, Jordan",May 1 – 29,706.00,Near Arabian Desert,NaN
190,"Ait Bihi, Morocco",May 1 – 29,"1,303.00","9,586 kilometers away",NaN
191,"Ouarzazate, Morocco",May 1 – 29,231.00,"9,329 kilometers away",NaN
192,"Tamesluht, Morocco",May 1 – 29,"17,752.00","9,404 kilometers away",NaN
193,"Aït Ben Haddou, Morocco",May 1 – 29,615.00,"9,341 kilometers away",NaN
194,"Wadi Rum Village, Jordan",May 1 – 29,396.00,Near Arabian Desert,NaN
195,"Aït Ben Haddou, Morocco",May 1 – 29,493.00,"9,341 kilometers away",NaN
196,"Ouarzazate, Morocco",May 1 – 29,"1,553.00","9,327 kilometers away",NaN
197,"Ait Bihi, Morocco",May 1 – 29,"1,063.00","9,586 kilometers away",NaN
198,"Ovnat , Israel",May 1 – 29,"3,094.00",Near Syrian Desert,NaN
199,"Ouarzazate, Morocco",May 1 – 29,296.00,"9,329 kilometers away",NaN
200,"Essaouira, Morocco",May 1 – 29,"5,386.00","9,536 kilometers away",NaN
201,"Faiyum, Egypt",May 1 – 29,"1,239.00",Near Sahara Desert,NaN
202,"Marrakech, Morocco",May 1 – 29,"9,969.00","9,384 kilometers away",NaN
203,"Mhamid, Morocco",May 1 – 29,532.00,Near Sahara Desert,NaN
204,"Merzouga , Morocco",May 1 – 29,665.00,Near Sahara Desert,NaN
205,"Mhamid, Morocco",May 1 – 29,375.00,Near Sahara Desert,NaN
206,"Ezuz, Israel",May 1 – 29,"2,635.00",Near Arabian Desert,NaN
207,"Es Sabria, Tunisia",May 1 – 29,954.00,Near Sahara Desert,NaN
208,"Jaisalmer Rural, India",May 1 – 29,393.00,Near Thar Desert,NaN
209,"Errachidia Province, Morocco",May 1 – 29,455.00,Near Sahara Desert,NaN
210,"Ma'an Governorate, Jordan",May 1 – 29,"1,993.00",Near Syrian Desert,NaN
211,"Boumalne Dades, Morocco",May 1 – 29,658.00,Near Sahara Desert,NaN
212,"Nuweibaa, Egypt",May 1 – 29,496.00,Near Arabian Desert,NaN
213,"Zagora, Morocco",May 1 – 29,918.00,Near Sahara Desert,NaN
214,"Aït Benhaddou, Morocco",May 1 – 29,"1,455.00","9,340 kilometers away",NaN
215,"Petra, Jordan, Jordan",May 1 – 29,687.00,Near Syrian Desert,NaN
216,"Wadi Rum Village, Jordan",May 1 – 29,465.00,Near Arabian Desert,NaN
217,"Essaouira, Morocco",May 1 – 29,"5,386.00","9,536 kilometers away",NaN
218,"Palea Agia Roumeli, Greece",May 1 – 29,851.00,"6,442 kilometers away",NaN
219,"Mhamid, Morocco",May 1 – 29,582.00,Near Sahara Desert,NaN
220,"Zagora, Morocco",May 1 – 29,657.00,Near Sahara Desert,NaN
221,"Órzola, Spain",May 1 – 29,"2,662.00","9,976 kilometers away",NaN
222,"Douz, Tunisia",May 1 – 29,"1,526.00",Near Sahara Desert,NaN
223,"Telouet, Morocco",May 1 – 29,404.00,"9,331 kilometers away",NaN
224,"Tinghir, Morocco",May 1 – 29,665.00,Near Sahara Desert,NaN
225,"Assouan, Aswan, Egypt",May 1 – 29,929.00,Near Sahara Desert,NaN
226,"Kathodi, India",May 1 – 29,184.00,Near Thar Desert,NaN
227,"Ouarzazate, Morocco",May 1 – 29,464.00,"9,340 kilometers away",NaN
228,"Abu AR Rish Qebli, Egypt",May 1 – 29,"1,163.00",Near Sahara Desert,NaN
229,"Merzouga, Morocco",May 1 – 29,463.00,Near Sahara Desert,NaN
230,"Wadi Rum Village, Jordan",May 1 – 29,178.00,Near Arabian Desert,NaN
231,"Demnat, Morocco",May 1 – 29,947.00,"9,296 kilometers away",NaN
232,"Quairah District, Jordan",May 1 – 29,501.00,Near Arabian Desert,NaN
233,"Petra - Wadi Musa, Jordan",May 1 – 29,"1,041.00",Near Syrian Desert,NaN
234,"Aït Ben Haddou, Morocco",May 1 – 29,590.00,"9,337 kilometers away",NaN
235,"Wadi Rum Village, Jordan",May 1 – 29,"1,053.00",Near Arabian Desert,NaN
236,"Quairah District, Jordan",May 1 – 29,155.00,Near Arabian Desert,NaN
237,"Rissani, Morocco",May 1 – 29,396.00,Near Sahara Desert,NaN
238,"Mhamid, Morocco",May 1 – 29,951.00,Near Sahara Desert,NaN
239,"Wadi Rum Village, Jordan",May 1 – 29,786.00,Near Arabian Desert,NaN
240,"Awrir , Morocco",May 1 – 29,"5,951.00","9,584 kilometers away",NaN
241,"Ras al-Khaimah , UAE",May 1 – 29,"3,038.00",Near Arabian Desert,NaN
242,"Merzouga, Morocco",May 1 – 29,"1,202.00",Near Sahara Desert,NaN
243,"??????????, Morocco",May 1 – 29,898.00,Near Sahara Desert,NaN
244,"Charco del Palo, Spain",May 1 – 29,"1,958.00","9,983 kilometers away",NaN
245,"Nijar (Almería), Spain",May 1 – 29,"2,663.00","8,657 kilometers away",NaN
246,"Mogán, Spain",May 1 – 29,"2,383.00","10,246 kilometers away",NaN
247,"Alhaurín el Grande, Spain",May 1 – 29,"12,816.00","8,891 kilometers away",NaN
248,"Níjar, Spain",May 1 – 29,"1,165.00","8,668 kilometers away",NaN
249,"Las Palmas, Spain",May 1 – 29,"3,605.00","10,057 kilometers away",NaN
250,"Swakopmund, Namibia",May 1 – 29,"6,894.00","9,682 kilometers away",NaN
251,"Antigua, Spain",May 1 – 29,"3,515.00","10,066 kilometers away",NaN
252,"Tarajalejo, Spain",May 1 – 29,"1,982.00","10,083 kilometers away",NaN
253,"Loxton, South Africa",May 1 – 29,"1,331.00","9,530 kilometers away",NaN
254,"Tarajalejo, Spain",May 1 – 29,"1,164.00","10,083 kilometers away",NaN
255,"Pozo de los Frailes, Spain",May 1 – 29,"3,140.00","8,667 kilometers away",NaN
256,"Tarajalejo, Spain",May 1 – 29,"1,898.00","10,083 kilometers away",NaN
257,"Palm-Mar, Spain",May 1 – 29,"8,230.00","10,319 kilometers away",NaN
258,"Las Hortichuelas, Spain",May 1 – 29,"1,767.00","8,658 kilometers away",NaN
259,"La Isleta del Moro, Spain",May 1 – 29,"2,329.00","8,662 kilometers away",NaN
260,"Tabernas, Spain",May 1 – 29,"1,327.00","8,681 kilometers away",NaN
261,"Caleta de Famara, Spain",May 1 – 29,"3,733.00","9,991 kilometers away",NaN
262,"Antas, Spain",May 1 – 29,"4,387.00","8,634 kilometers away",NaN
263,"El Roque, Spain",May 1 – 29,696.00,"10,050 kilometers away",NaN
264,"Tabernas, Spain",May 1 – 29,"2,064.00","8,681 kilometers away",NaN
265,"Cuevas del Almanzora, Spain",May 1 – 29,998.00,"8,631 kilometers away",NaN
266,"Tarajalejo, Spain",May 1 – 29,"1,898.00","10,083 kilometers away",NaN
267,"Montaña de Tindaya, Spain",May 1 – 29,"1,139.00","10,054 kilometers away",NaN
268,"El Pozo de los Frailes, Spain",May 1 – 29,"2,227.00","8,668 kilometers away",NaN
269,"Yaiza, Spain",May 1 – 29,"6,695.00","10,019 kilometers away",NaN
270,"Arrieta, Spain",May 1 – 29,"1,597.00","9,981 kilometers away",NaN
271,"Las Casitas, Spain",May 1 – 29,"17,481.00","10,017 kilometers away",NaN
272,"sceale bay, Australia",May 1 – 29,"4,699.00","7,821 kilometers away",NaN
273,"Caleta/Teguise, Spain",May 1 – 29,"1,869.00","9,993 kilometers away",NaN
274,"Bidiyah, Oman",May 1 – 29,"1,054.00",Near Arabian Desert,NaN
275,"Haría Lanzarote, Spain",May 1 – 29,"5,117.00","9,981 kilometers away",NaN
276,"Tefia , Spain",May 1 – 29,"2,326.00","10,058 kilometers away",NaN
277,"El Pozo de los Frailes, Spain",May 1 – 29,"2,994.00","8,668 kilometers away",NaN
278,"Tarajalejo, Spain",May 1 – 29,"1,616.00","10,083 kilometers away",NaN
279,"Las Palmas, Spain",May 1 – 29,"1,872.00","10,055 kilometers away",NaN

In [23]:
print(desert.columns.tolist())

['Desert name', 'Date', 'Price(In dollar)', 'Details', 'Rating', 'Month']

In [24]:
display(desert.columns)

Index(['Desert name', 'Date', 'Price(In dollar)', 'Details', 'Rating',
       'Month'],
      dtype='object')

In [25]:
desert["Price(In dollar)"] = (
    desert["Price(In dollar)"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .str.replace("$", "", regex=False)
    .str.strip()
)

desert["Price(In dollar)"] = pd.to_numeric(
    desert["Price(In dollar)"],
    errors="coerce"
)

In [26]:
desert = desert.rename(columns={
    "Price(In dollar)": "Price (In dollar)",
    "Rating": "Property Rating",
    "Details": "Property Proximity"
})

In [27]:
for col in desert.columns:
    print(col)

Desert name
Date
Price (In dollar)
Property Proximity
Property Rating
Month

In [28]:
print(desert.columns.tolist())

['Desert name', 'Date', 'Price (In dollar)', 'Property Proximity', 'Property Rating', 'Month']

In [29]:
desert = desert.rename(columns={
    "Property Rating": "Rating"
})

In [31]:
print(desert.columns.tolist())

['Desert name', 'Date', 'Price (In dollar)', 'Property Proximity', 'Rating', 'Month']

In [32]:
desert[["Property Location", "Country"]] = (
    desert["Desert name"]
    .str.split(",", n=1, expand=True)
)

desert["Property Location"] = desert["Property Location"].str.strip()
desert["Country"] = desert["Country"].str.strip()

In [33]:
desert = desert.rename(columns={
    "Details": "Property Proximity",
    "Price(In dollar)": "Price (In dollar)"
})

In [34]:
desert["Month"] = desert["Date"].str.extract(
    r"(January|February|March|April|May|June|July|August|September|October|November|December|Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)"
)

In [35]:
desert["Price (In dollar)"] = (
    desert["Price (In dollar)"]
    .astype(str)
    .str.replace(",", "", regex=False)
)

desert["Price (In dollar)"] = pd.to_numeric(
    desert["Price (In dollar)"],
    errors="coerce"
)

In [36]:
desert = desert[
    [
        "Property Location",
        "Country",
        "Month",
        "Property Proximity",
        "Price (In dollar)",
        "Rating"
    ]
]

display(desert)

,Property Location,Country,Month,Property Proximity,Price (In dollar),Rating
0,Mhamid,Morocco,May,Near Sahara Desert,479.0,4.79
1,Aqaba City,Jordan,May,Near Arabian Desert,2168.0,4.92
2,Tamesluht,Morocco,May,"9,404 kilometers away",17752.0,4.95
3,Al Bairat,Egypt,May,Near Sahara Desert,1982.0,4.88
4,Tamesluht,Morocco,May,"9,404 kilometers away",17752.0,4.87
5,Mitzpe Ramon,Israel,May,Near Arabian Desert,2502.0,4.81
6,M'Hamid El Ghizlane,Morocco,May,Near Sahara Desert,415.0,4.81
7,Tinghir,Morocco,May,Near Sahara Desert,1346.0,4.92
8,Skoura,Morocco,May,"9,293 kilometers away",928.0,4.91
9,MA,Morocco,May,Near Sahara Desert,857.0,4.86
10,Mitzpe Ramon,Israel,May,Near Arabian Desert,2945.0,4.81
11,Wadi Rum,Jordan,May,Near Arabian Desert,898.0,4.84
12,Jaisalmer,India,May,Near Thar Desert,449.0,4.79
13,Siwa,Egypt,May,Near Sahara Desert,991.0,4.90
14,Merzouga,Morocco,May,Near Sahara Desert,2937.0,4.83
15,Essaouira,Morocco,May,"9,536 kilometers away",5386.0,4.90
16,Jaisalmer,India,May,Near Thar Desert,284.0,4.86
17,Tzofar,Israel,May,Near Arabian Desert,1821.0,4.77
18,Ait Bihi,Morocco,May,"9,586 kilometers away",1096.0,4.94
19,Jaisalmer,India,May,Near Thar Desert,677.0,4.79
20,Al Bairat,Egypt,May,Near Sahara Desert,1670.0,5.00
21,Órzola,Spain,May,"9,976 kilometers away",2396.0,4.90
22,Hassilabied,Morocco,May,Near Sahara Desert,970.0,4.94
23,Aglou,Morocco,May,"9,637 kilometers away",2792.0,5.00
24,Takojt,Morocco,May,Near Sahara Desert,371.0,5.00
25,Ouarzazate,Morocco,May,"9,327 kilometers away",530.0,4.67
26,Wadi Rum Village,Jordan,May,Near Arabian Desert,823.0,5.00
27,Marrakech,Morocco,May,"9,391 kilometers away",3561.0,4.94
28,Wadi Rum Village,Jordan,May,Near Arabian Desert,898.0,4.86
29,M'Hamid El Ghizlane,Morocco,May,Near Sahara Desert,340.0,5.00
30,Tamesluht,Morocco,May,"9,406 kilometers away",12800.0,4.77
31,Mhamid,Morocco,May,Near Sahara Desert,179.0,4.89
32,Arad,Israel,May,Near Arabian Desert,3737.0,4.82
33,Merzouga,Morocco,May,Near Sahara Desert,840.0,4.98
34,Mhamid,Morocco,May,Near Sahara Desert,1145.0,4.87
35,???????,Morocco,May,"9,586 kilometers away",1149.0,4.96
36,Wadi Rum Village,Jordan,May,Near Arabian Desert,294.0,4.89
37,Marrakesh,Morocco,May,"9,414 kilometers away",7515.0,4.94
38,Triopetra,Greece,May,"6,390 kilometers away",3209.0,4.82
39,Ksar Bounou (Oasis de M´hamid Alguizlane ),Morocco,May,Near Sahara Desert,285.0,4.95
40,????,Israel,May,Near Arabian Desert,2082.0,4.88
41,Arad,Israel,May,Near Arabian Desert,1734.0,5.00
42,???? ?????,Egypt,May,Near Arabian Desert,598.0,4.94
43,Midreshet Ben-Gurion,Israel,May,Near Arabian Desert,2994.0,5.00
44,M'HAMID,Morocco,May,Near Sahara Desert,305.0,4.86
45,Hassilabied,Morocco,May,Near Sahara Desert,997.0,4.76
46,Khuri,India,May,Near Thar Desert,375.0,4.82
47,???? ???? ??,Jordan,May,Near Arabian Desert,279.0,4.83
48,Mhamid,Morocco,May,Near Sahara Desert,731.0,4.92
49,Tamesluht,Morocco,May,"9,404 kilometers away",17752.0,5.00
50,Tamesluht,Morocco,May,"9,406 kilometers away",10473.0,4.85
51,Kalya,Israel,May,Near Syrian Desert,7228.0,5.00
52,Birkat al Maraqi,Egypt,May,Near Sahara Desert,249.0,5.00
53,Aqaba,Jordan,May,Near Arabian Desert,2061.0,5.00
54,Luxor,Egypt,May,Near Sahara Desert,347.0,5.00
55,Jaisalmer,India,May,Near Thar Desert,562.0,4.88
56,Oued El Khil,Tunisia,May,Near Sahara Desert,749.0,4.94
57,Mhamid,Morocco,May,Near Sahara Desert,207.0,5.00
58,commune rurale Fritissa,Morocco,May,"8,935 kilometers away",587.0,5.00
59,Tiznit,Morocco,May,"9,635 kilometers away",7687.0,5.00
60,Wadi Rum Village,Jordan,May,Near Arabian Desert,368.0,5.00
61,Hassilabied,Morocco,May,Near Sahara Desert,822.0,5.00
62,Fint,Morocco,May,"9,328 kilometers away",831.0,4.67
63,Arad,Israel,May,Near Arabian Desert,8080.0,5.00
64,Tamesluht,Morocco,May,"9,406 kilometers away",10473.0,5.00
65,Marrakech Alentours,Morocco,May,"9,379 kilometers away",35293.0,5.00
66,Merzouga,Morocco,May,Near Sahara Desert,877.0,5.00
67,Zagora,Morocco,May,Near Sahara Desert,256.0,5.00
68,Hassilabied,Morocco,May,Near Sahara Desert,263.0,4.67
69,Es Sabria,Tunisia,May,Near Sahara Desert,932.0,4.62
70,MA,Morocco,May,Near Sahara Desert,542.0,4.78
71,Al Ula,Saudi Arabia,May,Near Arabian Desert,16519.0,4.87
72,Nazlet El-Semman,Egypt,May,Near Sahara Desert,1370.0,4.63
73,Douz,Tunisia,May,Near Sahara Desert,1896.0,4.78
74,Arad,Israel,May,Near Arabian Desert,4209.0,4.78
75,Jaisalmer,India,May,Near Thar Desert,449.0,4.74
76,Zagora,Morocco,May,Near Sahara Desert,190.0,4.76
77,Hassilabied,Morocco,May,Near Sahara Desert,455.0,4.73
78,Zagora,Morocco,May,Near Sahara Desert,798.0,4.52
79,Merzouga,Morocco,May,Near Sahara Desert,780.0,4.79
80,Tinghir,Morocco,May,Near Sahara Desert,1346.0,4.67
81,Siwa Oasis,Egypt,May,Near Sahara Desert,867.0,4.70
82,Zagora,Morocco,May,Near Sahara Desert,466.0,4.67
83,Zagora,Morocco,May,Near Sahara Desert,425.0,4.43
84,Jaisalmer,India,May,Near Thar Desert,1198.0,4.52
85,Marrakech,Morocco,May,"9,390 kilometers away",648.0,4.76
86,Qesm Siwah,Egypt,May,Near Sahara Desert,790.0,4.76
87,Aoufous,Morocco,May,Near Sahara Desert,663.0,4.75
88,Wadi Rum Village,Jordan,May,Near Arabian Desert,244.0,4.50
89,Marrakech,Morocco,May,"9,391 kilometers away",3061.0,4.83
90,Sam,India,May,Near Thar Desert,628.0,4.23
91,Hassilabied,Morocco,May,Near Sahara Desert,1515.0,4.76
92,Kfar Adumim,Israel,May,Near Syrian Desert,4248.0,4.59
93,Essaouira,Morocco,May,"9,536 kilometers away",8977.0,4.89
94,Stavros,Greece,May,"6,425 kilometers away",9601.0,4.57
95,Merzouga,Morocco,May,Near Sahara Desert,812.0,4.84
96,Dahab,Egypt,May,Near Arabian Desert,1512.0,4.76
97,Ouarzazate,Morocco,May,"9,349 kilometers away",897.0,4.68
98,Tamesluht,Morocco,May,"9,406 kilometers away",10473.0,4.38
99,Merzouga,Morocco,May,Near Sahara Desert,2061.0,4.51
100,Boumalne Dades,Morocco,May,Near Sahara Desert,2359.0,4.50
101,Hassilabied,Morocco,May,Near Sahara Desert,1184.0,4.71
102,Bawity,Egypt,May,Near Sahara Desert,1239.0,4.75
103,Wadi rum,Jordan,May,Near Arabian Desert,217.0,4.70
104,Nador,Morocco,May,"8,770 kilometers away",1225.0,4.62
105,Hassilabied,Morocco,May,Near Sahara Desert,426.0,4.67
106,Ezuz,Israel,May,Near Arabian Desert,5545.0,4.00
107,Mhamid,Morocco,May,Near Sahara Desert,744.0,4.56
108,Mhamid,Morocco,May,Near Sahara Desert,565.0,4.67
109,Wadi Rum Village,Jordan,May,Near Arabian Desert,232.0,4.68
110,Merzouga,Morocco,May,Near Sahara Desert,299.0,4.82
111,Zagora,Morocco,May,Near Sahara Desert,220.0,4.60
112,M'Hamid El Ghizlane,Morocco,May,Near Sahara Desert,764.0,4.30
113,Mhamid,Morocco,May,Near Sahara Desert,1163.0,4.50
114,Khamlia,Morocco,May,Near Sahara Desert,1442.0,3.67
115,Ouarzazate,Morocco,May,"9,341 kilometers away",2326.0,4.68
116,Jaisalmer,India,May,Near Thar Desert,1310.0,4.71
117,Wadi Rum Village,Jordan,May,Near Arabian Desert,350.0,4.71
118,Zagora,Morocco,May,Near Sahara Desert,930.0,4.25
119,Quairah District,Jordan,May,Near Arabian Desert,155.0,4.84
120,Jaisalmer,India,May,Near Thar Desert,2039.0,4.20
121,Wadi Rum Village,Jordan,May,Near Arabian Desert,294.0,4.50
122,Merzouga,Morocco,May,Near Sahara Desert,2966.0,4.11
123,Mhamid,Morocco,May,Near Sahara Desert,295.0,4.53
124,Jaisalmer,India,May,Near Thar Desert,233.0,3.67
125,Ouled Arbia,Morocco,May,"9,295 kilometers away",2758.0,4.15
126,Merzouga,Morocco,May,Near Sahara Desert,1848.0,4.00
127,Bikaner,India,May,Near Thar Desert,1514.0,4.67
128,Tighza/Telouet,Morocco,May,"9,328 kilometers away",523.0,4.47
129,Merzouga,Morocco,May,Near Sahara Desert,989.0,4.74
130,Aqaba City,Jordan,May,Near Arabian Desert,341.0,4.64
131,Marrakesh,Morocco,May,"9,391 kilometers away",2612.0,4.67
132,Taghia,Morocco,May,"9,215 kilometers away",580.0,4.63
133,Mhamid,Morocco,May,Near Sahara Desert,665.0,4.58
134,Merzouga,"Morocco, Morocco",May,Near Sahara Desert,1330.0,4.76
135,Mhamid,Morocco,May,Near Sahara Desert,155.0,4.87
136,Hassilabied,Morocco,May,Near Sahara Desert,2534.0,4.52
137,Kanoi,India,May,Near Thar Desert,2353.0,4.82
138,Merzouga,Morocco,May,Near Sahara Desert,537.0,4.75
139,erg chebbi,Morocco,May,Near Sahara Desert,1115.0,4.83
140,Zagora,Morocco,May,Near Sahara Desert,1163.0,4.82
141,Merzouga,Morocco,May,Near Sahara Desert,2991.0,4.71
142,Wadi Rum Village,Jordan,May,Near Arabian Desert,350.0,4.60
143,Quairah District,Jordan,May,Near Arabian Desert,374.0,4.77
144,Bawity,Egypt,May,Near Sahara Desert,1549.0,4.67
145,Mhamid,Morocco,May,Near Sahara Desert,339.0,4.17
146,Ghewara,India,May,Near Thar Desert,1049.0,4.53
147,Merzouga,Morocco,May,Near Sahara Desert,399.0,4.58
148,Province de Ouarzazate,Morocco,May,"9,336 kilometers away",509.0,4.59
149,Quairah District,Jordan,May,Near Arabian Desert,1260.0,4.66
150,Agdz,Morocco,May,Near Sahara Desert,819.0,4.67
151,Jaisalmer,India,May,Near Thar Desert,1523.0,4.75
152,Qesm Siwah,Egypt,May,Near Sahara Desert,2369.0,4.74
153,Merzouga,Morocco,May,Near Sahara Desert,2425.0,4.86
154,Marrakesh,Morocco,May,Near Sahara Desert,2326.0,4.76
155,Zagora,Morocco,May,Near Sahara Desert,3153.0,4.67
156,Jaisalmer,India,May,Near Thar Desert,2039.0,4.46
157,Zagora,Morocco,May,Near Sahara Desert,2542.0,4.69
158,Khamlia,Morocco,May,Near Sahara Desert,1442.0,4.69
159,Marrakesh,Morocco,May,"9,391 kilometers away",2922.0,3.50
160,Erg Chebbi,Morocco,May,Near Sahara Desert,9969.0,4.86
161,Wadi Rum Village,Jordan,May,Near Arabian Desert,1260.0,4.74
162,Todra River,Morocco,May,Near Sahara Desert,335.0,4.82
163,Mhamid,Morocco,May,Near Sahara Desert,1163.0,4.63
164,Mhamid,Morocco,May,Near Sahara Desert,392.0,4.58
165,Jaisalmer,India,May,Near Thar Desert,1252.0,4.60
166,Mhamid,Morocco,May,Near Sahara Desert,759.0,4.56
167,Hassilabied,Morocco,May,Near Sahara Desert,1188.0,4.38
168,Wadi Rum Village,Jordan,May,Near Arabian Desert,339.0,NaN
169,Wadi Rum Village,Jordan,May,Near Arabian Desert,836.0,NaN
170,Mhamid,Morocco,May,Near Sahara Desert,1163.0,NaN
171,Mhamid,Morocco,May,Near Sahara Desert,1330.0,NaN
172,Mhamid,Morocco,May,Near Sahara Desert,1371.0,NaN
173,Marrakesh,Morocco,May,"9,412 kilometers away",51071.0,NaN
174,Mhamid,Morocco,May,Near Sahara Desert,1196.0,NaN
175,Tagounite,Morocco,May,Near Sahara Desert,997.0,NaN
176,merzouga,Morocco,May,Near Sahara Desert,276.0,NaN
177,Zagora,Morocco,May,Near Sahara Desert,1469.0,NaN
178,Merzouga,Morocco,May,Near Sahara Desert,7976.0,NaN
179,Wadi Rum Village,Jordan,May,Near Arabian Desert,1993.0,NaN
180,Essaouira,Morocco,May,"9,536 kilometers away",5386.0,NaN
181,Santorini,Greece,May,"6,291 kilometers away",7477.0,NaN
182,Oumnass,Morocco,May,"9,405 kilometers away",3745.0,NaN
183,Marrakesh,Morocco,May,"9,373 kilometers away",8307.0,NaN
184,Essaouira,Morocco,May,"9,536 kilometers away",5386.0,NaN
185,Marrakesh,Morocco,May,"9,387 kilometers away",19440.0,NaN
186,?????Marrakech,Morocco,May,"9,406 kilometers away",49610.0,NaN
187,Marrakech,Morocco,May,"9,389 kilometers away",5360.0,NaN
188,Tidzi,Morocco,May,"9,548 kilometers away",6320.0,NaN
189,Aqaba City,Jordan,May,Near Arabian Desert,706.0,NaN
190,Ait Bihi,Morocco,May,"9,586 kilometers away",1303.0,NaN
191,Ouarzazate,Morocco,May,"9,329 kilometers away",231.0,NaN
192,Tamesluht,Morocco,May,"9,404 kilometers away",17752.0,NaN
193,Aït Ben Haddou,Morocco,May,"9,341 kilometers away",615.0,NaN
194,Wadi Rum Village,Jordan,May,Near Arabian Desert,396.0,NaN
195,Aït Ben Haddou,Morocco,May,"9,341 kilometers away",493.0,NaN
196,Ouarzazate,Morocco,May,"9,327 kilometers away",1553.0,NaN
197,Ait Bihi,Morocco,May,"9,586 kilometers away",1063.0,NaN
198,Ovnat,Israel,May,Near Syrian Desert,3094.0,NaN
199,Ouarzazate,Morocco,May,"9,329 kilometers away",296.0,NaN
200,Essaouira,Morocco,May,"9,536 kilometers away",5386.0,NaN
201,Faiyum,Egypt,May,Near Sahara Desert,1239.0,NaN
202,Marrakech,Morocco,May,"9,384 kilometers away",9969.0,NaN
203,Mhamid,Morocco,May,Near Sahara Desert,532.0,NaN
204,Merzouga,Morocco,May,Near Sahara Desert,665.0,NaN
205,Mhamid,Morocco,May,Near Sahara Desert,375.0,NaN
206,Ezuz,Israel,May,Near Arabian Desert,2635.0,NaN
207,Es Sabria,Tunisia,May,Near Sahara Desert,954.0,NaN
208,Jaisalmer Rural,India,May,Near Thar Desert,393.0,NaN
209,Errachidia Province,Morocco,May,Near Sahara Desert,455.0,NaN
210,Ma'an Governorate,Jordan,May,Near Syrian Desert,1993.0,NaN
211,Boumalne Dades,Morocco,May,Near Sahara Desert,658.0,NaN
212,Nuweibaa,Egypt,May,Near Arabian Desert,496.0,NaN
213,Zagora,Morocco,May,Near Sahara Desert,918.0,NaN
214,Aït Benhaddou,Morocco,May,"9,340 kilometers away",1455.0,NaN
215,Petra,"Jordan, Jordan",May,Near Syrian Desert,687.0,NaN
216,Wadi Rum Village,Jordan,May,Near Arabian Desert,465.0,NaN
217,Essaouira,Morocco,May,"9,536 kilometers away",5386.0,NaN
218,Palea Agia Roumeli,Greece,May,"6,442 kilometers away",851.0,NaN
219,Mhamid,Morocco,May,Near Sahara Desert,582.0,NaN
220,Zagora,Morocco,May,Near Sahara Desert,657.0,NaN
221,Órzola,Spain,May,"9,976 kilometers away",2662.0,NaN
222,Douz,Tunisia,May,Near Sahara Desert,1526.0,NaN
223,Telouet,Morocco,May,"9,331 kilometers away",404.0,NaN
224,Tinghir,Morocco,May,Near Sahara Desert,665.0,NaN
225,Assouan,"Aswan, Egypt",May,Near Sahara Desert,929.0,NaN
226,Kathodi,India,May,Near Thar Desert,184.0,NaN
227,Ouarzazate,Morocco,May,"9,340 kilometers away",464.0,NaN
228,Abu AR Rish Qebli,Egypt,May,Near Sahara Desert,1163.0,NaN
229,Merzouga,Morocco,May,Near Sahara Desert,463.0,NaN
230,Wadi Rum Village,Jordan,May,Near Arabian Desert,178.0,NaN
231,Demnat,Morocco,May,"9,296 kilometers away",947.0,NaN
232,Quairah District,Jordan,May,Near Arabian Desert,501.0,NaN
233,Petra - Wadi Musa,Jordan,May,Near Syrian Desert,1041.0,NaN
234,Aït Ben Haddou,Morocco,May,"9,337 kilometers away",590.0,NaN
235,Wadi Rum Village,Jordan,May,Near Arabian Desert,1053.0,NaN
236,Quairah District,Jordan,May,Near Arabian Desert,155.0,NaN
237,Rissani,Morocco,May,Near Sahara Desert,396.0,NaN
238,Mhamid,Morocco,May,Near Sahara Desert,951.0,NaN
239,Wadi Rum Village,Jordan,May,Near Arabian Desert,786.0,NaN
240,Awrir,Morocco,May,"9,584 kilometers away",5951.0,NaN
241,Ras al-Khaimah,UAE,May,Near Arabian Desert,3038.0,NaN
242,Merzouga,Morocco,May,Near Sahara Desert,1202.0,NaN
243,??????????,Morocco,May,Near Sahara Desert,898.0,NaN
244,Charco del Palo,Spain,May,"9,983 kilometers away",1958.0,NaN
245,Nijar (Almería),Spain,May,"8,657 kilometers away",2663.0,NaN
246,Mogán,Spain,May,"10,246 kilometers away",2383.0,NaN
247,Alhaurín el Grande,Spain,May,"8,891 kilometers away",12816.0,NaN
248,Níjar,Spain,May,"8,668 kilometers away",1165.0,NaN
249,Las Palmas,Spain,May,"10,057 kilometers away",3605.0,NaN
250,Swakopmund,Namibia,May,"9,682 kilometers away",6894.0,NaN
251,Antigua,Spain,May,"10,066 kilometers away",3515.0,NaN
252,Tarajalejo,Spain,May,"10,083 kilometers away",1982.0,NaN
253,Loxton,South Africa,May,"9,530 kilometers away",1331.0,NaN
254,Tarajalejo,Spain,May,"10,083 kilometers away",1164.0,NaN
255,Pozo de los Frailes,Spain,May,"8,667 kilometers away",3140.0,NaN
256,Tarajalejo,Spain,May,"10,083 kilometers away",1898.0,NaN
257,Palm-Mar,Spain,May,"10,319 kilometers away",8230.0,NaN
258,Las Hortichuelas,Spain,May,"8,658 kilometers away",1767.0,NaN
259,La Isleta del Moro,Spain,May,"8,662 kilometers away",2329.0,NaN
260,Tabernas,Spain,May,"8,681 kilometers away",1327.0,NaN
261,Caleta de Famara,Spain,May,"9,991 kilometers away",3733.0,NaN
262,Antas,Spain,May,"8,634 kilometers away",4387.0,NaN
263,El Roque,Spain,May,"10,050 kilometers away",696.0,NaN
264,Tabernas,Spain,May,"8,681 kilometers away",2064.0,NaN
265,Cuevas del Almanzora,Spain,May,"8,631 kilometers away",998.0,NaN
266,Tarajalejo,Spain,May,"10,083 kilometers away",1898.0,NaN
267,Montaña de Tindaya,Spain,May,"10,054 kilometers away",1139.0,NaN
268,El Pozo de los Frailes,Spain,May,"8,668 kilometers away",2227.0,NaN
269,Yaiza,Spain,May,"10,019 kilometers away",6695.0,NaN
270,Arrieta,Spain,May,"9,981 kilometers away",1597.0,NaN
271,Las Casitas,Spain,May,"10,017 kilometers away",17481.0,NaN
272,sceale bay,Australia,May,"7,821 kilometers away",4699.0,NaN
273,Caleta/Teguise,Spain,May,"9,993 kilometers away",1869.0,NaN
274,Bidiyah,Oman,May,Near Arabian Desert,1054.0,NaN
275,Haría Lanzarote,Spain,May,"9,981 kilometers away",5117.0,NaN
276,Tefia,Spain,May,"10,058 kilometers away",2326.0,NaN
277,El Pozo de los Frailes,Spain,May,"8,668 kilometers away",2994.0,NaN
278,Tarajalejo,Spain,May,"10,083 kilometers away",1616.0,NaN
279,Las Palmas,Spain,May,"10,055 kilometers away",1872.0,NaN

In [37]:
print(desert.columns.tolist())

['Property Location', 'Country', 'Month', 'Property Proximity', 'Price (In dollar)', 'Rating']

In [38]:
display(desert)

,Property Location,Country,Month,Property Proximity,Price (In dollar),Rating
0,Mhamid,Morocco,May,Near Sahara Desert,479.0,4.79
1,Aqaba City,Jordan,May,Near Arabian Desert,2168.0,4.92
2,Tamesluht,Morocco,May,"9,404 kilometers away",17752.0,4.95
3,Al Bairat,Egypt,May,Near Sahara Desert,1982.0,4.88
4,Tamesluht,Morocco,May,"9,404 kilometers away",17752.0,4.87
5,Mitzpe Ramon,Israel,May,Near Arabian Desert,2502.0,4.81
6,M'Hamid El Ghizlane,Morocco,May,Near Sahara Desert,415.0,4.81
7,Tinghir,Morocco,May,Near Sahara Desert,1346.0,4.92
8,Skoura,Morocco,May,"9,293 kilometers away",928.0,4.91
9,MA,Morocco,May,Near Sahara Desert,857.0,4.86
10,Mitzpe Ramon,Israel,May,Near Arabian Desert,2945.0,4.81
11,Wadi Rum,Jordan,May,Near Arabian Desert,898.0,4.84
12,Jaisalmer,India,May,Near Thar Desert,449.0,4.79
13,Siwa,Egypt,May,Near Sahara Desert,991.0,4.90
14,Merzouga,Morocco,May,Near Sahara Desert,2937.0,4.83
15,Essaouira,Morocco,May,"9,536 kilometers away",5386.0,4.90
16,Jaisalmer,India,May,Near Thar Desert,284.0,4.86
17,Tzofar,Israel,May,Near Arabian Desert,1821.0,4.77
18,Ait Bihi,Morocco,May,"9,586 kilometers away",1096.0,4.94
19,Jaisalmer,India,May,Near Thar Desert,677.0,4.79
20,Al Bairat,Egypt,May,Near Sahara Desert,1670.0,5.00
21,Órzola,Spain,May,"9,976 kilometers away",2396.0,4.90
22,Hassilabied,Morocco,May,Near Sahara Desert,970.0,4.94
23,Aglou,Morocco,May,"9,637 kilometers away",2792.0,5.00
24,Takojt,Morocco,May,Near Sahara Desert,371.0,5.00
25,Ouarzazate,Morocco,May,"9,327 kilometers away",530.0,4.67
26,Wadi Rum Village,Jordan,May,Near Arabian Desert,823.0,5.00
27,Marrakech,Morocco,May,"9,391 kilometers away",3561.0,4.94
28,Wadi Rum Village,Jordan,May,Near Arabian Desert,898.0,4.86
29,M'Hamid El Ghizlane,Morocco,May,Near Sahara Desert,340.0,5.00
30,Tamesluht,Morocco,May,"9,406 kilometers away",12800.0,4.77
31,Mhamid,Morocco,May,Near Sahara Desert,179.0,4.89
32,Arad,Israel,May,Near Arabian Desert,3737.0,4.82
33,Merzouga,Morocco,May,Near Sahara Desert,840.0,4.98
34,Mhamid,Morocco,May,Near Sahara Desert,1145.0,4.87
35,???????,Morocco,May,"9,586 kilometers away",1149.0,4.96
36,Wadi Rum Village,Jordan,May,Near Arabian Desert,294.0,4.89
37,Marrakesh,Morocco,May,"9,414 kilometers away",7515.0,4.94
38,Triopetra,Greece,May,"6,390 kilometers away",3209.0,4.82
39,Ksar Bounou (Oasis de M´hamid Alguizlane ),Morocco,May,Near Sahara Desert,285.0,4.95
40,????,Israel,May,Near Arabian Desert,2082.0,4.88
41,Arad,Israel,May,Near Arabian Desert,1734.0,5.00
42,???? ?????,Egypt,May,Near Arabian Desert,598.0,4.94
43,Midreshet Ben-Gurion,Israel,May,Near Arabian Desert,2994.0,5.00
44,M'HAMID,Morocco,May,Near Sahara Desert,305.0,4.86
45,Hassilabied,Morocco,May,Near Sahara Desert,997.0,4.76
46,Khuri,India,May,Near Thar Desert,375.0,4.82
47,???? ???? ??,Jordan,May,Near Arabian Desert,279.0,4.83
48,Mhamid,Morocco,May,Near Sahara Desert,731.0,4.92
49,Tamesluht,Morocco,May,"9,404 kilometers away",17752.0,5.00
50,Tamesluht,Morocco,May,"9,406 kilometers away",10473.0,4.85
51,Kalya,Israel,May,Near Syrian Desert,7228.0,5.00
52,Birkat al Maraqi,Egypt,May,Near Sahara Desert,249.0,5.00
53,Aqaba,Jordan,May,Near Arabian Desert,2061.0,5.00
54,Luxor,Egypt,May,Near Sahara Desert,347.0,5.00
55,Jaisalmer,India,May,Near Thar Desert,562.0,4.88
56,Oued El Khil,Tunisia,May,Near Sahara Desert,749.0,4.94
57,Mhamid,Morocco,May,Near Sahara Desert,207.0,5.00
58,commune rurale Fritissa,Morocco,May,"8,935 kilometers away",587.0,5.00
59,Tiznit,Morocco,May,"9,635 kilometers away",7687.0,5.00
60,Wadi Rum Village,Jordan,May,Near Arabian Desert,368.0,5.00
61,Hassilabied,Morocco,May,Near Sahara Desert,822.0,5.00
62,Fint,Morocco,May,"9,328 kilometers away",831.0,4.67
63,Arad,Israel,May,Near Arabian Desert,8080.0,5.00
64,Tamesluht,Morocco,May,"9,406 kilometers away",10473.0,5.00
65,Marrakech Alentours,Morocco,May,"9,379 kilometers away",35293.0,5.00
66,Merzouga,Morocco,May,Near Sahara Desert,877.0,5.00
67,Zagora,Morocco,May,Near Sahara Desert,256.0,5.00
68,Hassilabied,Morocco,May,Near Sahara Desert,263.0,4.67
69,Es Sabria,Tunisia,May,Near Sahara Desert,932.0,4.62
70,MA,Morocco,May,Near Sahara Desert,542.0,4.78
71,Al Ula,Saudi Arabia,May,Near Arabian Desert,16519.0,4.87
72,Nazlet El-Semman,Egypt,May,Near Sahara Desert,1370.0,4.63
73,Douz,Tunisia,May,Near Sahara Desert,1896.0,4.78
74,Arad,Israel,May,Near Arabian Desert,4209.0,4.78
75,Jaisalmer,India,May,Near Thar Desert,449.0,4.74
76,Zagora,Morocco,May,Near Sahara Desert,190.0,4.76
77,Hassilabied,Morocco,May,Near Sahara Desert,455.0,4.73
78,Zagora,Morocco,May,Near Sahara Desert,798.0,4.52
79,Merzouga,Morocco,May,Near Sahara Desert,780.0,4.79
80,Tinghir,Morocco,May,Near Sahara Desert,1346.0,4.67
81,Siwa Oasis,Egypt,May,Near Sahara Desert,867.0,4.70
82,Zagora,Morocco,May,Near Sahara Desert,466.0,4.67
83,Zagora,Morocco,May,Near Sahara Desert,425.0,4.43
84,Jaisalmer,India,May,Near Thar Desert,1198.0,4.52
85,Marrakech,Morocco,May,"9,390 kilometers away",648.0,4.76
86,Qesm Siwah,Egypt,May,Near Sahara Desert,790.0,4.76
87,Aoufous,Morocco,May,Near Sahara Desert,663.0,4.75
88,Wadi Rum Village,Jordan,May,Near Arabian Desert,244.0,4.50
89,Marrakech,Morocco,May,"9,391 kilometers away",3061.0,4.83
90,Sam,India,May,Near Thar Desert,628.0,4.23
91,Hassilabied,Morocco,May,Near Sahara Desert,1515.0,4.76
92,Kfar Adumim,Israel,May,Near Syrian Desert,4248.0,4.59
93,Essaouira,Morocco,May,"9,536 kilometers away",8977.0,4.89
94,Stavros,Greece,May,"6,425 kilometers away",9601.0,4.57
95,Merzouga,Morocco,May,Near Sahara Desert,812.0,4.84
96,Dahab,Egypt,May,Near Arabian Desert,1512.0,4.76
97,Ouarzazate,Morocco,May,"9,349 kilometers away",897.0,4.68
98,Tamesluht,Morocco,May,"9,406 kilometers away",10473.0,4.38
99,Merzouga,Morocco,May,Near Sahara Desert,2061.0,4.51
100,Boumalne Dades,Morocco,May,Near Sahara Desert,2359.0,4.50
101,Hassilabied,Morocco,May,Near Sahara Desert,1184.0,4.71
102,Bawity,Egypt,May,Near Sahara Desert,1239.0,4.75
103,Wadi rum,Jordan,May,Near Arabian Desert,217.0,4.70
104,Nador,Morocco,May,"8,770 kilometers away",1225.0,4.62
105,Hassilabied,Morocco,May,Near Sahara Desert,426.0,4.67
106,Ezuz,Israel,May,Near Arabian Desert,5545.0,4.00
107,Mhamid,Morocco,May,Near Sahara Desert,744.0,4.56
108,Mhamid,Morocco,May,Near Sahara Desert,565.0,4.67
109,Wadi Rum Village,Jordan,May,Near Arabian Desert,232.0,4.68
110,Merzouga,Morocco,May,Near Sahara Desert,299.0,4.82
111,Zagora,Morocco,May,Near Sahara Desert,220.0,4.60
112,M'Hamid El Ghizlane,Morocco,May,Near Sahara Desert,764.0,4.30
113,Mhamid,Morocco,May,Near Sahara Desert,1163.0,4.50
114,Khamlia,Morocco,May,Near Sahara Desert,1442.0,3.67
115,Ouarzazate,Morocco,May,"9,341 kilometers away",2326.0,4.68
116,Jaisalmer,India,May,Near Thar Desert,1310.0,4.71
117,Wadi Rum Village,Jordan,May,Near Arabian Desert,350.0,4.71
118,Zagora,Morocco,May,Near Sahara Desert,930.0,4.25
119,Quairah District,Jordan,May,Near Arabian Desert,155.0,4.84
120,Jaisalmer,India,May,Near Thar Desert,2039.0,4.20
121,Wadi Rum Village,Jordan,May,Near Arabian Desert,294.0,4.50
122,Merzouga,Morocco,May,Near Sahara Desert,2966.0,4.11
123,Mhamid,Morocco,May,Near Sahara Desert,295.0,4.53
124,Jaisalmer,India,May,Near Thar Desert,233.0,3.67
125,Ouled Arbia,Morocco,May,"9,295 kilometers away",2758.0,4.15
126,Merzouga,Morocco,May,Near Sahara Desert,1848.0,4.00
127,Bikaner,India,May,Near Thar Desert,1514.0,4.67
128,Tighza/Telouet,Morocco,May,"9,328 kilometers away",523.0,4.47
129,Merzouga,Morocco,May,Near Sahara Desert,989.0,4.74
130,Aqaba City,Jordan,May,Near Arabian Desert,341.0,4.64
131,Marrakesh,Morocco,May,"9,391 kilometers away",2612.0,4.67
132,Taghia,Morocco,May,"9,215 kilometers away",580.0,4.63
133,Mhamid,Morocco,May,Near Sahara Desert,665.0,4.58
134,Merzouga,"Morocco, Morocco",May,Near Sahara Desert,1330.0,4.76
135,Mhamid,Morocco,May,Near Sahara Desert,155.0,4.87
136,Hassilabied,Morocco,May,Near Sahara Desert,2534.0,4.52
137,Kanoi,India,May,Near Thar Desert,2353.0,4.82
138,Merzouga,Morocco,May,Near Sahara Desert,537.0,4.75
139,erg chebbi,Morocco,May,Near Sahara Desert,1115.0,4.83
140,Zagora,Morocco,May,Near Sahara Desert,1163.0,4.82
141,Merzouga,Morocco,May,Near Sahara Desert,2991.0,4.71
142,Wadi Rum Village,Jordan,May,Near Arabian Desert,350.0,4.60
143,Quairah District,Jordan,May,Near Arabian Desert,374.0,4.77
144,Bawity,Egypt,May,Near Sahara Desert,1549.0,4.67
145,Mhamid,Morocco,May,Near Sahara Desert,339.0,4.17
146,Ghewara,India,May,Near Thar Desert,1049.0,4.53
147,Merzouga,Morocco,May,Near Sahara Desert,399.0,4.58
148,Province de Ouarzazate,Morocco,May,"9,336 kilometers away",509.0,4.59
149,Quairah District,Jordan,May,Near Arabian Desert,1260.0,4.66
150,Agdz,Morocco,May,Near Sahara Desert,819.0,4.67
151,Jaisalmer,India,May,Near Thar Desert,1523.0,4.75
152,Qesm Siwah,Egypt,May,Near Sahara Desert,2369.0,4.74
153,Merzouga,Morocco,May,Near Sahara Desert,2425.0,4.86
154,Marrakesh,Morocco,May,Near Sahara Desert,2326.0,4.76
155,Zagora,Morocco,May,Near Sahara Desert,3153.0,4.67
156,Jaisalmer,India,May,Near Thar Desert,2039.0,4.46
157,Zagora,Morocco,May,Near Sahara Desert,2542.0,4.69
158,Khamlia,Morocco,May,Near Sahara Desert,1442.0,4.69
159,Marrakesh,Morocco,May,"9,391 kilometers away",2922.0,3.50
160,Erg Chebbi,Morocco,May,Near Sahara Desert,9969.0,4.86
161,Wadi Rum Village,Jordan,May,Near Arabian Desert,1260.0,4.74
162,Todra River,Morocco,May,Near Sahara Desert,335.0,4.82
163,Mhamid,Morocco,May,Near Sahara Desert,1163.0,4.63
164,Mhamid,Morocco,May,Near Sahara Desert,392.0,4.58
165,Jaisalmer,India,May,Near Thar Desert,1252.0,4.60
166,Mhamid,Morocco,May,Near Sahara Desert,759.0,4.56
167,Hassilabied,Morocco,May,Near Sahara Desert,1188.0,4.38
168,Wadi Rum Village,Jordan,May,Near Arabian Desert,339.0,NaN
169,Wadi Rum Village,Jordan,May,Near Arabian Desert,836.0,NaN
170,Mhamid,Morocco,May,Near Sahara Desert,1163.0,NaN
171,Mhamid,Morocco,May,Near Sahara Desert,1330.0,NaN
172,Mhamid,Morocco,May,Near Sahara Desert,1371.0,NaN
173,Marrakesh,Morocco,May,"9,412 kilometers away",51071.0,NaN
174,Mhamid,Morocco,May,Near Sahara Desert,1196.0,NaN
175,Tagounite,Morocco,May,Near Sahara Desert,997.0,NaN
176,merzouga,Morocco,May,Near Sahara Desert,276.0,NaN
177,Zagora,Morocco,May,Near Sahara Desert,1469.0,NaN
178,Merzouga,Morocco,May,Near Sahara Desert,7976.0,NaN
179,Wadi Rum Village,Jordan,May,Near Arabian Desert,1993.0,NaN
180,Essaouira,Morocco,May,"9,536 kilometers away",5386.0,NaN
181,Santorini,Greece,May,"6,291 kilometers away",7477.0,NaN
182,Oumnass,Morocco,May,"9,405 kilometers away",3745.0,NaN
183,Marrakesh,Morocco,May,"9,373 kilometers away",8307.0,NaN
184,Essaouira,Morocco,May,"9,536 kilometers away",5386.0,NaN
185,Marrakesh,Morocco,May,"9,387 kilometers away",19440.0,NaN
186,?????Marrakech,Morocco,May,"9,406 kilometers away",49610.0,NaN
187,Marrakech,Morocco,May,"9,389 kilometers away",5360.0,NaN
188,Tidzi,Morocco,May,"9,548 kilometers away",6320.0,NaN
189,Aqaba City,Jordan,May,Near Arabian Desert,706.0,NaN
190,Ait Bihi,Morocco,May,"9,586 kilometers away",1303.0,NaN
191,Ouarzazate,Morocco,May,"9,329 kilometers away",231.0,NaN
192,Tamesluht,Morocco,May,"9,404 kilometers away",17752.0,NaN
193,Aït Ben Haddou,Morocco,May,"9,341 kilometers away",615.0,NaN
194,Wadi Rum Village,Jordan,May,Near Arabian Desert,396.0,NaN
195,Aït Ben Haddou,Morocco,May,"9,341 kilometers away",493.0,NaN
196,Ouarzazate,Morocco,May,"9,327 kilometers away",1553.0,NaN
197,Ait Bihi,Morocco,May,"9,586 kilometers away",1063.0,NaN
198,Ovnat,Israel,May,Near Syrian Desert,3094.0,NaN
199,Ouarzazate,Morocco,May,"9,329 kilometers away",296.0,NaN
200,Essaouira,Morocco,May,"9,536 kilometers away",5386.0,NaN
201,Faiyum,Egypt,May,Near Sahara Desert,1239.0,NaN
202,Marrakech,Morocco,May,"9,384 kilometers away",9969.0,NaN
203,Mhamid,Morocco,May,Near Sahara Desert,532.0,NaN
204,Merzouga,Morocco,May,Near Sahara Desert,665.0,NaN
205,Mhamid,Morocco,May,Near Sahara Desert,375.0,NaN
206,Ezuz,Israel,May,Near Arabian Desert,2635.0,NaN
207,Es Sabria,Tunisia,May,Near Sahara Desert,954.0,NaN
208,Jaisalmer Rural,India,May,Near Thar Desert,393.0,NaN
209,Errachidia Province,Morocco,May,Near Sahara Desert,455.0,NaN
210,Ma'an Governorate,Jordan,May,Near Syrian Desert,1993.0,NaN
211,Boumalne Dades,Morocco,May,Near Sahara Desert,658.0,NaN
212,Nuweibaa,Egypt,May,Near Arabian Desert,496.0,NaN
213,Zagora,Morocco,May,Near Sahara Desert,918.0,NaN
214,Aït Benhaddou,Morocco,May,"9,340 kilometers away",1455.0,NaN
215,Petra,"Jordan, Jordan",May,Near Syrian Desert,687.0,NaN
216,Wadi Rum Village,Jordan,May,Near Arabian Desert,465.0,NaN
217,Essaouira,Morocco,May,"9,536 kilometers away",5386.0,NaN
218,Palea Agia Roumeli,Greece,May,"6,442 kilometers away",851.0,NaN
219,Mhamid,Morocco,May,Near Sahara Desert,582.0,NaN
220,Zagora,Morocco,May,Near Sahara Desert,657.0,NaN
221,Órzola,Spain,May,"9,976 kilometers away",2662.0,NaN
222,Douz,Tunisia,May,Near Sahara Desert,1526.0,NaN
223,Telouet,Morocco,May,"9,331 kilometers away",404.0,NaN
224,Tinghir,Morocco,May,Near Sahara Desert,665.0,NaN
225,Assouan,"Aswan, Egypt",May,Near Sahara Desert,929.0,NaN
226,Kathodi,India,May,Near Thar Desert,184.0,NaN
227,Ouarzazate,Morocco,May,"9,340 kilometers away",464.0,NaN
228,Abu AR Rish Qebli,Egypt,May,Near Sahara Desert,1163.0,NaN
229,Merzouga,Morocco,May,Near Sahara Desert,463.0,NaN
230,Wadi Rum Village,Jordan,May,Near Arabian Desert,178.0,NaN
231,Demnat,Morocco,May,"9,296 kilometers away",947.0,NaN
232,Quairah District,Jordan,May,Near Arabian Desert,501.0,NaN
233,Petra - Wadi Musa,Jordan,May,Near Syrian Desert,1041.0,NaN
234,Aït Ben Haddou,Morocco,May,"9,337 kilometers away",590.0,NaN
235,Wadi Rum Village,Jordan,May,Near Arabian Desert,1053.0,NaN
236,Quairah District,Jordan,May,Near Arabian Desert,155.0,NaN
237,Rissani,Morocco,May,Near Sahara Desert,396.0,NaN
238,Mhamid,Morocco,May,Near Sahara Desert,951.0,NaN
239,Wadi Rum Village,Jordan,May,Near Arabian Desert,786.0,NaN
240,Awrir,Morocco,May,"9,584 kilometers away",5951.0,NaN
241,Ras al-Khaimah,UAE,May,Near Arabian Desert,3038.0,NaN
242,Merzouga,Morocco,May,Near Sahara Desert,1202.0,NaN
243,??????????,Morocco,May,Near Sahara Desert,898.0,NaN
244,Charco del Palo,Spain,May,"9,983 kilometers away",1958.0,NaN
245,Nijar (Almería),Spain,May,"8,657 kilometers away",2663.0,NaN
246,Mogán,Spain,May,"10,246 kilometers away",2383.0,NaN
247,Alhaurín el Grande,Spain,May,"8,891 kilometers away",12816.0,NaN
248,Níjar,Spain,May,"8,668 kilometers away",1165.0,NaN
249,Las Palmas,Spain,May,"10,057 kilometers away",3605.0,NaN
250,Swakopmund,Namibia,May,"9,682 kilometers away",6894.0,NaN
251,Antigua,Spain,May,"10,066 kilometers away",3515.0,NaN
252,Tarajalejo,Spain,May,"10,083 kilometers away",1982.0,NaN
253,Loxton,South Africa,May,"9,530 kilometers away",1331.0,NaN
254,Tarajalejo,Spain,May,"10,083 kilometers away",1164.0,NaN
255,Pozo de los Frailes,Spain,May,"8,667 kilometers away",3140.0,NaN
256,Tarajalejo,Spain,May,"10,083 kilometers away",1898.0,NaN
257,Palm-Mar,Spain,May,"10,319 kilometers away",8230.0,NaN
258,Las Hortichuelas,Spain,May,"8,658 kilometers away",1767.0,NaN
259,La Isleta del Moro,Spain,May,"8,662 kilometers away",2329.0,NaN
260,Tabernas,Spain,May,"8,681 kilometers away",1327.0,NaN
261,Caleta de Famara,Spain,May,"9,991 kilometers away",3733.0,NaN
262,Antas,Spain,May,"8,634 kilometers away",4387.0,NaN
263,El Roque,Spain,May,"10,050 kilometers away",696.0,NaN
264,Tabernas,Spain,May,"8,681 kilometers away",2064.0,NaN
265,Cuevas del Almanzora,Spain,May,"8,631 kilometers away",998.0,NaN
266,Tarajalejo,Spain,May,"10,083 kilometers away",1898.0,NaN
267,Montaña de Tindaya,Spain,May,"10,054 kilometers away",1139.0,NaN
268,El Pozo de los Frailes,Spain,May,"8,668 kilometers away",2227.0,NaN
269,Yaiza,Spain,May,"10,019 kilometers away",6695.0,NaN
270,Arrieta,Spain,May,"9,981 kilometers away",1597.0,NaN
271,Las Casitas,Spain,May,"10,017 kilometers away",17481.0,NaN
272,sceale bay,Australia,May,"7,821 kilometers away",4699.0,NaN
273,Caleta/Teguise,Spain,May,"9,993 kilometers away",1869.0,NaN
274,Bidiyah,Oman,May,Near Arabian Desert,1054.0,NaN
275,Haría Lanzarote,Spain,May,"9,981 kilometers away",5117.0,NaN
276,Tefia,Spain,May,"10,058 kilometers away",2326.0,NaN
277,El Pozo de los Frailes,Spain,May,"8,668 kilometers away",2994.0,NaN
278,Tarajalejo,Spain,May,"10,083 kilometers away",1616.0,NaN
279,Las Palmas,Spain,May,"10,055 kilometers away",1872.0,NaN

In [39]:
desert = desert[
    [
        "Property Location",
        "Property Proximity",
        "Country",
        "Month",
        "Price (In dollar)",
        "Rating"
    ]
]

display(desert)

,Property Location,Property Proximity,Country,Month,Price (In dollar),Rating
0,Mhamid,Near Sahara Desert,Morocco,May,479.0,4.79
1,Aqaba City,Near Arabian Desert,Jordan,May,2168.0,4.92
2,Tamesluht,"9,404 kilometers away",Morocco,May,17752.0,4.95
3,Al Bairat,Near Sahara Desert,Egypt,May,1982.0,4.88
4,Tamesluht,"9,404 kilometers away",Morocco,May,17752.0,4.87
5,Mitzpe Ramon,Near Arabian Desert,Israel,May,2502.0,4.81
6,M'Hamid El Ghizlane,Near Sahara Desert,Morocco,May,415.0,4.81
7,Tinghir,Near Sahara Desert,Morocco,May,1346.0,4.92
8,Skoura,"9,293 kilometers away",Morocco,May,928.0,4.91
9,MA,Near Sahara Desert,Morocco,May,857.0,4.86
10,Mitzpe Ramon,Near Arabian Desert,Israel,May,2945.0,4.81
11,Wadi Rum,Near Arabian Desert,Jordan,May,898.0,4.84
12,Jaisalmer,Near Thar Desert,India,May,449.0,4.79
13,Siwa,Near Sahara Desert,Egypt,May,991.0,4.90
14,Merzouga,Near Sahara Desert,Morocco,May,2937.0,4.83
15,Essaouira,"9,536 kilometers away",Morocco,May,5386.0,4.90
16,Jaisalmer,Near Thar Desert,India,May,284.0,4.86
17,Tzofar,Near Arabian Desert,Israel,May,1821.0,4.77
18,Ait Bihi,"9,586 kilometers away",Morocco,May,1096.0,4.94
19,Jaisalmer,Near Thar Desert,India,May,677.0,4.79
20,Al Bairat,Near Sahara Desert,Egypt,May,1670.0,5.00
21,Órzola,"9,976 kilometers away",Spain,May,2396.0,4.90
22,Hassilabied,Near Sahara Desert,Morocco,May,970.0,4.94
23,Aglou,"9,637 kilometers away",Morocco,May,2792.0,5.00
24,Takojt,Near Sahara Desert,Morocco,May,371.0,5.00
25,Ouarzazate,"9,327 kilometers away",Morocco,May,530.0,4.67
26,Wadi Rum Village,Near Arabian Desert,Jordan,May,823.0,5.00
27,Marrakech,"9,391 kilometers away",Morocco,May,3561.0,4.94
28,Wadi Rum Village,Near Arabian Desert,Jordan,May,898.0,4.86
29,M'Hamid El Ghizlane,Near Sahara Desert,Morocco,May,340.0,5.00
30,Tamesluht,"9,406 kilometers away",Morocco,May,12800.0,4.77
31,Mhamid,Near Sahara Desert,Morocco,May,179.0,4.89
32,Arad,Near Arabian Desert,Israel,May,3737.0,4.82
33,Merzouga,Near Sahara Desert,Morocco,May,840.0,4.98
34,Mhamid,Near Sahara Desert,Morocco,May,1145.0,4.87
35,???????,"9,586 kilometers away",Morocco,May,1149.0,4.96
36,Wadi Rum Village,Near Arabian Desert,Jordan,May,294.0,4.89
37,Marrakesh,"9,414 kilometers away",Morocco,May,7515.0,4.94
38,Triopetra,"6,390 kilometers away",Greece,May,3209.0,4.82
39,Ksar Bounou (Oasis de M´hamid Alguizlane ),Near Sahara Desert,Morocco,May,285.0,4.95
40,????,Near Arabian Desert,Israel,May,2082.0,4.88
41,Arad,Near Arabian Desert,Israel,May,1734.0,5.00
42,???? ?????,Near Arabian Desert,Egypt,May,598.0,4.94
43,Midreshet Ben-Gurion,Near Arabian Desert,Israel,May,2994.0,5.00
44,M'HAMID,Near Sahara Desert,Morocco,May,305.0,4.86
45,Hassilabied,Near Sahara Desert,Morocco,May,997.0,4.76
46,Khuri,Near Thar Desert,India,May,375.0,4.82
47,???? ???? ??,Near Arabian Desert,Jordan,May,279.0,4.83
48,Mhamid,Near Sahara Desert,Morocco,May,731.0,4.92
49,Tamesluht,"9,404 kilometers away",Morocco,May,17752.0,5.00
50,Tamesluht,"9,406 kilometers away",Morocco,May,10473.0,4.85
51,Kalya,Near Syrian Desert,Israel,May,7228.0,5.00
52,Birkat al Maraqi,Near Sahara Desert,Egypt,May,249.0,5.00
53,Aqaba,Near Arabian Desert,Jordan,May,2061.0,5.00
54,Luxor,Near Sahara Desert,Egypt,May,347.0,5.00
55,Jaisalmer,Near Thar Desert,India,May,562.0,4.88
56,Oued El Khil,Near Sahara Desert,Tunisia,May,749.0,4.94
57,Mhamid,Near Sahara Desert,Morocco,May,207.0,5.00
58,commune rurale Fritissa,"8,935 kilometers away",Morocco,May,587.0,5.00
59,Tiznit,"9,635 kilometers away",Morocco,May,7687.0,5.00
60,Wadi Rum Village,Near Arabian Desert,Jordan,May,368.0,5.00
61,Hassilabied,Near Sahara Desert,Morocco,May,822.0,5.00
62,Fint,"9,328 kilometers away",Morocco,May,831.0,4.67
63,Arad,Near Arabian Desert,Israel,May,8080.0,5.00
64,Tamesluht,"9,406 kilometers away",Morocco,May,10473.0,5.00
65,Marrakech Alentours,"9,379 kilometers away",Morocco,May,35293.0,5.00
66,Merzouga,Near Sahara Desert,Morocco,May,877.0,5.00
67,Zagora,Near Sahara Desert,Morocco,May,256.0,5.00
68,Hassilabied,Near Sahara Desert,Morocco,May,263.0,4.67
69,Es Sabria,Near Sahara Desert,Tunisia,May,932.0,4.62
70,MA,Near Sahara Desert,Morocco,May,542.0,4.78
71,Al Ula,Near Arabian Desert,Saudi Arabia,May,16519.0,4.87
72,Nazlet El-Semman,Near Sahara Desert,Egypt,May,1370.0,4.63
73,Douz,Near Sahara Desert,Tunisia,May,1896.0,4.78
74,Arad,Near Arabian Desert,Israel,May,4209.0,4.78
75,Jaisalmer,Near Thar Desert,India,May,449.0,4.74
76,Zagora,Near Sahara Desert,Morocco,May,190.0,4.76
77,Hassilabied,Near Sahara Desert,Morocco,May,455.0,4.73
78,Zagora,Near Sahara Desert,Morocco,May,798.0,4.52
79,Merzouga,Near Sahara Desert,Morocco,May,780.0,4.79
80,Tinghir,Near Sahara Desert,Morocco,May,1346.0,4.67
81,Siwa Oasis,Near Sahara Desert,Egypt,May,867.0,4.70
82,Zagora,Near Sahara Desert,Morocco,May,466.0,4.67
83,Zagora,Near Sahara Desert,Morocco,May,425.0,4.43
84,Jaisalmer,Near Thar Desert,India,May,1198.0,4.52
85,Marrakech,"9,390 kilometers away",Morocco,May,648.0,4.76
86,Qesm Siwah,Near Sahara Desert,Egypt,May,790.0,4.76
87,Aoufous,Near Sahara Desert,Morocco,May,663.0,4.75
88,Wadi Rum Village,Near Arabian Desert,Jordan,May,244.0,4.50
89,Marrakech,"9,391 kilometers away",Morocco,May,3061.0,4.83
90,Sam,Near Thar Desert,India,May,628.0,4.23
91,Hassilabied,Near Sahara Desert,Morocco,May,1515.0,4.76
92,Kfar Adumim,Near Syrian Desert,Israel,May,4248.0,4.59
93,Essaouira,"9,536 kilometers away",Morocco,May,8977.0,4.89
94,Stavros,"6,425 kilometers away",Greece,May,9601.0,4.57
95,Merzouga,Near Sahara Desert,Morocco,May,812.0,4.84
96,Dahab,Near Arabian Desert,Egypt,May,1512.0,4.76
97,Ouarzazate,"9,349 kilometers away",Morocco,May,897.0,4.68
98,Tamesluht,"9,406 kilometers away",Morocco,May,10473.0,4.38
99,Merzouga,Near Sahara Desert,Morocco,May,2061.0,4.51
100,Boumalne Dades,Near Sahara Desert,Morocco,May,2359.0,4.50
101,Hassilabied,Near Sahara Desert,Morocco,May,1184.0,4.71
102,Bawity,Near Sahara Desert,Egypt,May,1239.0,4.75
103,Wadi rum,Near Arabian Desert,Jordan,May,217.0,4.70
104,Nador,"8,770 kilometers away",Morocco,May,1225.0,4.62
105,Hassilabied,Near Sahara Desert,Morocco,May,426.0,4.67
106,Ezuz,Near Arabian Desert,Israel,May,5545.0,4.00
107,Mhamid,Near Sahara Desert,Morocco,May,744.0,4.56
108,Mhamid,Near Sahara Desert,Morocco,May,565.0,4.67
109,Wadi Rum Village,Near Arabian Desert,Jordan,May,232.0,4.68
110,Merzouga,Near Sahara Desert,Morocco,May,299.0,4.82
111,Zagora,Near Sahara Desert,Morocco,May,220.0,4.60
112,M'Hamid El Ghizlane,Near Sahara Desert,Morocco,May,764.0,4.30
113,Mhamid,Near Sahara Desert,Morocco,May,1163.0,4.50
114,Khamlia,Near Sahara Desert,Morocco,May,1442.0,3.67
115,Ouarzazate,"9,341 kilometers away",Morocco,May,2326.0,4.68
116,Jaisalmer,Near Thar Desert,India,May,1310.0,4.71
117,Wadi Rum Village,Near Arabian Desert,Jordan,May,350.0,4.71
118,Zagora,Near Sahara Desert,Morocco,May,930.0,4.25
119,Quairah District,Near Arabian Desert,Jordan,May,155.0,4.84
120,Jaisalmer,Near Thar Desert,India,May,2039.0,4.20
121,Wadi Rum Village,Near Arabian Desert,Jordan,May,294.0,4.50
122,Merzouga,Near Sahara Desert,Morocco,May,2966.0,4.11
123,Mhamid,Near Sahara Desert,Morocco,May,295.0,4.53
124,Jaisalmer,Near Thar Desert,India,May,233.0,3.67
125,Ouled Arbia,"9,295 kilometers away",Morocco,May,2758.0,4.15
126,Merzouga,Near Sahara Desert,Morocco,May,1848.0,4.00
127,Bikaner,Near Thar Desert,India,May,1514.0,4.67
128,Tighza/Telouet,"9,328 kilometers away",Morocco,May,523.0,4.47
129,Merzouga,Near Sahara Desert,Morocco,May,989.0,4.74
130,Aqaba City,Near Arabian Desert,Jordan,May,341.0,4.64
131,Marrakesh,"9,391 kilometers away",Morocco,May,2612.0,4.67
132,Taghia,"9,215 kilometers away",Morocco,May,580.0,4.63
133,Mhamid,Near Sahara Desert,Morocco,May,665.0,4.58
134,Merzouga,Near Sahara Desert,"Morocco, Morocco",May,1330.0,4.76
135,Mhamid,Near Sahara Desert,Morocco,May,155.0,4.87
136,Hassilabied,Near Sahara Desert,Morocco,May,2534.0,4.52
137,Kanoi,Near Thar Desert,India,May,2353.0,4.82
138,Merzouga,Near Sahara Desert,Morocco,May,537.0,4.75
139,erg chebbi,Near Sahara Desert,Morocco,May,1115.0,4.83
140,Zagora,Near Sahara Desert,Morocco,May,1163.0,4.82
141,Merzouga,Near Sahara Desert,Morocco,May,2991.0,4.71
142,Wadi Rum Village,Near Arabian Desert,Jordan,May,350.0,4.60
143,Quairah District,Near Arabian Desert,Jordan,May,374.0,4.77
144,Bawity,Near Sahara Desert,Egypt,May,1549.0,4.67
145,Mhamid,Near Sahara Desert,Morocco,May,339.0,4.17
146,Ghewara,Near Thar Desert,India,May,1049.0,4.53
147,Merzouga,Near Sahara Desert,Morocco,May,399.0,4.58
148,Province de Ouarzazate,"9,336 kilometers away",Morocco,May,509.0,4.59
149,Quairah District,Near Arabian Desert,Jordan,May,1260.0,4.66
150,Agdz,Near Sahara Desert,Morocco,May,819.0,4.67
151,Jaisalmer,Near Thar Desert,India,May,1523.0,4.75
152,Qesm Siwah,Near Sahara Desert,Egypt,May,2369.0,4.74
153,Merzouga,Near Sahara Desert,Morocco,May,2425.0,4.86
154,Marrakesh,Near Sahara Desert,Morocco,May,2326.0,4.76
155,Zagora,Near Sahara Desert,Morocco,May,3153.0,4.67
156,Jaisalmer,Near Thar Desert,India,May,2039.0,4.46
157,Zagora,Near Sahara Desert,Morocco,May,2542.0,4.69
158,Khamlia,Near Sahara Desert,Morocco,May,1442.0,4.69
159,Marrakesh,"9,391 kilometers away",Morocco,May,2922.0,3.50
160,Erg Chebbi,Near Sahara Desert,Morocco,May,9969.0,4.86
161,Wadi Rum Village,Near Arabian Desert,Jordan,May,1260.0,4.74
162,Todra River,Near Sahara Desert,Morocco,May,335.0,4.82
163,Mhamid,Near Sahara Desert,Morocco,May,1163.0,4.63
164,Mhamid,Near Sahara Desert,Morocco,May,392.0,4.58
165,Jaisalmer,Near Thar Desert,India,May,1252.0,4.60
166,Mhamid,Near Sahara Desert,Morocco,May,759.0,4.56
167,Hassilabied,Near Sahara Desert,Morocco,May,1188.0,4.38
168,Wadi Rum Village,Near Arabian Desert,Jordan,May,339.0,NaN
169,Wadi Rum Village,Near Arabian Desert,Jordan,May,836.0,NaN
170,Mhamid,Near Sahara Desert,Morocco,May,1163.0,NaN
171,Mhamid,Near Sahara Desert,Morocco,May,1330.0,NaN
172,Mhamid,Near Sahara Desert,Morocco,May,1371.0,NaN
173,Marrakesh,"9,412 kilometers away",Morocco,May,51071.0,NaN
174,Mhamid,Near Sahara Desert,Morocco,May,1196.0,NaN
175,Tagounite,Near Sahara Desert,Morocco,May,997.0,NaN
176,merzouga,Near Sahara Desert,Morocco,May,276.0,NaN
177,Zagora,Near Sahara Desert,Morocco,May,1469.0,NaN
178,Merzouga,Near Sahara Desert,Morocco,May,7976.0,NaN
179,Wadi Rum Village,Near Arabian Desert,Jordan,May,1993.0,NaN
180,Essaouira,"9,536 kilometers away",Morocco,May,5386.0,NaN
181,Santorini,"6,291 kilometers away",Greece,May,7477.0,NaN
182,Oumnass,"9,405 kilometers away",Morocco,May,3745.0,NaN
183,Marrakesh,"9,373 kilometers away",Morocco,May,8307.0,NaN
184,Essaouira,"9,536 kilometers away",Morocco,May,5386.0,NaN
185,Marrakesh,"9,387 kilometers away",Morocco,May,19440.0,NaN
186,?????Marrakech,"9,406 kilometers away",Morocco,May,49610.0,NaN
187,Marrakech,"9,389 kilometers away",Morocco,May,5360.0,NaN
188,Tidzi,"9,548 kilometers away",Morocco,May,6320.0,NaN
189,Aqaba City,Near Arabian Desert,Jordan,May,706.0,NaN
190,Ait Bihi,"9,586 kilometers away",Morocco,May,1303.0,NaN
191,Ouarzazate,"9,329 kilometers away",Morocco,May,231.0,NaN
192,Tamesluht,"9,404 kilometers away",Morocco,May,17752.0,NaN
193,Aït Ben Haddou,"9,341 kilometers away",Morocco,May,615.0,NaN
194,Wadi Rum Village,Near Arabian Desert,Jordan,May,396.0,NaN
195,Aït Ben Haddou,"9,341 kilometers away",Morocco,May,493.0,NaN
196,Ouarzazate,"9,327 kilometers away",Morocco,May,1553.0,NaN
197,Ait Bihi,"9,586 kilometers away",Morocco,May,1063.0,NaN
198,Ovnat,Near Syrian Desert,Israel,May,3094.0,NaN
199,Ouarzazate,"9,329 kilometers away",Morocco,May,296.0,NaN
200,Essaouira,"9,536 kilometers away",Morocco,May,5386.0,NaN
201,Faiyum,Near Sahara Desert,Egypt,May,1239.0,NaN
202,Marrakech,"9,384 kilometers away",Morocco,May,9969.0,NaN
203,Mhamid,Near Sahara Desert,Morocco,May,532.0,NaN
204,Merzouga,Near Sahara Desert,Morocco,May,665.0,NaN
205,Mhamid,Near Sahara Desert,Morocco,May,375.0,NaN
206,Ezuz,Near Arabian Desert,Israel,May,2635.0,NaN
207,Es Sabria,Near Sahara Desert,Tunisia,May,954.0,NaN
208,Jaisalmer Rural,Near Thar Desert,India,May,393.0,NaN
209,Errachidia Province,Near Sahara Desert,Morocco,May,455.0,NaN
210,Ma'an Governorate,Near Syrian Desert,Jordan,May,1993.0,NaN
211,Boumalne Dades,Near Sahara Desert,Morocco,May,658.0,NaN
212,Nuweibaa,Near Arabian Desert,Egypt,May,496.0,NaN
213,Zagora,Near Sahara Desert,Morocco,May,918.0,NaN
214,Aït Benhaddou,"9,340 kilometers away",Morocco,May,1455.0,NaN
215,Petra,Near Syrian Desert,"Jordan, Jordan",May,687.0,NaN
216,Wadi Rum Village,Near Arabian Desert,Jordan,May,465.0,NaN
217,Essaouira,"9,536 kilometers away",Morocco,May,5386.0,NaN
218,Palea Agia Roumeli,"6,442 kilometers away",Greece,May,851.0,NaN
219,Mhamid,Near Sahara Desert,Morocco,May,582.0,NaN
220,Zagora,Near Sahara Desert,Morocco,May,657.0,NaN
221,Órzola,"9,976 kilometers away",Spain,May,2662.0,NaN
222,Douz,Near Sahara Desert,Tunisia,May,1526.0,NaN
223,Telouet,"9,331 kilometers away",Morocco,May,404.0,NaN
224,Tinghir,Near Sahara Desert,Morocco,May,665.0,NaN
225,Assouan,Near Sahara Desert,"Aswan, Egypt",May,929.0,NaN
226,Kathodi,Near Thar Desert,India,May,184.0,NaN
227,Ouarzazate,"9,340 kilometers away",Morocco,May,464.0,NaN
228,Abu AR Rish Qebli,Near Sahara Desert,Egypt,May,1163.0,NaN
229,Merzouga,Near Sahara Desert,Morocco,May,463.0,NaN
230,Wadi Rum Village,Near Arabian Desert,Jordan,May,178.0,NaN
231,Demnat,"9,296 kilometers away",Morocco,May,947.0,NaN
232,Quairah District,Near Arabian Desert,Jordan,May,501.0,NaN
233,Petra - Wadi Musa,Near Syrian Desert,Jordan,May,1041.0,NaN
234,Aït Ben Haddou,"9,337 kilometers away",Morocco,May,590.0,NaN
235,Wadi Rum Village,Near Arabian Desert,Jordan,May,1053.0,NaN
236,Quairah District,Near Arabian Desert,Jordan,May,155.0,NaN
237,Rissani,Near Sahara Desert,Morocco,May,396.0,NaN
238,Mhamid,Near Sahara Desert,Morocco,May,951.0,NaN
239,Wadi Rum Village,Near Arabian Desert,Jordan,May,786.0,NaN
240,Awrir,"9,584 kilometers away",Morocco,May,5951.0,NaN
241,Ras al-Khaimah,Near Arabian Desert,UAE,May,3038.0,NaN
242,Merzouga,Near Sahara Desert,Morocco,May,1202.0,NaN
243,??????????,Near Sahara Desert,Morocco,May,898.0,NaN
244,Charco del Palo,"9,983 kilometers away",Spain,May,1958.0,NaN
245,Nijar (Almería),"8,657 kilometers away",Spain,May,2663.0,NaN
246,Mogán,"10,246 kilometers away",Spain,May,2383.0,NaN
247,Alhaurín el Grande,"8,891 kilometers away",Spain,May,12816.0,NaN
248,Níjar,"8,668 kilometers away",Spain,May,1165.0,NaN
249,Las Palmas,"10,057 kilometers away",Spain,May,3605.0,NaN
250,Swakopmund,"9,682 kilometers away",Namibia,May,6894.0,NaN
251,Antigua,"10,066 kilometers away",Spain,May,3515.0,NaN
252,Tarajalejo,"10,083 kilometers away",Spain,May,1982.0,NaN
253,Loxton,"9,530 kilometers away",South Africa,May,1331.0,NaN
254,Tarajalejo,"10,083 kilometers away",Spain,May,1164.0,NaN
255,Pozo de los Frailes,"8,667 kilometers away",Spain,May,3140.0,NaN
256,Tarajalejo,"10,083 kilometers away",Spain,May,1898.0,NaN
257,Palm-Mar,"10,319 kilometers away",Spain,May,8230.0,NaN
258,Las Hortichuelas,"8,658 kilometers away",Spain,May,1767.0,NaN
259,La Isleta del Moro,"8,662 kilometers away",Spain,May,2329.0,NaN
260,Tabernas,"8,681 kilometers away",Spain,May,1327.0,NaN
261,Caleta de Famara,"9,991 kilometers away",Spain,May,3733.0,NaN
262,Antas,"8,634 kilometers away",Spain,May,4387.0,NaN
263,El Roque,"10,050 kilometers away",Spain,May,696.0,NaN
264,Tabernas,"8,681 kilometers away",Spain,May,2064.0,NaN
265,Cuevas del Almanzora,"8,631 kilometers away",Spain,May,998.0,NaN
266,Tarajalejo,"10,083 kilometers away",Spain,May,1898.0,NaN
267,Montaña de Tindaya,"10,054 kilometers away",Spain,May,1139.0,NaN
268,El Pozo de los Frailes,"8,668 kilometers away",Spain,May,2227.0,NaN
269,Yaiza,"10,019 kilometers away",Spain,May,6695.0,NaN
270,Arrieta,"9,981 kilometers away",Spain,May,1597.0,NaN
271,Las Casitas,"10,017 kilometers away",Spain,May,17481.0,NaN
272,sceale bay,"7,821 kilometers away",Australia,May,4699.0,NaN
273,Caleta/Teguise,"9,993 kilometers away",Spain,May,1869.0,NaN
274,Bidiyah,Near Arabian Desert,Oman,May,1054.0,NaN
275,Haría Lanzarote,"9,981 kilometers away",Spain,May,5117.0,NaN
276,Tefia,"10,058 kilometers away",Spain,May,2326.0,NaN
277,El Pozo de los Frailes,"8,668 kilometers away",Spain,May,2994.0,NaN
278,Tarajalejo,"10,083 kilometers away",Spain,May,1616.0,NaN
279,Las Palmas,"10,055 kilometers away",Spain,May,1872.0,NaN

In [40]:
desert.to_csv("data/clean/airnb_desert_clean.csv", index=False)

In [41]:
desert.isnull().sum()

Property Location       0
Property Proximity      0
Country                 0
Month                   0
Price (In dollar)       0
Rating                112
dtype: int64

In [42]:
desert["Rating"] = pd.to_numeric(desert["Rating"], errors="coerce").fillna(0)

In [43]:
desert.isnull().sum()

Property Location     0
Property Proximity    0
Country               0
Month                 0
Price (In dollar)     0
Rating                0
dtype: int64

In [44]:
desert[desert["Rating"] == 0]

,Property Location,Property Proximity,Country,Month,Price (In dollar),Rating
168,Wadi Rum Village,Near Arabian Desert,Jordan,May,339.0,0.0
169,Wadi Rum Village,Near Arabian Desert,Jordan,May,836.0,0.0
170,Mhamid,Near Sahara Desert,Morocco,May,1163.0,0.0
171,Mhamid,Near Sahara Desert,Morocco,May,1330.0,0.0
172,Mhamid,Near Sahara Desert,Morocco,May,1371.0,0.0
173,Marrakesh,"9,412 kilometers away",Morocco,May,51071.0,0.0
174,Mhamid,Near Sahara Desert,Morocco,May,1196.0,0.0
175,Tagounite,Near Sahara Desert,Morocco,May,997.0,0.0
176,merzouga,Near Sahara Desert,Morocco,May,276.0,0.0
177,Zagora,Near Sahara Desert,Morocco,May,1469.0,0.0
178,Merzouga,Near Sahara Desert,Morocco,May,7976.0,0.0
179,Wadi Rum Village,Near Arabian Desert,Jordan,May,1993.0,0.0
180,Essaouira,"9,536 kilometers away",Morocco,May,5386.0,0.0
181,Santorini,"6,291 kilometers away",Greece,May,7477.0,0.0
182,Oumnass,"9,405 kilometers away",Morocco,May,3745.0,0.0
183,Marrakesh,"9,373 kilometers away",Morocco,May,8307.0,0.0
184,Essaouira,"9,536 kilometers away",Morocco,May,5386.0,0.0
185,Marrakesh,"9,387 kilometers away",Morocco,May,19440.0,0.0
186,?????Marrakech,"9,406 kilometers away",Morocco,May,49610.0,0.0
187,Marrakech,"9,389 kilometers away",Morocco,May,5360.0,0.0
188,Tidzi,"9,548 kilometers away",Morocco,May,6320.0,0.0
189,Aqaba City,Near Arabian Desert,Jordan,May,706.0,0.0
190,Ait Bihi,"9,586 kilometers away",Morocco,May,1303.0,0.0
191,Ouarzazate,"9,329 kilometers away",Morocco,May,231.0,0.0
192,Tamesluht,"9,404 kilometers away",Morocco,May,17752.0,0.0
193,Aït Ben Haddou,"9,341 kilometers away",Morocco,May,615.0,0.0
194,Wadi Rum Village,Near Arabian Desert,Jordan,May,396.0,0.0
195,Aït Ben Haddou,"9,341 kilometers away",Morocco,May,493.0,0.0
196,Ouarzazate,"9,327 kilometers away",Morocco,May,1553.0,0.0
197,Ait Bihi,"9,586 kilometers away",Morocco,May,1063.0,0.0
198,Ovnat,Near Syrian Desert,Israel,May,3094.0,0.0
199,Ouarzazate,"9,329 kilometers away",Morocco,May,296.0,0.0
200,Essaouira,"9,536 kilometers away",Morocco,May,5386.0,0.0
201,Faiyum,Near Sahara Desert,Egypt,May,1239.0,0.0
202,Marrakech,"9,384 kilometers away",Morocco,May,9969.0,0.0
203,Mhamid,Near Sahara Desert,Morocco,May,532.0,0.0
204,Merzouga,Near Sahara Desert,Morocco,May,665.0,0.0
205,Mhamid,Near Sahara Desert,Morocco,May,375.0,0.0
206,Ezuz,Near Arabian Desert,Israel,May,2635.0,0.0
207,Es Sabria,Near Sahara Desert,Tunisia,May,954.0,0.0
208,Jaisalmer Rural,Near Thar Desert,India,May,393.0,0.0
209,Errachidia Province,Near Sahara Desert,Morocco,May,455.0,0.0
210,Ma'an Governorate,Near Syrian Desert,Jordan,May,1993.0,0.0
211,Boumalne Dades,Near Sahara Desert,Morocco,May,658.0,0.0
212,Nuweibaa,Near Arabian Desert,Egypt,May,496.0,0.0
213,Zagora,Near Sahara Desert,Morocco,May,918.0,0.0
214,Aït Benhaddou,"9,340 kilometers away",Morocco,May,1455.0,0.0
215,Petra,Near Syrian Desert,"Jordan, Jordan",May,687.0,0.0
216,Wadi Rum Village,Near Arabian Desert,Jordan,May,465.0,0.0
217,Essaouira,"9,536 kilometers away",Morocco,May,5386.0,0.0
218,Palea Agia Roumeli,"6,442 kilometers away",Greece,May,851.0,0.0
219,Mhamid,Near Sahara Desert,Morocco,May,582.0,0.0
220,Zagora,Near Sahara Desert,Morocco,May,657.0,0.0
221,Órzola,"9,976 kilometers away",Spain,May,2662.0,0.0
222,Douz,Near Sahara Desert,Tunisia,May,1526.0,0.0
223,Telouet,"9,331 kilometers away",Morocco,May,404.0,0.0
224,Tinghir,Near Sahara Desert,Morocco,May,665.0,0.0
225,Assouan,Near Sahara Desert,"Aswan, Egypt",May,929.0,0.0
226,Kathodi,Near Thar Desert,India,May,184.0,0.0
227,Ouarzazate,"9,340 kilometers away",Morocco,May,464.0,0.0
228,Abu AR Rish Qebli,Near Sahara Desert,Egypt,May,1163.0,0.0
229,Merzouga,Near Sahara Desert,Morocco,May,463.0,0.0
230,Wadi Rum Village,Near Arabian Desert,Jordan,May,178.0,0.0
231,Demnat,"9,296 kilometers away",Morocco,May,947.0,0.0
232,Quairah District,Near Arabian Desert,Jordan,May,501.0,0.0
233,Petra - Wadi Musa,Near Syrian Desert,Jordan,May,1041.0,0.0
234,Aït Ben Haddou,"9,337 kilometers away",Morocco,May,590.0,0.0
235,Wadi Rum Village,Near Arabian Desert,Jordan,May,1053.0,0.0
236,Quairah District,Near Arabian Desert,Jordan,May,155.0,0.0
237,Rissani,Near Sahara Desert,Morocco,May,396.0,0.0
238,Mhamid,Near Sahara Desert,Morocco,May,951.0,0.0
239,Wadi Rum Village,Near Arabian Desert,Jordan,May,786.0,0.0
240,Awrir,"9,584 kilometers away",Morocco,May,5951.0,0.0
241,Ras al-Khaimah,Near Arabian Desert,UAE,May,3038.0,0.0
242,Merzouga,Near Sahara Desert,Morocco,May,1202.0,0.0
243,??????????,Near Sahara Desert,Morocco,May,898.0,0.0
244,Charco del Palo,"9,983 kilometers away",Spain,May,1958.0,0.0
245,Nijar (Almería),"8,657 kilometers away",Spain,May,2663.0,0.0
246,Mogán,"10,246 kilometers away",Spain,May,2383.0,0.0
247,Alhaurín el Grande,"8,891 kilometers away",Spain,May,12816.0,0.0
248,Níjar,"8,668 kilometers away",Spain,May,1165.0,0.0
249,Las Palmas,"10,057 kilometers away",Spain,May,3605.0,0.0
250,Swakopmund,"9,682 kilometers away",Namibia,May,6894.0,0.0
251,Antigua,"10,066 kilometers away",Spain,May,3515.0,0.0
252,Tarajalejo,"10,083 kilometers away",Spain,May,1982.0,0.0
253,Loxton,"9,530 kilometers away",South Africa,May,1331.0,0.0
254,Tarajalejo,"10,083 kilometers away",Spain,May,1164.0,0.0
255,Pozo de los Frailes,"8,667 kilometers away",Spain,May,3140.0,0.0
256,Tarajalejo,"10,083 kilometers away",Spain,May,1898.0,0.0
257,Palm-Mar,"10,319 kilometers away",Spain,May,8230.0,0.0
258,Las Hortichuelas,"8,658 kilometers away",Spain,May,1767.0,0.0
259,La Isleta del Moro,"8,662 kilometers away",Spain,May,2329.0,0.0
260,Tabernas,"8,681 kilometers away",Spain,May,1327.0,0.0
261,Caleta de Famara,"9,991 kilometers away",Spain,May,3733.0,0.0
262,Antas,"8,634 kilometers away",Spain,May,4387.0,0.0
263,El Roque,"10,050 kilometers away",Spain,May,696.0,0.0
264,Tabernas,"8,681 kilometers away",Spain,May,2064.0,0.0
265,Cuevas del Almanzora,"8,631 kilometers away",Spain,May,998.0,0.0
266,Tarajalejo,"10,083 kilometers away",Spain,May,1898.0,0.0
267,Montaña de Tindaya,"10,054 kilometers away",Spain,May,1139.0,0.0
268,El Pozo de los Frailes,"8,668 kilometers away",Spain,May,2227.0,0.0
269,Yaiza,"10,019 kilometers away",Spain,May,6695.0,0.0
270,Arrieta,"9,981 kilometers away",Spain,May,1597.0,0.0
271,Las Casitas,"10,017 kilometers away",Spain,May,17481.0,0.0
272,sceale bay,"7,821 kilometers away",Australia,May,4699.0,0.0
273,Caleta/Teguise,"9,993 kilometers away",Spain,May,1869.0,0.0
274,Bidiyah,Near Arabian Desert,Oman,May,1054.0,0.0
275,Haría Lanzarote,"9,981 kilometers away",Spain,May,5117.0,0.0
276,Tefia,"10,058 kilometers away",Spain,May,2326.0,0.0
277,El Pozo de los Frailes,"8,668 kilometers away",Spain,May,2994.0,0.0
278,Tarajalejo,"10,083 kilometers away",Spain,May,1616.0,0.0
279,Las Palmas,"10,055 kilometers away",Spain,May,1872.0,0.0

In [45]:
print(sorted(desert["Property Location"].unique()))

['????', '???? ???? ??', '???? ?????', '???????', '??????????', '?????Marrakech', 'Abu AR Rish Qebli', 'Agdz', 'Aglou', 'Ait Bihi', 'Al Bairat', 'Al Ula', 'Alhaurín el Grande', 'Antas', 'Antigua', 'Aoufous', 'Aqaba', 'Aqaba City', 'Arad', 'Arrieta', 'Assouan', 'Awrir', 'Aït Ben Haddou', 'Aït Benhaddou', 'Bawity', 'Bidiyah', 'Bikaner', 'Birkat al Maraqi', 'Boumalne Dades', 'Caleta de Famara', 'Caleta/Teguise', 'Charco del Palo', 'Cuevas del Almanzora', 'Dahab', 'Demnat', 'Douz', 'El Pozo de los Frailes', 'El Roque', 'Erg Chebbi', 'Errachidia Province', 'Es Sabria', 'Essaouira', 'Ezuz', 'Faiyum', 'Fint', 'Ghewara', 'Haría Lanzarote', 'Hassilabied', 'Jaisalmer', 'Jaisalmer Rural', 'Kalya', 'Kanoi', 'Kathodi', 'Kfar Adumim', 'Khamlia', 'Khuri', 'Ksar Bounou (Oasis de M´hamid Alguizlane )', 'La Isleta del Moro', 'Las Casitas', 'Las Hortichuelas', 'Las Palmas', 'Loxton', 'Luxor', "M'HAMID", "M'Hamid El Ghizlane", 'MA', "Ma'an Governorate", 'Marrakech', 'Marrakech Alentours', 'Marrakesh', 'Merzouga', 'Mhamid', 'Midreshet Ben-Gurion', 'Mitzpe Ramon', 'Mogán', 'Montaña de Tindaya', 'Nador', 'Nazlet El-Semman', 'Nijar (Almería)', 'Nuweibaa', 'Níjar', 'Ouarzazate', 'Oued El Khil', 'Ouled Arbia', 'Oumnass', 'Ovnat', 'Palea Agia Roumeli', 'Palm-Mar', 'Petra', 'Petra - Wadi Musa', 'Pozo de los Frailes', 'Province de Ouarzazate', 'Qesm Siwah', 'Quairah District', 'Ras al-Khaimah', 'Rissani', 'Sam', 'Santorini', 'Siwa', 'Siwa Oasis', 'Skoura', 'Stavros', 'Swakopmund', 'Tabernas', 'Taghia', 'Tagounite', 'Takojt', 'Tamesluht', 'Tarajalejo', 'Tefia', 'Telouet', 'Tidzi', 'Tighza/Telouet', 'Tinghir', 'Tiznit', 'Todra River', 'Triopetra', 'Tzofar', 'Wadi Rum', 'Wadi Rum Village', 'Wadi rum', 'Yaiza', 'Zagora', 'commune rurale Fritissa', 'erg chebbi', 'merzouga', 'sceale bay', 'Órzola']

In [46]:
special_chars = desert[
    desert["Property Location"].str.contains(
        r"[^A-Za-z0-9\s,\.\-']",
        regex=True,
        na=False
    )
]

display(special_chars)

,Property Location,Property Proximity,Country,Month,Price (In dollar),Rating
21,Órzola,"9,976 kilometers away",Spain,May,2396.0,4.90
35,???????,"9,586 kilometers away",Morocco,May,1149.0,4.96
39,Ksar Bounou (Oasis de M´hamid Alguizlane ),Near Sahara Desert,Morocco,May,285.0,4.95
40,????,Near Arabian Desert,Israel,May,2082.0,4.88
42,???? ?????,Near Arabian Desert,Egypt,May,598.0,4.94
47,???? ???? ??,Near Arabian Desert,Jordan,May,279.0,4.83
128,Tighza/Telouet,"9,328 kilometers away",Morocco,May,523.0,4.47
186,?????Marrakech,"9,406 kilometers away",Morocco,May,49610.0,0.00
193,Aït Ben Haddou,"9,341 kilometers away",Morocco,May,615.0,0.00
195,Aït Ben Haddou,"9,341 kilometers away",Morocco,May,493.0,0.00
214,Aït Benhaddou,"9,340 kilometers away",Morocco,May,1455.0,0.00
221,Órzola,"9,976 kilometers away",Spain,May,2662.0,0.00
234,Aït Ben Haddou,"9,337 kilometers away",Morocco,May,590.0,0.00
243,??????????,Near Sahara Desert,Morocco,May,898.0,0.00
245,Nijar (Almería),"8,657 kilometers away",Spain,May,2663.0,0.00
246,Mogán,"10,246 kilometers away",Spain,May,2383.0,0.00
247,Alhaurín el Grande,"8,891 kilometers away",Spain,May,12816.0,0.00
248,Níjar,"8,668 kilometers away",Spain,May,1165.0,0.00
267,Montaña de Tindaya,"10,054 kilometers away",Spain,May,1139.0,0.00
273,Caleta/Teguise,"9,993 kilometers away",Spain,May,1869.0,0.00
275,Haría Lanzarote,"9,981 kilometers away",Spain,May,5117.0,0.00

In [47]:
desert["Location Length"] = desert["Property Location"].str.len()

display(desert[["Property Location", "Location Length"]])

                              Property Location  Location Length
0                                        Mhamid                6
1                                    Aqaba City               10
2                                     Tamesluht                9
3                                     Al Bairat                9
4                                     Tamesluht                9
5                                  Mitzpe Ramon               12
6                           M'Hamid El Ghizlane               19
7                                       Tinghir                7
8                                        Skoura                6
9                                            MA                2
10                                 Mitzpe Ramon               12
11                                     Wadi Rum                8
12                                    Jaisalmer                9
13                                         Siwa                4
14                                     Merzouga                8
15                                    Essaouira                9
16                                    Jaisalmer                9
17                                       Tzofar                6
18                                     Ait Bihi                8
19                                    Jaisalmer                9
20                                    Al Bairat                9
21                                       Órzola                6
22                                  Hassilabied               11
23                                        Aglou                5
24                                       Takojt                6
25                                   Ouarzazate               10
26                             Wadi Rum Village               16
27                                    Marrakech                9
28                             Wadi Rum Village               16
29                          M'Hamid El Ghizlane               19
30                                    Tamesluht                9
31                                       Mhamid                6
32                                         Arad                4
33                                     Merzouga                8
34                                       Mhamid                6
35                                      ???????                7
36                             Wadi Rum Village               16
37                                    Marrakesh                9
38                                    Triopetra                9
39   Ksar Bounou (Oasis de M´hamid Alguizlane )               42
40                                         ????                4
41                                         Arad                4
42                                   ???? ?????               10
43                         Midreshet Ben-Gurion               20
44                                      M'HAMID                7
45                                  Hassilabied               11
46                                        Khuri                5
47                                 ???? ???? ??               12
48                                       Mhamid                6
49                                    Tamesluht                9
50                                    Tamesluht                9
51                                        Kalya                5
52                             Birkat al Maraqi               16
53                                        Aqaba                5
54                                        Luxor                5
55                                    Jaisalmer                9
56                                 Oued El Khil               12
57                                       Mhamid                6
58                      commune rurale Fritissa               23
59                                       Tiznit                6
60                             Wadi Rum Village               16
61                                  Hassilabied               11
62                                         Fint                4
63                                         Arad                4
64                                    Tamesluht                9
65                          Marrakech Alentours               19
66                                     Merzouga                8
67                                       Zagora                6
68                                  Hassilabied               11
69                                    Es Sabria                9
70                                           MA                2
71                                       Al Ula                6
72                             Nazlet El-Semman               16
73                                         Douz                4
74                                         Arad                4
75                                    Jaisalmer                9
76                                       Zagora                6
77                                  Hassilabied               11
78                                       Zagora                6
79                                     Merzouga                8
80                                      Tinghir                7
81                                   Siwa Oasis               10
82                                       Zagora                6
83                                       Zagora                6
84                                    Jaisalmer                9
85                                    Marrakech                9
86                                   Qesm Siwah               10
87                                      Aoufous                7
88                             Wadi Rum Village               16
89                                    Marrakech                9
90                                          Sam                3
91                                  Hassilabied               11
92                                  Kfar Adumim               11
93                                    Essaouira                9
94                                      Stavros                7
95                                     Merzouga                8
96                                        Dahab                5
97                                   Ouarzazate               10
98                                    Tamesluht                9
99                                     Merzouga                8
100                              Boumalne Dades               14
101                                 Hassilabied               11
102                                      Bawity                6
103                                    Wadi rum                8
104                                       Nador                5
105                                 Hassilabied               11
106                                        Ezuz                4
107                                      Mhamid                6
108                                      Mhamid                6
109                            Wadi Rum Village               16
110                                    Merzouga                8
111                                      Zagora                6
112                         M'Hamid El Ghizlane               19
113                                      Mhamid                6
114                                     Khamlia                7
115                                  Ouarzazate               10
116                                   Jaisalmer                9
117                            Wadi Rum Village               16
118                                      Zagora                6
119                            Quairah District               16
120                                   Jaisalmer                9
121                            Wadi Rum Village               16
122                                    Merzouga                8
123                                      Mhamid                6
124                                   Jaisalmer                9
125                                 Ouled Arbia               11
126                                    Merzouga                8
127                                     Bikaner                7
128                              Tighza/Telouet               14
129                                    Merzouga                8
130                                  Aqaba City               10
131                                   Marrakesh                9
132                                      Taghia                6
133                                      Mhamid                6
134                                    Merzouga                8
135                                      Mhamid                6
136                                 Hassilabied               11
137                                       Kanoi                5
138                                    Merzouga                8
139                                  erg chebbi               10
140                                      Zagora                6
141                                    Merzouga                8
142                            Wadi Rum Village               16
143                            Quairah District               16
144                                      Bawity                6
145                                      Mhamid                6
146                                     Ghewara                7
147                                    Merzouga                8
148                      Province de Ouarzazate               22
149                            Quairah District               16
150                                        Agdz                4
151                                   Jaisalmer                9
152                                  Qesm Siwah               10
153                                    Merzouga                8
154                                   Marrakesh                9
155                                      Zagora                6
156                                   Jaisalmer                9
157                                      Zagora                6
158                                     Khamlia                7
159                                   Marrakesh                9
160                                  Erg Chebbi               10
161                            Wadi Rum Village               16
162                                 Todra River               11
163                                      Mhamid                6
164                                      Mhamid                6
165                                   Jaisalmer                9
166                                      Mhamid                6
167                                 Hassilabied               11
168                            Wadi Rum Village               16
169                            Wadi Rum Village               16
170                                      Mhamid                6
171                                      Mhamid                6
172                                      Mhamid                6
173                                   Marrakesh                9
174                                      Mhamid                6
175                                   Tagounite                9
176                                    merzouga                8
177                                      Zagora                6
178                                    Merzouga                8
179                            Wadi Rum Village               16
180                                   Essaouira                9
181                                   Santorini                9
182                                     Oumnass                7
183                                   Marrakesh                9
184                                   Essaouira                9
185                                   Marrakesh                9
186                              ?????Marrakech               14
187                                   Marrakech                9
188                                       Tidzi                5
189                                  Aqaba City               10
190                                    Ait Bihi                8
191                                  Ouarzazate               10
192                                   Tamesluht                9
193                              Aït Ben Haddou               14
194                            Wadi Rum Village               16
195                              Aït Ben Haddou               14
196                                  Ouarzazate               10
197                                    Ait Bihi                8
198                                       Ovnat                5
199                                  Ouarzazate               10
200                                   Essaouira                9
201                                      Faiyum                6
202                                   Marrakech                9
203                                      Mhamid                6
204                                    Merzouga                8
205                                      Mhamid                6
206                                        Ezuz                4
207                                   Es Sabria                9
208                             Jaisalmer Rural               15
209                         Errachidia Province               19
210                           Ma'an Governorate               17
211                              Boumalne Dades               14
212                                    Nuweibaa                8
213                                      Zagora                6
214                               Aït Benhaddou               13
215                                       Petra                5
216                            Wadi Rum Village               16
217                                   Essaouira                9
218                          Palea Agia Roumeli               18
219                                      Mhamid                6
220                                      Zagora                6
221                                      Órzola                6
222                                        Douz                4
223                                     Telouet                7
224                                     Tinghir                7
225                                     Assouan                7
226                                     Kathodi                7
227                                  Ouarzazate               10
228                           Abu AR Rish Qebli               17
229                                    Merzouga                8
230                            Wadi Rum Village               16
231                                      Demnat                6
232                            Quairah District               16
233                           Petra - Wadi Musa               17
234                              Aït Ben Haddou               14
235                            Wadi Rum Village               16
236                            Quairah District               16
237                                     Rissani                7
238                                      Mhamid                6
239                            Wadi Rum Village               16
240                                       Awrir                5
241                              Ras al-Khaimah               14
242                                    Merzouga                8
243                                  ??????????               10
244                             Charco del Palo               15
245                             Nijar (Almería)               15
246                                       Mogán                5
247                          Alhaurín el Grande               18
248                                       Níjar                5
249                                  Las Palmas               10
250                                  Swakopmund               10
251                                     Antigua                7
252                                  Tarajalejo               10
253                                      Loxton                6
254                                  Tarajalejo               10
255                         Pozo de los Frailes               19
256                                  Tarajalejo               10
257                                    Palm-Mar                8
258                            Las Hortichuelas               16
259                          La Isleta del Moro               18
260                                    Tabernas                8
261                            Caleta de Famara               16
262                                       Antas                5
263                                    El Roque                8
264                                    Tabernas                8
265                        Cuevas del Almanzora               20
266                                  Tarajalejo               10
267                          Montaña de Tindaya               18
268                      El Pozo de los Frailes               22
269                                       Yaiza                5
270                                     Arrieta                7
271                                 Las Casitas               11
272                                  sceale bay               10
273                              Caleta/Teguise               14
274                                     Bidiyah                7
275                             Haría Lanzarote               15
276                                       Tefia                5
277                      El Pozo de los Frailes               22
278                                  Tarajalejo               10
279                                  Las Palmas               10

In [48]:
desert[
    desert["Property Location"] != desert["Property Location"].str.strip()
]

Empty DataFrame
Columns: [Property Location, Property Proximity, Country, Month, Price (In dollar), Rating, Location Length]
Index: []

In [51]:
starts_with_special = desert["Property Location"].str.match(
    r"^[^A-Za-z0-9]",
    na=False
)

print("Number of properties starting with a special character:", starts_with_special.sum())

Number of properties starting with a special character: 8

In [53]:
# Remove rows where Property Location starts with a special character
# or is equal to "No Name"

desert = desert[
    ~(
        desert["Property Location"].str.match(r"^[^A-Za-z0-9]", na=False)
        | (desert["Property Location"] == "No Name")
    )
]

# Display the cleaned dataset
display(desert)

,Property Location,Property Proximity,Country,Month,Price (In dollar),Rating,Location Length
0,Mhamid,Near Sahara Desert,Morocco,May,479.0,4.79,6
1,Aqaba City,Near Arabian Desert,Jordan,May,2168.0,4.92,10
2,Tamesluht,"9,404 kilometers away",Morocco,May,17752.0,4.95,9
3,Al Bairat,Near Sahara Desert,Egypt,May,1982.0,4.88,9
4,Tamesluht,"9,404 kilometers away",Morocco,May,17752.0,4.87,9
5,Mitzpe Ramon,Near Arabian Desert,Israel,May,2502.0,4.81,12
6,M'Hamid El Ghizlane,Near Sahara Desert,Morocco,May,415.0,4.81,19
7,Tinghir,Near Sahara Desert,Morocco,May,1346.0,4.92,7
8,Skoura,"9,293 kilometers away",Morocco,May,928.0,4.91,6
9,MA,Near Sahara Desert,Morocco,May,857.0,4.86,2
10,Mitzpe Ramon,Near Arabian Desert,Israel,May,2945.0,4.81,12
11,Wadi Rum,Near Arabian Desert,Jordan,May,898.0,4.84,8
12,Jaisalmer,Near Thar Desert,India,May,449.0,4.79,9
13,Siwa,Near Sahara Desert,Egypt,May,991.0,4.90,4
14,Merzouga,Near Sahara Desert,Morocco,May,2937.0,4.83,8
15,Essaouira,"9,536 kilometers away",Morocco,May,5386.0,4.90,9
16,Jaisalmer,Near Thar Desert,India,May,284.0,4.86,9
17,Tzofar,Near Arabian Desert,Israel,May,1821.0,4.77,6
18,Ait Bihi,"9,586 kilometers away",Morocco,May,1096.0,4.94,8
19,Jaisalmer,Near Thar Desert,India,May,677.0,4.79,9
20,Al Bairat,Near Sahara Desert,Egypt,May,1670.0,5.00,9
22,Hassilabied,Near Sahara Desert,Morocco,May,970.0,4.94,11
23,Aglou,"9,637 kilometers away",Morocco,May,2792.0,5.00,5
24,Takojt,Near Sahara Desert,Morocco,May,371.0,5.00,6
25,Ouarzazate,"9,327 kilometers away",Morocco,May,530.0,4.67,10
26,Wadi Rum Village,Near Arabian Desert,Jordan,May,823.0,5.00,16
27,Marrakech,"9,391 kilometers away",Morocco,May,3561.0,4.94,9
28,Wadi Rum Village,Near Arabian Desert,Jordan,May,898.0,4.86,16
29,M'Hamid El Ghizlane,Near Sahara Desert,Morocco,May,340.0,5.00,19
30,Tamesluht,"9,406 kilometers away",Morocco,May,12800.0,4.77,9
31,Mhamid,Near Sahara Desert,Morocco,May,179.0,4.89,6
32,Arad,Near Arabian Desert,Israel,May,3737.0,4.82,4
33,Merzouga,Near Sahara Desert,Morocco,May,840.0,4.98,8
34,Mhamid,Near Sahara Desert,Morocco,May,1145.0,4.87,6
36,Wadi Rum Village,Near Arabian Desert,Jordan,May,294.0,4.89,16
37,Marrakesh,"9,414 kilometers away",Morocco,May,7515.0,4.94,9
38,Triopetra,"6,390 kilometers away",Greece,May,3209.0,4.82,9
39,Ksar Bounou (Oasis de M´hamid Alguizlane ),Near Sahara Desert,Morocco,May,285.0,4.95,42
41,Arad,Near Arabian Desert,Israel,May,1734.0,5.00,4
43,Midreshet Ben-Gurion,Near Arabian Desert,Israel,May,2994.0,5.00,20
44,M'HAMID,Near Sahara Desert,Morocco,May,305.0,4.86,7
45,Hassilabied,Near Sahara Desert,Morocco,May,997.0,4.76,11
46,Khuri,Near Thar Desert,India,May,375.0,4.82,5
48,Mhamid,Near Sahara Desert,Morocco,May,731.0,4.92,6
49,Tamesluht,"9,404 kilometers away",Morocco,May,17752.0,5.00,9
50,Tamesluht,"9,406 kilometers away",Morocco,May,10473.0,4.85,9
51,Kalya,Near Syrian Desert,Israel,May,7228.0,5.00,5
52,Birkat al Maraqi,Near Sahara Desert,Egypt,May,249.0,5.00,16
53,Aqaba,Near Arabian Desert,Jordan,May,2061.0,5.00,5
54,Luxor,Near Sahara Desert,Egypt,May,347.0,5.00,5
55,Jaisalmer,Near Thar Desert,India,May,562.0,4.88,9
56,Oued El Khil,Near Sahara Desert,Tunisia,May,749.0,4.94,12
57,Mhamid,Near Sahara Desert,Morocco,May,207.0,5.00,6
58,commune rurale Fritissa,"8,935 kilometers away",Morocco,May,587.0,5.00,23
59,Tiznit,"9,635 kilometers away",Morocco,May,7687.0,5.00,6
60,Wadi Rum Village,Near Arabian Desert,Jordan,May,368.0,5.00,16
61,Hassilabied,Near Sahara Desert,Morocco,May,822.0,5.00,11
62,Fint,"9,328 kilometers away",Morocco,May,831.0,4.67,4
63,Arad,Near Arabian Desert,Israel,May,8080.0,5.00,4
64,Tamesluht,"9,406 kilometers away",Morocco,May,10473.0,5.00,9
65,Marrakech Alentours,"9,379 kilometers away",Morocco,May,35293.0,5.00,19
66,Merzouga,Near Sahara Desert,Morocco,May,877.0,5.00,8
67,Zagora,Near Sahara Desert,Morocco,May,256.0,5.00,6
68,Hassilabied,Near Sahara Desert,Morocco,May,263.0,4.67,11
69,Es Sabria,Near Sahara Desert,Tunisia,May,932.0,4.62,9
70,MA,Near Sahara Desert,Morocco,May,542.0,4.78,2
71,Al Ula,Near Arabian Desert,Saudi Arabia,May,16519.0,4.87,6
72,Nazlet El-Semman,Near Sahara Desert,Egypt,May,1370.0,4.63,16
73,Douz,Near Sahara Desert,Tunisia,May,1896.0,4.78,4
74,Arad,Near Arabian Desert,Israel,May,4209.0,4.78,4
75,Jaisalmer,Near Thar Desert,India,May,449.0,4.74,9
76,Zagora,Near Sahara Desert,Morocco,May,190.0,4.76,6
77,Hassilabied,Near Sahara Desert,Morocco,May,455.0,4.73,11
78,Zagora,Near Sahara Desert,Morocco,May,798.0,4.52,6
79,Merzouga,Near Sahara Desert,Morocco,May,780.0,4.79,8
80,Tinghir,Near Sahara Desert,Morocco,May,1346.0,4.67,7
81,Siwa Oasis,Near Sahara Desert,Egypt,May,867.0,4.70,10
82,Zagora,Near Sahara Desert,Morocco,May,466.0,4.67,6
83,Zagora,Near Sahara Desert,Morocco,May,425.0,4.43,6
84,Jaisalmer,Near Thar Desert,India,May,1198.0,4.52,9
85,Marrakech,"9,390 kilometers away",Morocco,May,648.0,4.76,9
86,Qesm Siwah,Near Sahara Desert,Egypt,May,790.0,4.76,10
87,Aoufous,Near Sahara Desert,Morocco,May,663.0,4.75,7
88,Wadi Rum Village,Near Arabian Desert,Jordan,May,244.0,4.50,16
89,Marrakech,"9,391 kilometers away",Morocco,May,3061.0,4.83,9
90,Sam,Near Thar Desert,India,May,628.0,4.23,3
91,Hassilabied,Near Sahara Desert,Morocco,May,1515.0,4.76,11
92,Kfar Adumim,Near Syrian Desert,Israel,May,4248.0,4.59,11
93,Essaouira,"9,536 kilometers away",Morocco,May,8977.0,4.89,9
94,Stavros,"6,425 kilometers away",Greece,May,9601.0,4.57,7
95,Merzouga,Near Sahara Desert,Morocco,May,812.0,4.84,8
96,Dahab,Near Arabian Desert,Egypt,May,1512.0,4.76,5
97,Ouarzazate,"9,349 kilometers away",Morocco,May,897.0,4.68,10
98,Tamesluht,"9,406 kilometers away",Morocco,May,10473.0,4.38,9
99,Merzouga,Near Sahara Desert,Morocco,May,2061.0,4.51,8
100,Boumalne Dades,Near Sahara Desert,Morocco,May,2359.0,4.50,14
101,Hassilabied,Near Sahara Desert,Morocco,May,1184.0,4.71,11
102,Bawity,Near Sahara Desert,Egypt,May,1239.0,4.75,6
103,Wadi rum,Near Arabian Desert,Jordan,May,217.0,4.70,8
104,Nador,"8,770 kilometers away",Morocco,May,1225.0,4.62,5
105,Hassilabied,Near Sahara Desert,Morocco,May,426.0,4.67,11
106,Ezuz,Near Arabian Desert,Israel,May,5545.0,4.00,4
107,Mhamid,Near Sahara Desert,Morocco,May,744.0,4.56,6
108,Mhamid,Near Sahara Desert,Morocco,May,565.0,4.67,6
109,Wadi Rum Village,Near Arabian Desert,Jordan,May,232.0,4.68,16
110,Merzouga,Near Sahara Desert,Morocco,May,299.0,4.82,8
111,Zagora,Near Sahara Desert,Morocco,May,220.0,4.60,6
112,M'Hamid El Ghizlane,Near Sahara Desert,Morocco,May,764.0,4.30,19
113,Mhamid,Near Sahara Desert,Morocco,May,1163.0,4.50,6
114,Khamlia,Near Sahara Desert,Morocco,May,1442.0,3.67,7
115,Ouarzazate,"9,341 kilometers away",Morocco,May,2326.0,4.68,10
116,Jaisalmer,Near Thar Desert,India,May,1310.0,4.71,9
117,Wadi Rum Village,Near Arabian Desert,Jordan,May,350.0,4.71,16
118,Zagora,Near Sahara Desert,Morocco,May,930.0,4.25,6
119,Quairah District,Near Arabian Desert,Jordan,May,155.0,4.84,16
120,Jaisalmer,Near Thar Desert,India,May,2039.0,4.20,9
121,Wadi Rum Village,Near Arabian Desert,Jordan,May,294.0,4.50,16
122,Merzouga,Near Sahara Desert,Morocco,May,2966.0,4.11,8
123,Mhamid,Near Sahara Desert,Morocco,May,295.0,4.53,6
124,Jaisalmer,Near Thar Desert,India,May,233.0,3.67,9
125,Ouled Arbia,"9,295 kilometers away",Morocco,May,2758.0,4.15,11
126,Merzouga,Near Sahara Desert,Morocco,May,1848.0,4.00,8
127,Bikaner,Near Thar Desert,India,May,1514.0,4.67,7
128,Tighza/Telouet,"9,328 kilometers away",Morocco,May,523.0,4.47,14
129,Merzouga,Near Sahara Desert,Morocco,May,989.0,4.74,8
130,Aqaba City,Near Arabian Desert,Jordan,May,341.0,4.64,10
131,Marrakesh,"9,391 kilometers away",Morocco,May,2612.0,4.67,9
132,Taghia,"9,215 kilometers away",Morocco,May,580.0,4.63,6
133,Mhamid,Near Sahara Desert,Morocco,May,665.0,4.58,6
134,Merzouga,Near Sahara Desert,"Morocco, Morocco",May,1330.0,4.76,8
135,Mhamid,Near Sahara Desert,Morocco,May,155.0,4.87,6
136,Hassilabied,Near Sahara Desert,Morocco,May,2534.0,4.52,11
137,Kanoi,Near Thar Desert,India,May,2353.0,4.82,5
138,Merzouga,Near Sahara Desert,Morocco,May,537.0,4.75,8
139,erg chebbi,Near Sahara Desert,Morocco,May,1115.0,4.83,10
140,Zagora,Near Sahara Desert,Morocco,May,1163.0,4.82,6
141,Merzouga,Near Sahara Desert,Morocco,May,2991.0,4.71,8
142,Wadi Rum Village,Near Arabian Desert,Jordan,May,350.0,4.60,16
143,Quairah District,Near Arabian Desert,Jordan,May,374.0,4.77,16
144,Bawity,Near Sahara Desert,Egypt,May,1549.0,4.67,6
145,Mhamid,Near Sahara Desert,Morocco,May,339.0,4.17,6
146,Ghewara,Near Thar Desert,India,May,1049.0,4.53,7
147,Merzouga,Near Sahara Desert,Morocco,May,399.0,4.58,8
148,Province de Ouarzazate,"9,336 kilometers away",Morocco,May,509.0,4.59,22
149,Quairah District,Near Arabian Desert,Jordan,May,1260.0,4.66,16
150,Agdz,Near Sahara Desert,Morocco,May,819.0,4.67,4
151,Jaisalmer,Near Thar Desert,India,May,1523.0,4.75,9
152,Qesm Siwah,Near Sahara Desert,Egypt,May,2369.0,4.74,10
153,Merzouga,Near Sahara Desert,Morocco,May,2425.0,4.86,8
154,Marrakesh,Near Sahara Desert,Morocco,May,2326.0,4.76,9
155,Zagora,Near Sahara Desert,Morocco,May,3153.0,4.67,6
156,Jaisalmer,Near Thar Desert,India,May,2039.0,4.46,9
157,Zagora,Near Sahara Desert,Morocco,May,2542.0,4.69,6
158,Khamlia,Near Sahara Desert,Morocco,May,1442.0,4.69,7
159,Marrakesh,"9,391 kilometers away",Morocco,May,2922.0,3.50,9
160,Erg Chebbi,Near Sahara Desert,Morocco,May,9969.0,4.86,10
161,Wadi Rum Village,Near Arabian Desert,Jordan,May,1260.0,4.74,16
162,Todra River,Near Sahara Desert,Morocco,May,335.0,4.82,11
163,Mhamid,Near Sahara Desert,Morocco,May,1163.0,4.63,6
164,Mhamid,Near Sahara Desert,Morocco,May,392.0,4.58,6
165,Jaisalmer,Near Thar Desert,India,May,1252.0,4.60,9
166,Mhamid,Near Sahara Desert,Morocco,May,759.0,4.56,6
167,Hassilabied,Near Sahara Desert,Morocco,May,1188.0,4.38,11
168,Wadi Rum Village,Near Arabian Desert,Jordan,May,339.0,0.00,16
169,Wadi Rum Village,Near Arabian Desert,Jordan,May,836.0,0.00,16
170,Mhamid,Near Sahara Desert,Morocco,May,1163.0,0.00,6
171,Mhamid,Near Sahara Desert,Morocco,May,1330.0,0.00,6
172,Mhamid,Near Sahara Desert,Morocco,May,1371.0,0.00,6
173,Marrakesh,"9,412 kilometers away",Morocco,May,51071.0,0.00,9
174,Mhamid,Near Sahara Desert,Morocco,May,1196.0,0.00,6
175,Tagounite,Near Sahara Desert,Morocco,May,997.0,0.00,9
176,merzouga,Near Sahara Desert,Morocco,May,276.0,0.00,8
177,Zagora,Near Sahara Desert,Morocco,May,1469.0,0.00,6
178,Merzouga,Near Sahara Desert,Morocco,May,7976.0,0.00,8
179,Wadi Rum Village,Near Arabian Desert,Jordan,May,1993.0,0.00,16
180,Essaouira,"9,536 kilometers away",Morocco,May,5386.0,0.00,9
181,Santorini,"6,291 kilometers away",Greece,May,7477.0,0.00,9
182,Oumnass,"9,405 kilometers away",Morocco,May,3745.0,0.00,7
183,Marrakesh,"9,373 kilometers away",Morocco,May,8307.0,0.00,9
184,Essaouira,"9,536 kilometers away",Morocco,May,5386.0,0.00,9
185,Marrakesh,"9,387 kilometers away",Morocco,May,19440.0,0.00,9
187,Marrakech,"9,389 kilometers away",Morocco,May,5360.0,0.00,9
188,Tidzi,"9,548 kilometers away",Morocco,May,6320.0,0.00,5
189,Aqaba City,Near Arabian Desert,Jordan,May,706.0,0.00,10
190,Ait Bihi,"9,586 kilometers away",Morocco,May,1303.0,0.00,8
191,Ouarzazate,"9,329 kilometers away",Morocco,May,231.0,0.00,10
192,Tamesluht,"9,404 kilometers away",Morocco,May,17752.0,0.00,9
193,Aït Ben Haddou,"9,341 kilometers away",Morocco,May,615.0,0.00,14
194,Wadi Rum Village,Near Arabian Desert,Jordan,May,396.0,0.00,16
195,Aït Ben Haddou,"9,341 kilometers away",Morocco,May,493.0,0.00,14
196,Ouarzazate,"9,327 kilometers away",Morocco,May,1553.0,0.00,10
197,Ait Bihi,"9,586 kilometers away",Morocco,May,1063.0,0.00,8
198,Ovnat,Near Syrian Desert,Israel,May,3094.0,0.00,5
199,Ouarzazate,"9,329 kilometers away",Morocco,May,296.0,0.00,10
200,Essaouira,"9,536 kilometers away",Morocco,May,5386.0,0.00,9
201,Faiyum,Near Sahara Desert,Egypt,May,1239.0,0.00,6
202,Marrakech,"9,384 kilometers away",Morocco,May,9969.0,0.00,9
203,Mhamid,Near Sahara Desert,Morocco,May,532.0,0.00,6
204,Merzouga,Near Sahara Desert,Morocco,May,665.0,0.00,8
205,Mhamid,Near Sahara Desert,Morocco,May,375.0,0.00,6
206,Ezuz,Near Arabian Desert,Israel,May,2635.0,0.00,4
207,Es Sabria,Near Sahara Desert,Tunisia,May,954.0,0.00,9
208,Jaisalmer Rural,Near Thar Desert,India,May,393.0,0.00,15
209,Errachidia Province,Near Sahara Desert,Morocco,May,455.0,0.00,19
210,Ma'an Governorate,Near Syrian Desert,Jordan,May,1993.0,0.00,17
211,Boumalne Dades,Near Sahara Desert,Morocco,May,658.0,0.00,14
212,Nuweibaa,Near Arabian Desert,Egypt,May,496.0,0.00,8
213,Zagora,Near Sahara Desert,Morocco,May,918.0,0.00,6
214,Aït Benhaddou,"9,340 kilometers away",Morocco,May,1455.0,0.00,13
215,Petra,Near Syrian Desert,"Jordan, Jordan",May,687.0,0.00,5
216,Wadi Rum Village,Near Arabian Desert,Jordan,May,465.0,0.00,16
217,Essaouira,"9,536 kilometers away",Morocco,May,5386.0,0.00,9
218,Palea Agia Roumeli,"6,442 kilometers away",Greece,May,851.0,0.00,18
219,Mhamid,Near Sahara Desert,Morocco,May,582.0,0.00,6
220,Zagora,Near Sahara Desert,Morocco,May,657.0,0.00,6
222,Douz,Near Sahara Desert,Tunisia,May,1526.0,0.00,4
223,Telouet,"9,331 kilometers away",Morocco,May,404.0,0.00,7
224,Tinghir,Near Sahara Desert,Morocco,May,665.0,0.00,7
225,Assouan,Near Sahara Desert,"Aswan, Egypt",May,929.0,0.00,7
226,Kathodi,Near Thar Desert,India,May,184.0,0.00,7
227,Ouarzazate,"9,340 kilometers away",Morocco,May,464.0,0.00,10
228,Abu AR Rish Qebli,Near Sahara Desert,Egypt,May,1163.0,0.00,17
229,Merzouga,Near Sahara Desert,Morocco,May,463.0,0.00,8
230,Wadi Rum Village,Near Arabian Desert,Jordan,May,178.0,0.00,16
231,Demnat,"9,296 kilometers away",Morocco,May,947.0,0.00,6
232,Quairah District,Near Arabian Desert,Jordan,May,501.0,0.00,16
233,Petra - Wadi Musa,Near Syrian Desert,Jordan,May,1041.0,0.00,17
234,Aït Ben Haddou,"9,337 kilometers away",Morocco,May,590.0,0.00,14
235,Wadi Rum Village,Near Arabian Desert,Jordan,May,1053.0,0.00,16
236,Quairah District,Near Arabian Desert,Jordan,May,155.0,0.00,16
237,Rissani,Near Sahara Desert,Morocco,May,396.0,0.00,7
238,Mhamid,Near Sahara Desert,Morocco,May,951.0,0.00,6
239,Wadi Rum Village,Near Arabian Desert,Jordan,May,786.0,0.00,16
240,Awrir,"9,584 kilometers away",Morocco,May,5951.0,0.00,5
241,Ras al-Khaimah,Near Arabian Desert,UAE,May,3038.0,0.00,14
242,Merzouga,Near Sahara Desert,Morocco,May,1202.0,0.00,8
244,Charco del Palo,"9,983 kilometers away",Spain,May,1958.0,0.00,15
245,Nijar (Almería),"8,657 kilometers away",Spain,May,2663.0,0.00,15
246,Mogán,"10,246 kilometers away",Spain,May,2383.0,0.00,5
247,Alhaurín el Grande,"8,891 kilometers away",Spain,May,12816.0,0.00,18
248,Níjar,"8,668 kilometers away",Spain,May,1165.0,0.00,5
249,Las Palmas,"10,057 kilometers away",Spain,May,3605.0,0.00,10
250,Swakopmund,"9,682 kilometers away",Namibia,May,6894.0,0.00,10
251,Antigua,"10,066 kilometers away",Spain,May,3515.0,0.00,7
252,Tarajalejo,"10,083 kilometers away",Spain,May,1982.0,0.00,10
253,Loxton,"9,530 kilometers away",South Africa,May,1331.0,0.00,6
254,Tarajalejo,"10,083 kilometers away",Spain,May,1164.0,0.00,10
255,Pozo de los Frailes,"8,667 kilometers away",Spain,May,3140.0,0.00,19
256,Tarajalejo,"10,083 kilometers away",Spain,May,1898.0,0.00,10
257,Palm-Mar,"10,319 kilometers away",Spain,May,8230.0,0.00,8
258,Las Hortichuelas,"8,658 kilometers away",Spain,May,1767.0,0.00,16
259,La Isleta del Moro,"8,662 kilometers away",Spain,May,2329.0,0.00,18
260,Tabernas,"8,681 kilometers away",Spain,May,1327.0,0.00,8
261,Caleta de Famara,"9,991 kilometers away",Spain,May,3733.0,0.00,16
262,Antas,"8,634 kilometers away",Spain,May,4387.0,0.00,5
263,El Roque,"10,050 kilometers away",Spain,May,696.0,0.00,8
264,Tabernas,"8,681 kilometers away",Spain,May,2064.0,0.00,8
265,Cuevas del Almanzora,"8,631 kilometers away",Spain,May,998.0,0.00,20
266,Tarajalejo,"10,083 kilometers away",Spain,May,1898.0,0.00,10
267,Montaña de Tindaya,"10,054 kilometers away",Spain,May,1139.0,0.00,18
268,El Pozo de los Frailes,"8,668 kilometers away",Spain,May,2227.0,0.00,22
269,Yaiza,"10,019 kilometers away",Spain,May,6695.0,0.00,5
270,Arrieta,"9,981 kilometers away",Spain,May,1597.0,0.00,7
271,Las Casitas,"10,017 kilometers away",Spain,May,17481.0,0.00,11
272,sceale bay,"7,821 kilometers away",Australia,May,4699.0,0.00,10
273,Caleta/Teguise,"9,993 kilometers away",Spain,May,1869.0,0.00,14
274,Bidiyah,Near Arabian Desert,Oman,May,1054.0,0.00,7
275,Haría Lanzarote,"9,981 kilometers away",Spain,May,5117.0,0.00,15
276,Tefia,"10,058 kilometers away",Spain,May,2326.0,0.00,5
277,El Pozo de los Frailes,"8,668 kilometers away",Spain,May,2994.0,0.00,22
278,Tarajalejo,"10,083 kilometers away",Spain,May,1616.0,0.00,10
279,Las Palmas,"10,055 kilometers away",Spain,May,1872.0,0.00,10

In [54]:
desert.shape

(272, 7)

In [55]:
invalid_locations = (
    desert["Property Location"].str.match(r"^[^A-Za-z0-9]", na=False)
    | (desert["Property Location"] == "No Name")
)

print("Remaining invalid property locations:", invalid_locations.sum())

Remaining invalid property locations: 0

In [56]:
print("Duplicate rows:", desert.duplicated().sum())

Duplicate rows: 4

In [57]:
duplicates = desert[desert.duplicated()]
display(duplicates)

,Property Location,Property Proximity,Country,Month,Price (In dollar),Rating,Location Length
184,Essaouira,"9,536 kilometers away",Morocco,May,5386.0,0.0,9
200,Essaouira,"9,536 kilometers away",Morocco,May,5386.0,0.0,9
217,Essaouira,"9,536 kilometers away",Morocco,May,5386.0,0.0,9
266,Tarajalejo,"10,083 kilometers away",Spain,May,1898.0,0.0,10

In [58]:
duplicates = desert[
    desert.duplicated(
        subset=[
            "Property Location",
            "Country",
            "Property Proximity"
        ],
        keep=False
    )
]

display(duplicates)

,Property Location,Property Proximity,Country,Month,Price (In dollar),Rating,Location Length
0,Mhamid,Near Sahara Desert,Morocco,May,479.0,4.79,6
1,Aqaba City,Near Arabian Desert,Jordan,May,2168.0,4.92,10
2,Tamesluht,"9,404 kilometers away",Morocco,May,17752.0,4.95,9
3,Al Bairat,Near Sahara Desert,Egypt,May,1982.0,4.88,9
4,Tamesluht,"9,404 kilometers away",Morocco,May,17752.0,4.87,9
5,Mitzpe Ramon,Near Arabian Desert,Israel,May,2502.0,4.81,12
6,M'Hamid El Ghizlane,Near Sahara Desert,Morocco,May,415.0,4.81,19
7,Tinghir,Near Sahara Desert,Morocco,May,1346.0,4.92,7
9,MA,Near Sahara Desert,Morocco,May,857.0,4.86,2
10,Mitzpe Ramon,Near Arabian Desert,Israel,May,2945.0,4.81,12
12,Jaisalmer,Near Thar Desert,India,May,449.0,4.79,9
14,Merzouga,Near Sahara Desert,Morocco,May,2937.0,4.83,8
15,Essaouira,"9,536 kilometers away",Morocco,May,5386.0,4.90,9
16,Jaisalmer,Near Thar Desert,India,May,284.0,4.86,9
18,Ait Bihi,"9,586 kilometers away",Morocco,May,1096.0,4.94,8
19,Jaisalmer,Near Thar Desert,India,May,677.0,4.79,9
20,Al Bairat,Near Sahara Desert,Egypt,May,1670.0,5.00,9
22,Hassilabied,Near Sahara Desert,Morocco,May,970.0,4.94,11
25,Ouarzazate,"9,327 kilometers away",Morocco,May,530.0,4.67,10
26,Wadi Rum Village,Near Arabian Desert,Jordan,May,823.0,5.00,16
27,Marrakech,"9,391 kilometers away",Morocco,May,3561.0,4.94,9
28,Wadi Rum Village,Near Arabian Desert,Jordan,May,898.0,4.86,16
29,M'Hamid El Ghizlane,Near Sahara Desert,Morocco,May,340.0,5.00,19
30,Tamesluht,"9,406 kilometers away",Morocco,May,12800.0,4.77,9
31,Mhamid,Near Sahara Desert,Morocco,May,179.0,4.89,6
32,Arad,Near Arabian Desert,Israel,May,3737.0,4.82,4
33,Merzouga,Near Sahara Desert,Morocco,May,840.0,4.98,8
34,Mhamid,Near Sahara Desert,Morocco,May,1145.0,4.87,6
36,Wadi Rum Village,Near Arabian Desert,Jordan,May,294.0,4.89,16
41,Arad,Near Arabian Desert,Israel,May,1734.0,5.00,4
45,Hassilabied,Near Sahara Desert,Morocco,May,997.0,4.76,11
48,Mhamid,Near Sahara Desert,Morocco,May,731.0,4.92,6
49,Tamesluht,"9,404 kilometers away",Morocco,May,17752.0,5.00,9
50,Tamesluht,"9,406 kilometers away",Morocco,May,10473.0,4.85,9
55,Jaisalmer,Near Thar Desert,India,May,562.0,4.88,9
57,Mhamid,Near Sahara Desert,Morocco,May,207.0,5.00,6
60,Wadi Rum Village,Near Arabian Desert,Jordan,May,368.0,5.00,16
61,Hassilabied,Near Sahara Desert,Morocco,May,822.0,5.00,11
63,Arad,Near Arabian Desert,Israel,May,8080.0,5.00,4
64,Tamesluht,"9,406 kilometers away",Morocco,May,10473.0,5.00,9
66,Merzouga,Near Sahara Desert,Morocco,May,877.0,5.00,8
67,Zagora,Near Sahara Desert,Morocco,May,256.0,5.00,6
68,Hassilabied,Near Sahara Desert,Morocco,May,263.0,4.67,11
69,Es Sabria,Near Sahara Desert,Tunisia,May,932.0,4.62,9
70,MA,Near Sahara Desert,Morocco,May,542.0,4.78,2
73,Douz,Near Sahara Desert,Tunisia,May,1896.0,4.78,4
74,Arad,Near Arabian Desert,Israel,May,4209.0,4.78,4
75,Jaisalmer,Near Thar Desert,India,May,449.0,4.74,9
76,Zagora,Near Sahara Desert,Morocco,May,190.0,4.76,6
77,Hassilabied,Near Sahara Desert,Morocco,May,455.0,4.73,11
78,Zagora,Near Sahara Desert,Morocco,May,798.0,4.52,6
79,Merzouga,Near Sahara Desert,Morocco,May,780.0,4.79,8
80,Tinghir,Near Sahara Desert,Morocco,May,1346.0,4.67,7
82,Zagora,Near Sahara Desert,Morocco,May,466.0,4.67,6
83,Zagora,Near Sahara Desert,Morocco,May,425.0,4.43,6
84,Jaisalmer,Near Thar Desert,India,May,1198.0,4.52,9
86,Qesm Siwah,Near Sahara Desert,Egypt,May,790.0,4.76,10
88,Wadi Rum Village,Near Arabian Desert,Jordan,May,244.0,4.50,16
89,Marrakech,"9,391 kilometers away",Morocco,May,3061.0,4.83,9
91,Hassilabied,Near Sahara Desert,Morocco,May,1515.0,4.76,11
93,Essaouira,"9,536 kilometers away",Morocco,May,8977.0,4.89,9
95,Merzouga,Near Sahara Desert,Morocco,May,812.0,4.84,8
98,Tamesluht,"9,406 kilometers away",Morocco,May,10473.0,4.38,9
99,Merzouga,Near Sahara Desert,Morocco,May,2061.0,4.51,8
100,Boumalne Dades,Near Sahara Desert,Morocco,May,2359.0,4.50,14
101,Hassilabied,Near Sahara Desert,Morocco,May,1184.0,4.71,11
102,Bawity,Near Sahara Desert,Egypt,May,1239.0,4.75,6
105,Hassilabied,Near Sahara Desert,Morocco,May,426.0,4.67,11
106,Ezuz,Near Arabian Desert,Israel,May,5545.0,4.00,4
107,Mhamid,Near Sahara Desert,Morocco,May,744.0,4.56,6
108,Mhamid,Near Sahara Desert,Morocco,May,565.0,4.67,6
109,Wadi Rum Village,Near Arabian Desert,Jordan,May,232.0,4.68,16
110,Merzouga,Near Sahara Desert,Morocco,May,299.0,4.82,8
111,Zagora,Near Sahara Desert,Morocco,May,220.0,4.60,6
112,M'Hamid El Ghizlane,Near Sahara Desert,Morocco,May,764.0,4.30,19
113,Mhamid,Near Sahara Desert,Morocco,May,1163.0,4.50,6
114,Khamlia,Near Sahara Desert,Morocco,May,1442.0,3.67,7
116,Jaisalmer,Near Thar Desert,India,May,1310.0,4.71,9
117,Wadi Rum Village,Near Arabian Desert,Jordan,May,350.0,4.71,16
118,Zagora,Near Sahara Desert,Morocco,May,930.0,4.25,6
119,Quairah District,Near Arabian Desert,Jordan,May,155.0,4.84,16
120,Jaisalmer,Near Thar Desert,India,May,2039.0,4.20,9
121,Wadi Rum Village,Near Arabian Desert,Jordan,May,294.0,4.50,16
122,Merzouga,Near Sahara Desert,Morocco,May,2966.0,4.11,8
123,Mhamid,Near Sahara Desert,Morocco,May,295.0,4.53,6
124,Jaisalmer,Near Thar Desert,India,May,233.0,3.67,9
126,Merzouga,Near Sahara Desert,Morocco,May,1848.0,4.00,8
129,Merzouga,Near Sahara Desert,Morocco,May,989.0,4.74,8
130,Aqaba City,Near Arabian Desert,Jordan,May,341.0,4.64,10
131,Marrakesh,"9,391 kilometers away",Morocco,May,2612.0,4.67,9
133,Mhamid,Near Sahara Desert,Morocco,May,665.0,4.58,6
135,Mhamid,Near Sahara Desert,Morocco,May,155.0,4.87,6
136,Hassilabied,Near Sahara Desert,Morocco,May,2534.0,4.52,11
138,Merzouga,Near Sahara Desert,Morocco,May,537.0,4.75,8
140,Zagora,Near Sahara Desert,Morocco,May,1163.0,4.82,6
141,Merzouga,Near Sahara Desert,Morocco,May,2991.0,4.71,8
142,Wadi Rum Village,Near Arabian Desert,Jordan,May,350.0,4.60,16
143,Quairah District,Near Arabian Desert,Jordan,May,374.0,4.77,16
144,Bawity,Near Sahara Desert,Egypt,May,1549.0,4.67,6
145,Mhamid,Near Sahara Desert,Morocco,May,339.0,4.17,6
147,Merzouga,Near Sahara Desert,Morocco,May,399.0,4.58,8
149,Quairah District,Near Arabian Desert,Jordan,May,1260.0,4.66,16
151,Jaisalmer,Near Thar Desert,India,May,1523.0,4.75,9
152,Qesm Siwah,Near Sahara Desert,Egypt,May,2369.0,4.74,10
153,Merzouga,Near Sahara Desert,Morocco,May,2425.0,4.86,8
155,Zagora,Near Sahara Desert,Morocco,May,3153.0,4.67,6
156,Jaisalmer,Near Thar Desert,India,May,2039.0,4.46,9
157,Zagora,Near Sahara Desert,Morocco,May,2542.0,4.69,6
158,Khamlia,Near Sahara Desert,Morocco,May,1442.0,4.69,7
159,Marrakesh,"9,391 kilometers away",Morocco,May,2922.0,3.50,9
161,Wadi Rum Village,Near Arabian Desert,Jordan,May,1260.0,4.74,16
163,Mhamid,Near Sahara Desert,Morocco,May,1163.0,4.63,6
164,Mhamid,Near Sahara Desert,Morocco,May,392.0,4.58,6
165,Jaisalmer,Near Thar Desert,India,May,1252.0,4.60,9
166,Mhamid,Near Sahara Desert,Morocco,May,759.0,4.56,6
167,Hassilabied,Near Sahara Desert,Morocco,May,1188.0,4.38,11
168,Wadi Rum Village,Near Arabian Desert,Jordan,May,339.0,0.00,16
169,Wadi Rum Village,Near Arabian Desert,Jordan,May,836.0,0.00,16
170,Mhamid,Near Sahara Desert,Morocco,May,1163.0,0.00,6
171,Mhamid,Near Sahara Desert,Morocco,May,1330.0,0.00,6
172,Mhamid,Near Sahara Desert,Morocco,May,1371.0,0.00,6
174,Mhamid,Near Sahara Desert,Morocco,May,1196.0,0.00,6
177,Zagora,Near Sahara Desert,Morocco,May,1469.0,0.00,6
178,Merzouga,Near Sahara Desert,Morocco,May,7976.0,0.00,8
179,Wadi Rum Village,Near Arabian Desert,Jordan,May,1993.0,0.00,16
180,Essaouira,"9,536 kilometers away",Morocco,May,5386.0,0.00,9
184,Essaouira,"9,536 kilometers away",Morocco,May,5386.0,0.00,9
189,Aqaba City,Near Arabian Desert,Jordan,May,706.0,0.00,10
190,Ait Bihi,"9,586 kilometers away",Morocco,May,1303.0,0.00,8
191,Ouarzazate,"9,329 kilometers away",Morocco,May,231.0,0.00,10
192,Tamesluht,"9,404 kilometers away",Morocco,May,17752.0,0.00,9
193,Aït Ben Haddou,"9,341 kilometers away",Morocco,May,615.0,0.00,14
194,Wadi Rum Village,Near Arabian Desert,Jordan,May,396.0,0.00,16
195,Aït Ben Haddou,"9,341 kilometers away",Morocco,May,493.0,0.00,14
196,Ouarzazate,"9,327 kilometers away",Morocco,May,1553.0,0.00,10
197,Ait Bihi,"9,586 kilometers away",Morocco,May,1063.0,0.00,8
199,Ouarzazate,"9,329 kilometers away",Morocco,May,296.0,0.00,10
200,Essaouira,"9,536 kilometers away",Morocco,May,5386.0,0.00,9
203,Mhamid,Near Sahara Desert,Morocco,May,532.0,0.00,6
204,Merzouga,Near Sahara Desert,Morocco,May,665.0,0.00,8
205,Mhamid,Near Sahara Desert,Morocco,May,375.0,0.00,6
206,Ezuz,Near Arabian Desert,Israel,May,2635.0,0.00,4
207,Es Sabria,Near Sahara Desert,Tunisia,May,954.0,0.00,9
211,Boumalne Dades,Near Sahara Desert,Morocco,May,658.0,0.00,14
213,Zagora,Near Sahara Desert,Morocco,May,918.0,0.00,6
216,Wadi Rum Village,Near Arabian Desert,Jordan,May,465.0,0.00,16
217,Essaouira,"9,536 kilometers away",Morocco,May,5386.0,0.00,9
219,Mhamid,Near Sahara Desert,Morocco,May,582.0,0.00,6
220,Zagora,Near Sahara Desert,Morocco,May,657.0,0.00,6
222,Douz,Near Sahara Desert,Tunisia,May,1526.0,0.00,4
224,Tinghir,Near Sahara Desert,Morocco,May,665.0,0.00,7
229,Merzouga,Near Sahara Desert,Morocco,May,463.0,0.00,8
230,Wadi Rum Village,Near Arabian Desert,Jordan,May,178.0,0.00,16
232,Quairah District,Near Arabian Desert,Jordan,May,501.0,0.00,16
235,Wadi Rum Village,Near Arabian Desert,Jordan,May,1053.0,0.00,16
236,Quairah District,Near Arabian Desert,Jordan,May,155.0,0.00,16
238,Mhamid,Near Sahara Desert,Morocco,May,951.0,0.00,6
239,Wadi Rum Village,Near Arabian Desert,Jordan,May,786.0,0.00,16
242,Merzouga,Near Sahara Desert,Morocco,May,1202.0,0.00,8
252,Tarajalejo,"10,083 kilometers away",Spain,May,1982.0,0.00,10
254,Tarajalejo,"10,083 kilometers away",Spain,May,1164.0,0.00,10
256,Tarajalejo,"10,083 kilometers away",Spain,May,1898.0,0.00,10
260,Tabernas,"8,681 kilometers away",Spain,May,1327.0,0.00,8
264,Tabernas,"8,681 kilometers away",Spain,May,2064.0,0.00,8
266,Tarajalejo,"10,083 kilometers away",Spain,May,1898.0,0.00,10
268,El Pozo de los Frailes,"8,668 kilometers away",Spain,May,2227.0,0.00,22
277,El Pozo de los Frailes,"8,668 kilometers away",Spain,May,2994.0,0.00,22
278,Tarajalejo,"10,083 kilometers away",Spain,May,1616.0,0.00,10

In [59]:
duplicate_count = desert.duplicated(
    subset=[
        "Property Location",
        "Country",
        "Property Proximity"
    ]
).sum()

print("Number of duplicate properties:", duplicate_count)

Number of duplicate properties: 135

In [61]:
duplicates = desert[
    desert.duplicated(
        subset=[
            "Property Location",
            "Property Proximity",
            "Country",
            "Month",
            "Price (In dollar)",
            "Rating"
        ],
        keep=False
    )
]

display(duplicates)

,Property Location,Property Proximity,Country,Month,Price (In dollar),Rating,Location Length
180,Essaouira,"9,536 kilometers away",Morocco,May,5386.0,0.0,9
184,Essaouira,"9,536 kilometers away",Morocco,May,5386.0,0.0,9
200,Essaouira,"9,536 kilometers away",Morocco,May,5386.0,0.0,9
217,Essaouira,"9,536 kilometers away",Morocco,May,5386.0,0.0,9
256,Tarajalejo,"10,083 kilometers away",Spain,May,1898.0,0.0,10
266,Tarajalejo,"10,083 kilometers away",Spain,May,1898.0,0.0,10

In [62]:
print("Total duplicate rows:", len(duplicates))

Total duplicate rows: 6

In [64]:
print(duplicates.to_string(index=False))

Property Location     Property Proximity Country Month  Price (In dollar)  Rating  Location Length
        Essaouira  9,536 kilometers away Morocco   May             5386.0     0.0                9
        Essaouira  9,536 kilometers away Morocco   May             5386.0     0.0                9
        Essaouira  9,536 kilometers away Morocco   May             5386.0     0.0                9
        Essaouira  9,536 kilometers away Morocco   May             5386.0     0.0                9
       Tarajalejo 10,083 kilometers away   Spain   May             1898.0     0.0               10
       Tarajalejo 10,083 kilometers away   Spain   May             1898.0     0.0               10

In [65]:
desert = desert.drop_duplicates(
    subset=[
        "Property Location",
        "Country",
        "Property Proximity"
    ]
)

display(desert)

,Property Location,Property Proximity,Country,Month,Price (In dollar),Rating,Location Length
0,Mhamid,Near Sahara Desert,Morocco,May,479.0,4.79,6
1,Aqaba City,Near Arabian Desert,Jordan,May,2168.0,4.92,10
2,Tamesluht,"9,404 kilometers away",Morocco,May,17752.0,4.95,9
3,Al Bairat,Near Sahara Desert,Egypt,May,1982.0,4.88,9
5,Mitzpe Ramon,Near Arabian Desert,Israel,May,2502.0,4.81,12
6,M'Hamid El Ghizlane,Near Sahara Desert,Morocco,May,415.0,4.81,19
7,Tinghir,Near Sahara Desert,Morocco,May,1346.0,4.92,7
8,Skoura,"9,293 kilometers away",Morocco,May,928.0,4.91,6
9,MA,Near Sahara Desert,Morocco,May,857.0,4.86,2
11,Wadi Rum,Near Arabian Desert,Jordan,May,898.0,4.84,8
12,Jaisalmer,Near Thar Desert,India,May,449.0,4.79,9
13,Siwa,Near Sahara Desert,Egypt,May,991.0,4.90,4
14,Merzouga,Near Sahara Desert,Morocco,May,2937.0,4.83,8
15,Essaouira,"9,536 kilometers away",Morocco,May,5386.0,4.90,9
17,Tzofar,Near Arabian Desert,Israel,May,1821.0,4.77,6
18,Ait Bihi,"9,586 kilometers away",Morocco,May,1096.0,4.94,8
22,Hassilabied,Near Sahara Desert,Morocco,May,970.0,4.94,11
23,Aglou,"9,637 kilometers away",Morocco,May,2792.0,5.00,5
24,Takojt,Near Sahara Desert,Morocco,May,371.0,5.00,6
25,Ouarzazate,"9,327 kilometers away",Morocco,May,530.0,4.67,10
26,Wadi Rum Village,Near Arabian Desert,Jordan,May,823.0,5.00,16
27,Marrakech,"9,391 kilometers away",Morocco,May,3561.0,4.94,9
30,Tamesluht,"9,406 kilometers away",Morocco,May,12800.0,4.77,9
32,Arad,Near Arabian Desert,Israel,May,3737.0,4.82,4
37,Marrakesh,"9,414 kilometers away",Morocco,May,7515.0,4.94,9
38,Triopetra,"6,390 kilometers away",Greece,May,3209.0,4.82,9
39,Ksar Bounou (Oasis de M´hamid Alguizlane ),Near Sahara Desert,Morocco,May,285.0,4.95,42
43,Midreshet Ben-Gurion,Near Arabian Desert,Israel,May,2994.0,5.00,20
44,M'HAMID,Near Sahara Desert,Morocco,May,305.0,4.86,7
46,Khuri,Near Thar Desert,India,May,375.0,4.82,5
51,Kalya,Near Syrian Desert,Israel,May,7228.0,5.00,5
52,Birkat al Maraqi,Near Sahara Desert,Egypt,May,249.0,5.00,16
53,Aqaba,Near Arabian Desert,Jordan,May,2061.0,5.00,5
54,Luxor,Near Sahara Desert,Egypt,May,347.0,5.00,5
56,Oued El Khil,Near Sahara Desert,Tunisia,May,749.0,4.94,12
58,commune rurale Fritissa,"8,935 kilometers away",Morocco,May,587.0,5.00,23
59,Tiznit,"9,635 kilometers away",Morocco,May,7687.0,5.00,6
62,Fint,"9,328 kilometers away",Morocco,May,831.0,4.67,4
65,Marrakech Alentours,"9,379 kilometers away",Morocco,May,35293.0,5.00,19
67,Zagora,Near Sahara Desert,Morocco,May,256.0,5.00,6
69,Es Sabria,Near Sahara Desert,Tunisia,May,932.0,4.62,9
71,Al Ula,Near Arabian Desert,Saudi Arabia,May,16519.0,4.87,6
72,Nazlet El-Semman,Near Sahara Desert,Egypt,May,1370.0,4.63,16
73,Douz,Near Sahara Desert,Tunisia,May,1896.0,4.78,4
81,Siwa Oasis,Near Sahara Desert,Egypt,May,867.0,4.70,10
85,Marrakech,"9,390 kilometers away",Morocco,May,648.0,4.76,9
86,Qesm Siwah,Near Sahara Desert,Egypt,May,790.0,4.76,10
87,Aoufous,Near Sahara Desert,Morocco,May,663.0,4.75,7
90,Sam,Near Thar Desert,India,May,628.0,4.23,3
92,Kfar Adumim,Near Syrian Desert,Israel,May,4248.0,4.59,11
94,Stavros,"6,425 kilometers away",Greece,May,9601.0,4.57,7
96,Dahab,Near Arabian Desert,Egypt,May,1512.0,4.76,5
97,Ouarzazate,"9,349 kilometers away",Morocco,May,897.0,4.68,10
100,Boumalne Dades,Near Sahara Desert,Morocco,May,2359.0,4.50,14
102,Bawity,Near Sahara Desert,Egypt,May,1239.0,4.75,6
103,Wadi rum,Near Arabian Desert,Jordan,May,217.0,4.70,8
104,Nador,"8,770 kilometers away",Morocco,May,1225.0,4.62,5
106,Ezuz,Near Arabian Desert,Israel,May,5545.0,4.00,4
114,Khamlia,Near Sahara Desert,Morocco,May,1442.0,3.67,7
115,Ouarzazate,"9,341 kilometers away",Morocco,May,2326.0,4.68,10
119,Quairah District,Near Arabian Desert,Jordan,May,155.0,4.84,16
125,Ouled Arbia,"9,295 kilometers away",Morocco,May,2758.0,4.15,11
127,Bikaner,Near Thar Desert,India,May,1514.0,4.67,7
128,Tighza/Telouet,"9,328 kilometers away",Morocco,May,523.0,4.47,14
131,Marrakesh,"9,391 kilometers away",Morocco,May,2612.0,4.67,9
132,Taghia,"9,215 kilometers away",Morocco,May,580.0,4.63,6
134,Merzouga,Near Sahara Desert,"Morocco, Morocco",May,1330.0,4.76,8
137,Kanoi,Near Thar Desert,India,May,2353.0,4.82,5
139,erg chebbi,Near Sahara Desert,Morocco,May,1115.0,4.83,10
146,Ghewara,Near Thar Desert,India,May,1049.0,4.53,7
148,Province de Ouarzazate,"9,336 kilometers away",Morocco,May,509.0,4.59,22
150,Agdz,Near Sahara Desert,Morocco,May,819.0,4.67,4
154,Marrakesh,Near Sahara Desert,Morocco,May,2326.0,4.76,9
160,Erg Chebbi,Near Sahara Desert,Morocco,May,9969.0,4.86,10
162,Todra River,Near Sahara Desert,Morocco,May,335.0,4.82,11
173,Marrakesh,"9,412 kilometers away",Morocco,May,51071.0,0.00,9
175,Tagounite,Near Sahara Desert,Morocco,May,997.0,0.00,9
176,merzouga,Near Sahara Desert,Morocco,May,276.0,0.00,8
181,Santorini,"6,291 kilometers away",Greece,May,7477.0,0.00,9
182,Oumnass,"9,405 kilometers away",Morocco,May,3745.0,0.00,7
183,Marrakesh,"9,373 kilometers away",Morocco,May,8307.0,0.00,9
185,Marrakesh,"9,387 kilometers away",Morocco,May,19440.0,0.00,9
187,Marrakech,"9,389 kilometers away",Morocco,May,5360.0,0.00,9
188,Tidzi,"9,548 kilometers away",Morocco,May,6320.0,0.00,5
191,Ouarzazate,"9,329 kilometers away",Morocco,May,231.0,0.00,10
193,Aït Ben Haddou,"9,341 kilometers away",Morocco,May,615.0,0.00,14
198,Ovnat,Near Syrian Desert,Israel,May,3094.0,0.00,5
201,Faiyum,Near Sahara Desert,Egypt,May,1239.0,0.00,6
202,Marrakech,"9,384 kilometers away",Morocco,May,9969.0,0.00,9
208,Jaisalmer Rural,Near Thar Desert,India,May,393.0,0.00,15
209,Errachidia Province,Near Sahara Desert,Morocco,May,455.0,0.00,19
210,Ma'an Governorate,Near Syrian Desert,Jordan,May,1993.0,0.00,17
212,Nuweibaa,Near Arabian Desert,Egypt,May,496.0,0.00,8
214,Aït Benhaddou,"9,340 kilometers away",Morocco,May,1455.0,0.00,13
215,Petra,Near Syrian Desert,"Jordan, Jordan",May,687.0,0.00,5
218,Palea Agia Roumeli,"6,442 kilometers away",Greece,May,851.0,0.00,18
223,Telouet,"9,331 kilometers away",Morocco,May,404.0,0.00,7
225,Assouan,Near Sahara Desert,"Aswan, Egypt",May,929.0,0.00,7
226,Kathodi,Near Thar Desert,India,May,184.0,0.00,7
227,Ouarzazate,"9,340 kilometers away",Morocco,May,464.0,0.00,10
228,Abu AR Rish Qebli,Near Sahara Desert,Egypt,May,1163.0,0.00,17
231,Demnat,"9,296 kilometers away",Morocco,May,947.0,0.00,6
233,Petra - Wadi Musa,Near Syrian Desert,Jordan,May,1041.0,0.00,17
234,Aït Ben Haddou,"9,337 kilometers away",Morocco,May,590.0,0.00,14
237,Rissani,Near Sahara Desert,Morocco,May,396.0,0.00,7
240,Awrir,"9,584 kilometers away",Morocco,May,5951.0,0.00,5
241,Ras al-Khaimah,Near Arabian Desert,UAE,May,3038.0,0.00,14
244,Charco del Palo,"9,983 kilometers away",Spain,May,1958.0,0.00,15
245,Nijar (Almería),"8,657 kilometers away",Spain,May,2663.0,0.00,15
246,Mogán,"10,246 kilometers away",Spain,May,2383.0,0.00,5
247,Alhaurín el Grande,"8,891 kilometers away",Spain,May,12816.0,0.00,18
248,Níjar,"8,668 kilometers away",Spain,May,1165.0,0.00,5
249,Las Palmas,"10,057 kilometers away",Spain,May,3605.0,0.00,10
250,Swakopmund,"9,682 kilometers away",Namibia,May,6894.0,0.00,10
251,Antigua,"10,066 kilometers away",Spain,May,3515.0,0.00,7
252,Tarajalejo,"10,083 kilometers away",Spain,May,1982.0,0.00,10
253,Loxton,"9,530 kilometers away",South Africa,May,1331.0,0.00,6
255,Pozo de los Frailes,"8,667 kilometers away",Spain,May,3140.0,0.00,19
257,Palm-Mar,"10,319 kilometers away",Spain,May,8230.0,0.00,8
258,Las Hortichuelas,"8,658 kilometers away",Spain,May,1767.0,0.00,16
259,La Isleta del Moro,"8,662 kilometers away",Spain,May,2329.0,0.00,18
260,Tabernas,"8,681 kilometers away",Spain,May,1327.0,0.00,8
261,Caleta de Famara,"9,991 kilometers away",Spain,May,3733.0,0.00,16
262,Antas,"8,634 kilometers away",Spain,May,4387.0,0.00,5
263,El Roque,"10,050 kilometers away",Spain,May,696.0,0.00,8
265,Cuevas del Almanzora,"8,631 kilometers away",Spain,May,998.0,0.00,20
267,Montaña de Tindaya,"10,054 kilometers away",Spain,May,1139.0,0.00,18
268,El Pozo de los Frailes,"8,668 kilometers away",Spain,May,2227.0,0.00,22
269,Yaiza,"10,019 kilometers away",Spain,May,6695.0,0.00,5
270,Arrieta,"9,981 kilometers away",Spain,May,1597.0,0.00,7
271,Las Casitas,"10,017 kilometers away",Spain,May,17481.0,0.00,11
272,sceale bay,"7,821 kilometers away",Australia,May,4699.0,0.00,10
273,Caleta/Teguise,"9,993 kilometers away",Spain,May,1869.0,0.00,14
274,Bidiyah,Near Arabian Desert,Oman,May,1054.0,0.00,7
275,Haría Lanzarote,"9,981 kilometers away",Spain,May,5117.0,0.00,15
276,Tefia,"10,058 kilometers away",Spain,May,2326.0,0.00,5
279,Las Palmas,"10,055 kilometers away",Spain,May,1872.0,0.00,10

In [66]:
print("Duplicate rows:", desert.duplicated().sum())

Duplicate rows: 0

In [67]:
duplicates = desert[
    desert.duplicated(
        subset=[
            "Property Location",
            "Property Proximity",
            "Country",
            "Month",
            "Price (In dollar)",
            "Rating"
        ],
        keep=False
    )
]

print("Remaining duplicate rows:", len(duplicates))
display(duplicates)

Remaining duplicate rows: 0

Empty DataFrame
Columns: [Property Location, Property Proximity, Country, Month, Price (In dollar), Rating, Location Length]
Index: []