In [31]:
import pandas as pd
import os

print(os.listdir("data"))
print(os.listdir("data/raw"))

['.DS_Store', 'clean', 'raw']
['.DS_Store', 'airnb.csv', 'Untitled.ipynb', 'airnb_desert.csv', '.ipynb_checkpoints', 'airnb_luxe.csv']

In [35]:
airbnb = pd.read_csv("data/raw/airnb.csv")

In [36]:
airbnb.head()

,Title,Detail,Date,Price(in dollar),Offer price(in dollar),Review and rating,Number of bed
0,"Chalet in Skykomish, Washington, US",Sky Haus - A-Frame Cabin,Jun 11 - 16,306.00,229.00,4.85 (531),4 beds
1,"Cabin in Hancock, New York, US",The Catskill A-Frame - Mid-Century Modern Cabin,Jun 6 - 11,485.00,170.00,4.77 (146),4 beds
2,"Cabin in West Farmington, Ohio, US",The Triangle: A-Frame Cabin for your city retreat,Jul 9 - 14,119.00,522.00,4.91 (515),4 beds
3,"Home in Blue Ridge, Georgia, US",*Summer Sizzle* 5 Min to Blue Ridge* Pets* Hot...,Jun 11 - 16,192.00,348.00,4.94 (88),5 beds
4,"Treehouse in Grandview, Texas, US",Luxury Treehouse Couples Getaway w/ Peaceful V...,Jun 4 - 9,232.00,196.00,4.99 (222),1 queen bed

In [38]:
airbnb["Title"].head(20)

0                 Chalet in Skykomish, Washington, US
1                      Cabin in Hancock, New York, US
2                  Cabin in West Farmington, Ohio, US
3                     Home in Blue Ridge, Georgia, US
4                   Treehouse in Grandview, Texas, US
5               Tiny home in Puerto Escondido, Mexico
6                             Home in Saco, Maine, US
7                       Chalet in Grand Étang, Canada
8                         Room in Mexico City, Mexico
9               Tiny home in Sandy Valley, Nevada, US
10                  Guest suite in Huntsville, Canada
11                            Cabin in Nelson, Canada
12                Dome in Joshua Tree, California, US
13                    Barn in Vero Beach, Florida, US
14                   Tiny home in Bolton, Vermont, US
15                          Cabin in Ucluelet, Canada
16                              Barn in Essex, Canada
17                       Apartment in Bacalar, Mexico
18    Treehouse in Travelers Rest, South Carolina, US
19      Farm stay in Del Norte County, California, US
Name: Title, dtype: object

In [45]:
airbnb[["BnB_Type", "Location"]] = airbnb["Title"].str.split(
    " in ",
    n=1,
    expand=True
)

In [46]:
airbnb[["City", "Country"]] = airbnb["Location"].str.split(
    ",",
    n=1,
    expand=True
)

# Remove extra spaces
airbnb["City"] = airbnb["City"].str.strip()
airbnb["Country"] = airbnb["Country"].str.strip()

In [42]:
split = airbnb["Title"].str.split(" in ", n=1, expand=True)

airbnb["BnB_Type"] = split[0]
airbnb["Location"] = split[1]
airbnb[["BnB_Type", "Location"]].isnull().sum()

BnB_Type    0
Location    0
dtype: int64

In [48]:
# Split Location into City and Country
airbnb[["City", "Country"]] = airbnb["Location"].str.split(
    ",",
    n=1,
    expand=True
)

# Remove leading and trailing spaces
airbnb["City"] = airbnb["City"].str.strip()
airbnb["Country"] = airbnb["Country"].str.strip()

In [49]:
airbnb[["Location", "City", "Country"]].head(10)

                    Location              City         Country
0  Skykomish, Washington, US         Skykomish  Washington, US
1      Hancock, New York, US           Hancock    New York, US
2  West Farmington, Ohio, US   West Farmington        Ohio, US
3    Blue Ridge, Georgia, US        Blue Ridge     Georgia, US
4       Grandview, Texas, US         Grandview       Texas, US
5   Puerto Escondido, Mexico  Puerto Escondido          Mexico
6            Saco, Maine, US              Saco       Maine, US
7        Grand Étang, Canada       Grand Étang          Canada
8        Mexico City, Mexico       Mexico City          Mexico
9   Sandy Valley, Nevada, US      Sandy Valley      Nevada, US

In [51]:
# Extract the first month abbreviation
airbnb["Month"] = airbnb["Date"].str.extract(r"^([A-Za-z]{3})")[0]

# Convert to full month name
month_map = {
    "Jan": "January",
    "Feb": "February",
    "Mar": "March",
    "Apr": "April",
    "May": "May",
    "Jun": "June",
    "Jul": "July",
    "Aug": "August",
    "Sep": "September",
    "Oct": "October",
    "Nov": "November",
    "Dec": "December"
}

airbnb["Month"] = airbnb["Month"].map(month_map)

airbnb[["Date", "Month"]].head()

          Date Month
0  Jun 11 - 16  June
1   Jun 6 - 11  June
2   Jul 9 - 14  July
3  Jun 11 - 16  June
4    Jun 4 - 9  June

In [53]:
# Rating
airbnb["Rating"] = airbnb["Review and rating"].str.extract(r"(\d+\.\d+)")

# Review count
airbnb["Reviews"] = airbnb["Review and rating"].str.extract(r"(\d+)")

# Convert to numeric
airbnb["Rating"] = pd.to_numeric(airbnb["Rating"], errors="coerce")
airbnb["Reviews"] = pd.to_numeric(airbnb["Reviews"], errors="coerce")

In [54]:
airbnb["Review and rating"].head(10)

0    4.85 (531)
1    4.77 (146)
2    4.91 (515)
3     4.94 (88)
4    4.99 (222)
5    4.84 (555)
6     4.64 (90)
7      5.0 (48)
8     4.84 (58)
9    4.92 (744)
Name: Review and rating, dtype: object

In [55]:
# Extract Rating
airbnb["Rating"] = airbnb["Review and rating"].str.extract(r'(\d+\.\d+|\d+)')

# Extract Number of Reviews
airbnb["Reviews"] = airbnb["Review and rating"].str.extract(r'\((\d+)\)')

# Convert both columns to numeric
airbnb["Rating"] = pd.to_numeric(airbnb["Rating"])
airbnb["Reviews"] = pd.to_numeric(airbnb["Reviews"])

# Display the result
airbnb[["Review and rating", "Rating", "Reviews"]].head(10)

  Review and rating  Rating  Reviews
0        4.85 (531)    4.85    531.0
1        4.77 (146)    4.77    146.0
2        4.91 (515)    4.91    515.0
3         4.94 (88)    4.94     88.0
4        4.99 (222)    4.99    222.0
5        4.84 (555)    4.84    555.0
6         4.64 (90)    4.64     90.0
7          5.0 (48)    5.00     48.0
8         4.84 (58)    4.84     58.0
9        4.92 (744)    4.92    744.0

In [56]:
# Get the list of columns
cols = airbnb.columns.tolist()

# Remove the Review and Rating columns
cols.remove("Reviews")
cols.remove("Rating")

# Find the position of the Detail column
detail_index = cols.index("Detail")

# Insert Rating and Reviews after Detail
cols.insert(detail_index + 1, "Rating")
cols.insert(detail_index + 2, "Reviews")

# Reorder the DataFrame
airbnb = airbnb[cols]

# Display the first few rows
airbnb.head()

,Title,Detail,Rating,Reviews,Date,Price(in dollar),Offer price(in dollar),Review and rating,Number of bed,BnB_Type,Location,City,Country,Month
0,"Chalet in Skykomish, Washington, US",Sky Haus - A-Frame Cabin,4.85,531.0,Jun 11 - 16,306.00,229.00,4.85 (531),4 beds,Chalet,"Skykomish, Washington, US",Skykomish,"Washington, US",Jun
1,"Cabin in Hancock, New York, US",The Catskill A-Frame - Mid-Century Modern Cabin,4.77,146.0,Jun 6 - 11,485.00,170.00,4.77 (146),4 beds,Cabin,"Hancock, New York, US",Hancock,"New York, US",Jun
2,"Cabin in West Farmington, Ohio, US",The Triangle: A-Frame Cabin for your city retreat,4.91,515.0,Jul 9 - 14,119.00,522.00,4.91 (515),4 beds,Cabin,"West Farmington, Ohio, US",West Farmington,"Ohio, US",Jul
3,"Home in Blue Ridge, Georgia, US",*Summer Sizzle* 5 Min to Blue Ridge* Pets* Hot...,4.94,88.0,Jun 11 - 16,192.00,348.00,4.94 (88),5 beds,Home,"Blue Ridge, Georgia, US",Blue Ridge,"Georgia, US",Jun
4,"Treehouse in Grandview, Texas, US",Luxury Treehouse Couples Getaway w/ Peaceful V...,4.99,222.0,Jun 4 - 9,232.00,196.00,4.99 (222),1 queen bed,Treehouse,"Grandview, Texas, US",Grandview,"Texas, US",Jun

In [57]:
print("Minimum Rating:", airbnb["Rating"].min())

Minimum Rating: 3.67

In [58]:
lowest_rating = airbnb["Rating"].min()

airbnb[airbnb["Rating"] == lowest_rating]

,Title,Detail,Rating,Reviews,Date,Price(in dollar),Offer price(in dollar),Review and rating,Number of bed,BnB_Type,Location,City,Country,Month
276,"Apartment in Calpe, Spain",Apartment Caribe - PlusHolidays,3.67,3.0,Jun 1 - 6,80.00,NaN,3.67 (3),2 double beds,Apartment,"Calpe, Spain",Calpe,Spain,Jun

In [59]:
lowest_reviews = airbnb["Reviews"].min()

airbnb[airbnb["Reviews"] == lowest_reviews]

,Title,Detail,Rating,Reviews,Date,Price(in dollar),Offer price(in dollar),Review and rating,Number of bed,BnB_Type,Location,City,Country,Month
83,"Campsite in Nemaiah Valley, Canada",Sunset Wilderness Camp,4.00,3.0,Jun 1 - 6,34.00,NaN,4.0 (3),1 bed,Campsite,"Nemaiah Valley, Canada",Nemaiah Valley,Canada,Jun
276,"Apartment in Calpe, Spain",Apartment Caribe - PlusHolidays,3.67,3.0,Jun 1 - 6,80.00,NaN,3.67 (3),2 double beds,Apartment,"Calpe, Spain",Calpe,Spain,Jun
365,"Apartment in Kadıköy, Turkey",Studio apartment with AC - Suite 3,5.00,3.0,Jun 17 - 22,34.00,NaN,5.0 (3),3 beds,Apartment,"Kadıköy, Turkey",Kadıköy,Turkey,Jun
820,Apartment in Sarasota,Private Bay area home !,4.67,3.0,May 1 - 6,117.00,NaN,4.67 (3),3 beds,Apartment,Sarasota,Sarasota,None,May

In [60]:
airbnb.sort_values(by="Rating").head(10)

,Title,Detail,Rating,Reviews,Date,Price(in dollar),Offer price(in dollar),Review and rating,Number of bed,BnB_Type,Location,City,Country,Month
276,"Apartment in Calpe, Spain",Apartment Caribe - PlusHolidays,3.67,3.0,Jun 1 - 6,80.00,NaN,3.67 (3),2 double beds,Apartment,"Calpe, Spain",Calpe,Spain,Jun
83,"Campsite in Nemaiah Valley, Canada",Sunset Wilderness Camp,4.00,3.0,Jun 1 - 6,34.00,NaN,4.0 (3),1 bed,Campsite,"Nemaiah Valley, Canada",Nemaiah Valley,Canada,Jun
781,Apartment in Orlando,Cozy Studio close to Universal,4.20,148.0,May 1 - 6,82.00,NaN,4.2 (148),2 beds,Apartment,Orlando,Orlando,None,May
591,"Condo in George Town, Malaysia",Lovely 1 Bedroom Suite with Pool View,4.27,56.0,Jun 5 - 10,26.00,NaN,4.27 (56),3 beds,Condo,"George Town, Malaysia",George Town,Malaysia,Jun
262,"Houseboat in Jickovice, Czechia","Boat in Orlik, you want it!",4.31,29.0,Jun 8 - 13,78.00,NaN,4.31 (29),4 sofa beds,Houseboat,"Jickovice, Czechia",Jickovice,Czechia,Jun
299,"Farm stay in Montepulciano, Italy",Rural Tuscany | Wine farm with pool | Terrarossa,4.33,6.0,Jun 14 - 20,148.00,NaN,4.33 (6),5 beds,Farm stay,"Montepulciano, Italy",Montepulciano,Italy,Jun
231,"Home in Avalon, California, US","Tropical Island Escape w/ Deck, Walk to Avalon...",4.34,80.0,Jun 19 - 24,336.00,NaN,4.34 (80),1 queen bed,Home,"Avalon, California, US",Avalon,"California, US",Jun
649,"Hotel in Nha Trang, Vietnam",VENUE HOTEL-20% Superior City NiceWindow#Good ...,4.35,17.0,Jun 4 - 9,17.00,177.00,4.35 (17),1 bed,Hotel,"Nha Trang, Vietnam",Nha Trang,Vietnam,Jun
193,"Apartment in Laguna Beach, California, US",Laguna Beach Studio Oceanviews 49,4.36,273.0,Jun 1 - 6,148.00,NaN,4.36 (273),2 beds,Apartment,"Laguna Beach, California, US",Laguna Beach,"California, US",Jun
217,"Boutique hotel in Miami Beach, Florida, US",Room 2 Queen beds- Buffet Breakfast-Steps to b...,4.38,156.0,Jun 5 - 10,116.00,139.00,4.38 (156),2 beds,Boutique hotel,"Miami Beach, Florida, US",Miami Beach,"Florida, US",Jun

In [61]:
# Arrange columns in the desired order
airbnb = airbnb[[
    "Title",
    "Detail",
    "BnB_Type",
    "City",
    "Country",
    "Month",
    "Price(in dollar)",
    "Rating",
    "Reviews"
]]

# Display the updated DataFrame
airbnb.head()

,Title,Detail,BnB_Type,City,Country,Month,Price(in dollar),Rating,Reviews
0,"Chalet in Skykomish, Washington, US",Sky Haus - A-Frame Cabin,Chalet,Skykomish,"Washington, US",Jun,306.00,4.85,531.0
1,"Cabin in Hancock, New York, US",The Catskill A-Frame - Mid-Century Modern Cabin,Cabin,Hancock,"New York, US",Jun,485.00,4.77,146.0
2,"Cabin in West Farmington, Ohio, US",The Triangle: A-Frame Cabin for your city retreat,Cabin,West Farmington,"Ohio, US",Jul,119.00,4.91,515.0
3,"Home in Blue Ridge, Georgia, US",*Summer Sizzle* 5 Min to Blue Ridge* Pets* Hot...,Home,Blue Ridge,"Georgia, US",Jun,192.00,4.94,88.0
4,"Treehouse in Grandview, Texas, US",Luxury Treehouse Couples Getaway w/ Peaceful V...,Treehouse,Grandview,"Texas, US",Jun,232.00,4.99,222.0

In [62]:
airbnb[[
    "Title",
    "Detail",
    "BnB_Type",
    "City",
    "Country",
    "Month",
    "Price(in dollar)",
    "Rating",
    "Reviews"
]].isnull().sum()

Title                 0
Detail                0
BnB_Type              0
City                  0
Country             251
Month                 0
Price(in dollar)      0
Rating               22
Reviews              22
dtype: int64

In [63]:
airbnb[
    airbnb[[
        "Title",
        "Detail",
        "BnB_Type",
        "City",
        "Country",
        "Month",
        "Price(in dollar)",
        "Rating",
        "Reviews"
    ]].isnull().any(axis=1)
]

,Title,Detail,BnB_Type,City,Country,Month,Price(in dollar),Rating,Reviews
18,"Treehouse in Travelers Rest, South Carolina, US",The Forestry House - A modern luxury treehouse.,Treehouse,Travelers Rest,"South Carolina, US",Aug,282.00,NaN,NaN
71,"Cabin in Tulum, Mexico",Jungle Lodge at Nahouse in Tulum,Cabin,Tulum,Mexico,Jun,109.00,NaN,NaN
98,"Guesthouse in Destin, Florida, US",New Carriage House * 1 Block to Beach * King Bed!,Guesthouse,Destin,"Florida, US",Aug,231.00,NaN,NaN
100,"Home in Bellingham, Washington, US",Bellingham A-Frame - Hot tub & Firepit,Home,Bellingham,"Washington, US",Jun,232.00,NaN,NaN
101,"Apartment in San Juan, Puerto Rico","Villa Bohème 3, 1BR with Patio",Apartment,San Juan,Puerto Rico,Jul,115.00,NaN,NaN
...,...,...,...,...,...,...,...,...,...
948,Guest suite in Lake Worth,The Garden Suite at the Historic Chateau Bleu,Guest suite,Lake Worth,None,May,141.00,4.85,82.0
949,Room in Kissimmee,Private Room in Orlando/Kissimmee (2Twins) T1,Room,Kissimmee,None,May,43.00,4.90,300.0
950,Guesthouse in San Antonio,Casa Alexander,Guesthouse,San Antonio,None,May,73.00,4.92,282.0
951,Apartment in Englewood,BEACH FRONT Unit w/ Pool Sandy Toe's # 5,Apartment,Englewood,None,May,233.00,4.96,318.0
952,Room in Long Beach,Across the Street from Beach Getaway/Near Conv...,Room,Long Beach,None,May,106.00,4.85,97.0

In [64]:
# Remove rows with missing values in Country, Rating, or Reviews
airbnb = airbnb.dropna(subset=["Country", "Rating", "Reviews"])

# Reset the index
airbnb.reset_index(drop=True, inplace=True)

# Check the result
airbnb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 682 entries, 0 to 681
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Title             682 non-null    object
 1   Detail            682 non-null    object
 2   BnB_Type          682 non-null    object
 3   City              682 non-null    object
 4   Country           682 non-null    object
 5   Month             682 non-null    object
 6   Price(in dollar)  682 non-null    object
 7   Rating            682 non-null    float64
 8   Reviews           682 non-null    float64
dtypes: float64(2), object(7)
memory usage: 48.1+ KB

In [65]:
import pandas as pd

# Replace blank strings with NaN
airbnb[["Country", "Rating", "Reviews"]] = (
    airbnb[["Country", "Rating", "Reviews"]]
    .replace(r'^\s*$', pd.NA, regex=True)
)

# Remove rows with missing values
airbnb = airbnb.dropna(subset=["Country", "Rating", "Reviews"])

# Reset the index
airbnb.reset_index(drop=True, inplace=True)

In [66]:
airbnb[["Country", "Rating", "Reviews"]].isnull().sum()

Country    0
Rating     0
Reviews    0
dtype: int64

In [67]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

display(airbnb)

,Title,Detail,BnB_Type,City,Country,Month,Price(in dollar),Rating,Reviews
0,"Chalet in Skykomish, Washington, US",Sky Haus - A-Frame Cabin,Chalet,Skykomish,"Washington, US",Jun,306.00,4.85,531.0
1,"Cabin in Hancock, New York, US",The Catskill A-Frame - Mid-Century Modern Cabin,Cabin,Hancock,"New York, US",Jun,485.00,4.77,146.0
2,"Cabin in West Farmington, Ohio, US",The Triangle: A-Frame Cabin for your city retreat,Cabin,West Farmington,"Ohio, US",Jul,119.00,4.91,515.0
3,"Home in Blue Ridge, Georgia, US",*Summer Sizzle* 5 Min to Blue Ridge* Pets* Hot...,Home,Blue Ridge,"Georgia, US",Jun,192.00,4.94,88.0
4,"Treehouse in Grandview, Texas, US",Luxury Treehouse Couples Getaway w/ Peaceful V...,Treehouse,Grandview,"Texas, US",Jun,232.00,4.99,222.0
5,"Tiny home in Puerto Escondido, Mexico",Casa Tiny near Casa Wabi,Tiny home,Puerto Escondido,Mexico,Jun,261.00,4.84,555.0
6,"Home in Saco, Maine, US",The Beach House. Oceanfront & Sunrise Views!,Home,Saco,"Maine, US",Jun,607.00,4.64,90.0
7,"Chalet in Grand Étang, Canada",• Cedar Peak • 2 Bedroom Barrier-Free Chalet,Chalet,Grand Étang,Canada,Jun,381.00,5.00,48.0
8,"Room in Mexico City, Mexico","Room in apartment, traditional neighborhood",Room,Mexico City,Mexico,Jul,29.00,4.84,58.0
9,"Tiny home in Sandy Valley, Nevada, US",Peacock Tiny House near Las Vegas,Tiny home,Sandy Valley,"Nevada, US",Jun,154.00,4.92,744.0
10,"Guest suite in Huntsville, Canada",Hidden Valley’s Guest Suite - explore nature,Guest suite,Huntsville,Canada,Sep,207.00,4.97,265.0
11,"Cabin in Nelson, Canada",Downey Family Cabin. Barrel Sauna Included!,Cabin,Nelson,Canada,Jun,162.00,4.99,226.0
12,"Dome in Joshua Tree, California, US",Dome in the Desert in Joshua Tree,Dome,Joshua Tree,"California, US",Jun,268.00,4.94,944.0
13,"Barn in Vero Beach, Florida, US",Private Barn Studio at Pura Vida Florida Farm,Barn,Vero Beach,"Florida, US",Sep,111.00,4.95,417.0
14,"Tiny home in Bolton, Vermont, US",Cozy Tiny House Cabin between Burlington and S...,Tiny home,Bolton,"Vermont, US",Jun,174.00,4.97,372.0
15,"Cabin in Ucluelet, Canada",Peace Cabin - private waterfront forest retreat,Cabin,Ucluelet,Canada,Sep,497.00,4.99,69.0
16,"Barn in Essex, Canada",14th Homestead Barn Loft,Barn,Essex,Canada,Jun,163.00,4.90,289.0
17,"Apartment in Bacalar, Mexico","Lagoon Front Hut: Daily Cleaning, Bikes & Kayaks!",Apartment,Bacalar,Mexico,Jun,141.00,4.89,633.0
18,"Farm stay in Del Norte County, California, US",Underground Hobbit Hole @ Sustainable Ecovillage,Farm stay,Del Norte County,"California, US",Jun,89.00,4.54,195.0
19,"Treehouse in San Carlos, Costa Rica",Rainforest Tree House with Hot Springs,Treehouse,San Carlos,Costa Rica,Aug,132.00,4.84,763.0
20,"Treehouse in Frazeysburg, Ohio, US",Tullihas in the Trees Off-Grid Treehouse,Treehouse,Frazeysburg,"Ohio, US",Jun,143.00,4.98,181.0
21,"Cabin in Rodney, Canada",SECLUDED LAKESIDE CABIN,Cabin,Rodney,Canada,Jul,463.00,4.99,172.0
22,"Room in La Habana, Cuba",Fauria Colonial House (Room 3),Room,La Habana,Cuba,Jun,29.00,4.92,75.0
23,"Dome in Terlingua, Texas, US",Domeland: Off-grid Adobe Dome near Big Bend,Dome,Terlingua,"Texas, US",Jul,136.00,4.95,863.0
24,"Home in Port Angeles, Washington, US",Lake Sutherland Waterfront Cabin w/ Expansive ...,Home,Port Angeles,"Washington, US",Sep,688.00,4.82,83.0
25,"Treehouse in Fredericksburg, Texas, US",Luxury Tree House X Magical Romantic Forest! P...,Treehouse,Fredericksburg,"Texas, US",Jun,658.00,4.91,142.0
26,"Cottage in Harcourt, Canada",Scandinavian-Inspired Tiny Home Experience,Cottage,Harcourt,Canada,Sep,392.00,4.98,95.0
27,"Tiny home in Medellín, Colombia",Tiny House Cubo Nube Santa Elena 40 min. Medel...,Tiny home,Medellín,Colombia,Jun,67.00,4.95,197.0
28,"Cabin in Medellín, Colombia",Chalet Boutique Saltamontes Santa Elena,Cabin,Medellín,Colombia,Jun,51.00,4.94,232.0
29,"Cabin in Bryson City, North Carolina, US",Secluded View! A-Frame Hot Tub and Fire Pit,Cabin,Bryson City,"North Carolina, US",Jun,354.00,4.95,20.0
30,"Place to stay in Retiro, Colombia",★ BubbleSky Glamping ★ One Night Under Stars ★3,Place to stay,Retiro,Colombia,Jun,107.00,4.90,154.0
31,"Cabin in Bluefields, Jamaica",Cozy Oceanview Cabin,Cabin,Bluefields,Jamaica,Jul,102.00,4.88,76.0
32,"Hut in Bavaro, Dominican Republic",Hut #1 Romantic Luxury Beachfront,Hut,Bavaro,Dominican Republic,Jul,171.00,4.89,377.0
33,"Treehouse in Marion, North Carolina, US",Treehouse w/Breathtaking Views+HotTub+Hiking+F...,Treehouse,Marion,"North Carolina, US",Aug,286.00,5.00,21.0
34,"Dome in Sandgate, Vermont, US",“Whimsical Stone Abode” - Boston Magazine,Dome,Sandgate,"Vermont, US",Jun,301.00,5.00,244.0
35,"Condo in Puerto Vallarta, Mexico",Buddha Loft in Romantic Zone of Puerto Vallarta,Condo,Puerto Vallarta,Mexico,Jul,112.00,4.85,175.0
36,"Cabin in Sanbornton, New Hampshire, US",The G Frame...an offGrid Cabin + woodstove sauna,Cabin,Sanbornton,"New Hampshire, US",Jun,169.00,4.96,395.0
37,"Room in La Habana, Cuba",Casa Blanca B&B with beautiful terrace &sea views,Room,La Habana,Cuba,Sep,43.00,4.82,359.0
38,"Home in Moss Beach, California, US",Walk to the Beach from this Ocean Front Home,Home,Moss Beach,"California, US",Jun,"1,463.00",4.94,149.0
39,"Cottage in Wheatley, Canada","Cozy Modern Beach House w/ Pool, Hot Tub & More!",Cottage,Wheatley,Canada,Jun,764.00,4.74,19.0
40,"Cabin in Topanga, California, US","Crystal Cabin, Restored Vintage Lodge in Topan...",Cabin,Topanga,"California, US",Jun,225.00,4.94,209.0
41,"Chalet in Cajicá, Colombia",Casa Anís,Chalet,Cajicá,Colombia,Jun,40.00,4.96,202.0
42,"Cabin in Center Conway, New Hampshire, US",Warm Pine A-frame Nestled In The Trees!,Cabin,Center Conway,"New Hampshire, US",Jul,287.00,4.79,536.0
43,"Cottage in Renous, Canada",Hambrook Point Cottage “Homestead”,Cottage,Renous,Canada,Jun,93.00,4.87,360.0
44,"Tiny home in Huntsville, Missouri, US",O’s Barn Cabin,Tiny home,Huntsville,"Missouri, US",Jul,118.00,4.94,296.0
45,"Tiny home in Castleton, Canada","Artsy ""Glamping"" experience",Tiny home,Castleton,Canada,Jul,138.00,4.91,278.0
46,"Cottage in Bodega Bay, California, US","Seamist Beach Cottage, Private Beach & Ocean v...",Cottage,Bodega Bay,"California, US",Aug,670.00,4.70,256.0
47,"Cabin in Rocky View County, Canada",100+ Year old Rustic Log Cabin near Ghost Lake,Cabin,Rocky View County,Canada,Aug,135.00,4.83,459.0
48,"Houseboat in Low, Canada",The Dragon + Private Island,Houseboat,Low,Canada,Jun,178.00,4.87,61.0
49,"Guesthouse in Key Largo, Florida, US","Private Cottage, enjoy beach, sunsets & fishing.",Guesthouse,Key Largo,"Florida, US",Jul,218.00,4.89,314.0
50,"Condo in Malibu, California, US","Malibu, Carbon Beach - Suite Seven",Condo,Malibu,"California, US",Jun,898.00,4.86,311.0
51,"Cottage in Petit-Tracadie, Canada",Waterfront Cottage #1 /Waterfront cottage,Cottage,Petit-Tracadie,Canada,Jun,144.00,4.92,267.0
52,"Cabin in Jarratt, Virginia, US",Harrell’s Cabin,Cabin,Jarratt,"Virginia, US",Jun,125.00,4.82,612.0
53,"Cabin in El Peñol, Colombia",6 Ibuku Big Cabin by Lake Jacuzzi Kayak,Cabin,El Peñol,Colombia,Jun,220.00,4.93,46.0
54,"Guest suite in North Vancouver, Canada",The Brite House - Oceanfront Sojourn,Guest suite,North Vancouver,Canada,Jun,305.00,4.87,319.0
55,"Home in Shirley, Canada",♨ Cedar Coast Lodge - Coastal retreat w/ HOT TUB,Home,Shirley,Canada,Jun,480.00,4.82,125.0
56,"Apartment in Miami, Florida, US","LUXURY 5★s ICON BRICKELL CONDO@47TH, GYM/POOL",Apartment,Miami,"Florida, US",Jun,398.00,4.89,605.0
57,"Room in Kansas City, Missouri, US",Mansion in the Park - garden view queen en suite,Room,Kansas City,"Missouri, US",Jun,148.00,4.99,93.0
58,"Dome in Lac-Supérieur, Canada",Dome L'Albatros | Private Spa | BBQ Zone,Dome,Lac-Supérieur,Canada,Jul,322.00,4.86,196.0
59,"Chalet in Saint-Damien, Canada",The Majesta ! Incredible Sunset !,Chalet,Saint-Damien,Canada,Jun,315.00,5.00,11.0
60,"Home in Tulum, Mexico","Heaven Lodge, entire house surrounded by nature",Home,Tulum,Mexico,Jun,128.00,4.86,155.0
61,"Apartment in Tulum, Mexico",☆King Bed Apartment☆ Suk-Ha ☆ La Veleta,Apartment,Tulum,Mexico,Jun,55.00,4.60,73.0
62,"Chalet in Durham, Canada",Newly-Constructed Riverfront Chalet,Chalet,Durham,Canada,Jun,360.00,4.97,95.0
63,"Tent in Island Park, Idaho, US","Yellowstone Luxury Tent; sleeps 3, 1 king +1 f...",Tent,Island Park,"Idaho, US",Jun,224.00,5.00,31.0
64,"Cabin in Arrowbear Lake, California, US",A-Frame Apogee | Hot Tub · Epic Views · Swing Set,Cabin,Arrowbear Lake,"California, US",Jun,227.00,4.96,166.0
65,"Home in Borinquen, Puerto Rico",The Nest at Crash Boat. Only waterfront on Beach,Home,Borinquen,Puerto Rico,Aug,363.00,4.90,143.0
66,"Cottage in Wasaga Beach, Canada",Cozy Riverfront Cottage Retreat with Dock,Cottage,Wasaga Beach,Canada,Jun,232.00,4.84,55.0
67,"Tiny home in Blockhouse, Canada",The Ruby -A Rustic Red Ark tiny home,Tiny home,Blockhouse,Canada,Jun,81.00,4.98,43.0
68,"Guesthouse in Peachland, Canada",Romantic lakefront estate with lake view & deck,Guesthouse,Peachland,Canada,Jun,271.00,5.00,311.0
69,"Cabin in Shaftsbury, Vermont, US",The Vermont Dream Cabin on 70 Acres,Cabin,Shaftsbury,"Vermont, US",Jun,219.00,4.89,136.0
70,"Dome in Windermere, Canada",Cougar Dome at Winderdome Resort!,Dome,Windermere,Canada,Aug,335.00,5.00,16.0
71,"Condo in Myrtle Beach, South Carolina, US",Cool Clean Condo with Brilliant Oceanfront View,Condo,Myrtle Beach,"South Carolina, US",Jun,261.00,4.58,108.0
72,"Hotel room in Laguna Beach, California, US",Beachfront Laguna Beach Magnificent Oceanviews 26,Hotel room,Laguna Beach,"California, US",Jun,287.00,4.38,396.0
73,"Apartment in Playa del Carmen, Mexico","Su mejor opción en Playa del Carmen, a pasos d...",Apartment,Playa del Carmen,Mexico,Jun,89.00,4.78,231.0
74,"Tiny home in Maynooth, Canada",Cozy Cabin #2 - private cabin in the wilderness!,Tiny home,Maynooth,Canada,Jun,71.00,4.89,90.0
75,"Guesthouse in Cabo Rojo, Puerto Rico",Villa Vista Puerto,Guesthouse,Cabo Rojo,Puerto Rico,Jun,138.00,4.86,493.0
76,"Tiny home in Canning, Canada",Split View Two,Tiny home,Canning,Canada,Aug,134.00,4.95,81.0
77,"Cottage in Luquillo, Puerto Rico",The Sugar Shack a unique cabin in the Rainforest,Cottage,Luquillo,Puerto Rico,Sep,75.00,4.92,447.0
78,"Condo in Lahaina, Hawaii, US",Noelani-My Perfect Stays Special: Jun 9-16 $189,Condo,Lahaina,"Hawaii, US",Jun,302.00,4.82,71.0
79,"Condo in Hollywood, Florida, US",Amazing Hyde One-bedroom apartment on the Beach,Condo,Hollywood,"Florida, US",Jun,248.00,4.56,62.0
80,"Cabin in Naples, New York, US",East hill cabins #1,Cabin,Naples,"New York, US",Jun,91.00,4.82,334.0
81,"Campsite in Nemaiah Valley, Canada",Sunset Wilderness Camp,Campsite,Nemaiah Valley,Canada,Jun,34.00,4.00,3.0
82,"Loft in The Blue Mountains, Canada",Chateau Ridge Chalet w/ Mountain View,Loft,The Blue Mountains,Canada,Jun,154.00,4.84,95.0
83,"Loft in The Blue Mountains, Canada",Cozy Blue Mountain Retreat @!@Spring Rates@!@,Loft,The Blue Mountains,Canada,Jun,118.00,4.72,365.0
84,"Room in Mexico City, Mexico",5 min to Airport with Terrace in a Safe area !,Room,Mexico City,Mexico,Jun,31.00,4.85,227.0
85,"Tiny home in Komoka, Canada",The Cabin at Fernwood Hills,Tiny home,Komoka,Canada,Jun,112.00,4.90,597.0
86,"Place to stay in Punta Cana, Dominican Republic",Hut #3 Romantic Luxury on the sand,Place to stay,Punta Cana,Dominican Republic,Jul,132.00,4.86,29.0
87,"Home in Hilbert, Wisconsin, US",State Park A-Frame with Hiking Trails & Arcade,Home,Hilbert,"Wisconsin, US",Jun,239.00,4.97,29.0
88,"Dome in Whittier, North Carolina, US",Luxury Dome w/ Hot Tub & Mountain View,Dome,Whittier,"North Carolina, US",Aug,291.00,5.00,11.0
89,"Place to stay in Punta Cana, Dominican Republic",Hut #3 Romantic Luxury on the sand,Place to stay,Punta Cana,Dominican Republic,Jul,132.00,4.86,29.0
90,"Home in Hilbert, Wisconsin, US",State Park A-Frame with Hiking Trails & Arcade,Home,Hilbert,"Wisconsin, US",Jun,239.00,4.97,29.0
91,"Home in Puntarenas Province, Costa Rica",House with pool in the heights of Santa Teresa,Home,Puntarenas Province,Costa Rica,Jun,230.00,5.00,6.0
92,"Loft in Monteverde, Costa Rica",Kapetsowa Container Loft near Monteverde Reserve,Loft,Monteverde,Costa Rica,Sep,159.00,4.87,396.0
93,"Nature lodge in Quesada, Costa Rica",Cabin Over a water fall,Nature lodge,Quesada,Costa Rica,Jun,82.00,4.94,133.0
94,"Boat in Key West, Florida, US",Cozy Houseboat “Wild One”,Boat,Key West,"Florida, US",Jun,233.00,5.00,4.0
95,"Cabin in Zapotal, Costa Rica",Pipe’s Lodge,Cabin,Zapotal,Costa Rica,Jun,51.00,4.87,31.0
96,"Tiny home in Playa Hermosa, Costa Rica",Beachfront Bungalow with private hydromassage ...,Tiny home,Playa Hermosa,Costa Rica,Jul,162.00,4.95,149.0
97,"Loft in Mexico City, Mexico",Loft Boutique Cd de México Mountain view 🏔,Loft,Mexico City,Mexico,Jul,57.00,4.84,155.0
98,"Cabin in Gold Bar, Washington, US",New lux cabin w/mount index view,Cabin,Gold Bar,"Washington, US",Jun,253.00,4.86,7.0
99,"Home in Malibu, California, US",Guesthouse Great Ocean & Mountain Views near B...,Home,Malibu,"California, US",Jul,468.00,4.87,694.0
100,"Tiny home in Orlando, Florida, US",The Little Tree House at Country Club of Orlando,Tiny home,Orlando,"Florida, US",Jul,127.00,4.98,604.0
101,"Boat in Marathon, Florida, US",Paradise awaits on this cozy houseboat!,Boat,Marathon,"Florida, US",Jul,276.00,4.77,98.0
102,"Hut in Uvero Alto - Bavaro - Punta Cana, Domin...",Hut #2 Romantic Luxury on the sand,Hut,Uvero Alto - Bavaro - Punta Cana,Dominican Republic,Aug,186.00,4.94,226.0
103,"Loft in Mazamitla, Mexico",Loft ALAMO /El Refugio Cabañas Mazamitla,Loft,Mazamitla,Mexico,Jun,58.00,4.44,146.0
104,"Hut in Uvero Alto - Bavaro - Punta Cana, Domin...",Hut #2 Romantic Luxury on the sand,Hut,Uvero Alto - Bavaro - Punta Cana,Dominican Republic,Aug,186.00,4.94,226.0
105,"Apartment in Punta Cana, Dominican Republic",Pool View Beach Residence / Private Beach Access,Apartment,Punta Cana,Dominican Republic,Jun,37.00,4.71,156.0
106,"Boat in Stuart, Florida, US",Modern Houseboat On the water,Boat,Stuart,"Florida, US",Aug,173.00,4.97,264.0
107,"Apartment in Playa del Carmen, Mexico",BoHo lofts & studios new modern w/ ocean-view ...,Apartment,Playa del Carmen,Mexico,Jun,38.00,4.59,183.0
108,"Condo in Miami Beach, Florida, US",Oceanfront 14th Floor Brand New Beachfront Flat,Condo,Miami Beach,"Florida, US",Jun,302.00,4.85,646.0
109,"Earthen home in Weaverville, North Carolina, US",Hobbithenge,Earthen home,Weaverville,"North Carolina, US",Jun,142.00,4.83,304.0
110,"Shipping container in Playa Hermosa, Costa Rica",Beachfront Bungalow w/ private hydromassage po...,Shipping container,Playa Hermosa,Costa Rica,Jun,147.00,4.90,68.0
111,"Cabin in Marion, North Carolina, US","Luxury Treehouse, Romantic, Views, Hike-Waterfall",Cabin,Marion,"North Carolina, US",Jul,228.00,5.00,18.0
112,"Camper/RV in Half Moon Bay, California, US",Quiet and Private Retreat in a 1967 Airstream ...,Camper/RV,Half Moon Bay,"California, US",Jun,220.00,4.93,347.0
113,"Dome in Hiawassee, Georgia, US",Tiny Dome River Glamping Experience,Dome,Hiawassee,"Georgia, US",Jun,143.00,4.86,289.0
114,"Apartment in San José, Costa Rica",New Boho Sabana Apartment Close to Airports w/ AC,Apartment,San José,Costa Rica,Jun,89.00,4.85,81.0
115,"Condo in Rosarito, Mexico",Elegant Ocean Front Condo! Rosarito Beach !WOW!!,Condo,Rosarito,Mexico,Jun,171.00,4.81,245.0
116,"Condo in Atlantic City, New Jersey, US",Highest Reviewed - Ocean Front + Free Parking!,Condo,Atlantic City,"New Jersey, US",Jun,170.00,4.85,278.0
117,"Cabin in Santa Marta, Colombia",The Dawn of Annapurna Cabin,Cabin,Santa Marta,Colombia,Jul,61.00,4.87,188.0
118,"Home in Cabo San Lucas, Mexico","Cabo Center,Ocean view Great price!",Home,Cabo San Lucas,Mexico,Jun,55.00,4.94,615.0
119,"Home in Kawartha Lakes, Canada",nortehaus - Nordic and Japanese inspired escape,Home,Kawartha Lakes,Canada,Jun,402.00,5.00,24.0
120,"Loft in Cholula, Mexico",Architect's Loft in Cholula,Loft,Cholula,Mexico,Jun,32.00,4.81,202.0
121,"Cabin in Jacó, Costa Rica",Jungle house 3km to Jaco beach & town center,Cabin,Jacó,Costa Rica,Jun,76.00,4.84,153.0
122,"Tiny home in Malibu, California, US","Malibu Charming GH, Mins Drive to Beach & Hike",Tiny home,Malibu,"California, US",Jul,332.00,4.78,558.0
123,"Apartment in Orlando, Florida, US",Studio near Disney,Apartment,Orlando,"Florida, US",Jun,80.00,4.43,132.0
124,"Treehouse in Río Grande, Puerto Rico",Charming Treehouse with Pool,Treehouse,Río Grande,Puerto Rico,Sep,217.00,5.00,172.0
125,"Loft in Mazatlán, Mexico",Oceanfront loft,Loft,Mazatlán,Mexico,Jun,100.00,4.92,177.0
126,"Apartment in Cancún, Mexico",Majestic Ocean Front Terrace II,Apartment,Cancún,Mexico,Jul,57.00,4.83,240.0
127,"Home in Real Montecassino, Mexico",New! Bamboo Bosque Mio (Stars & Campfires),Home,Real Montecassino,Mexico,Jun,113.00,4.82,56.0
128,"Cottage in Huntsville, Canada","Cabin for 2 w/ Hot Tub, Muskoka Romantic Getaway",Cottage,Huntsville,Canada,Jun,335.00,4.97,179.0
129,"Apartment in La Habana, Cuba",Old Havana+Cuban Style Place+Roof Top+WiFi,Apartment,La Habana,Cuba,Jun,57.00,4.48,161.0
130,"Home in Vero Beach, Florida, US","Heated Pool, Putt Putt Golf",Home,Vero Beach,"Florida, US",Jun,468.00,4.93,15.0
131,"Room in Cuauhtémoc, , Mexico",Guest Suite in Historic Architecture Home,Room,Cuauhtémoc,", Mexico",Jun,55.00,4.82,443.0
132,"Condo in Kaunakakai, Hawaii, US",$87 a night Molokai Escape Condo,Condo,Kaunakakai,"Hawaii, US",Jun,101.00,4.76,337.0
133,"Treehouse in Atenas, Costa Rica",Treehouse on a Coffee Farm with Ocean View,Treehouse,Atenas,Costa Rica,Jun,74.00,5.00,13.0
134,"Apartment in Tulum, Mexico",Design Casa Patchouli with private pool and lo...,Apartment,Tulum,Mexico,Jun,283.00,4.98,80.0
135,"Shipping container in Jauca, Puerto Rico",Pequeño espacio Romántico piscina y muelle pri...,Shipping container,Jauca,Puerto Rico,Jul,220.00,4.95,139.0
136,"Tiny home in Peachland, Canada",Haven in the Woods- tiny home WiFi & solar power,Tiny home,Peachland,Canada,Jun,76.00,5.00,4.0
137,Shipping container in Puerto Viejo de Talamanc...,Mimosa Y - Beautiful Unique Container Home w' ...,Shipping container,Puerto Viejo de Talamanca,Costa Rica,Jun,90.00,4.85,54.0
138,Shipping container in Puerto Viejo de Talamanc...,Mimosa Y - Beautiful Unique Container Home w' ...,Shipping container,Puerto Viejo de Talamanca,Costa Rica,Jun,90.00,4.85,54.0
139,"Apartment in Acapulco, Mexico",COMFORTABLE BEACH DEPA OVERLOOKING THE SEA,Apartment,Acapulco,Mexico,Jun,42.00,4.57,226.0
140,"Yurt in Airville, Pennsylvania, US",Waterfront Glamping Muddy Creek PA,Yurt,Airville,"Pennsylvania, US",Jun,102.00,4.95,22.0
141,"Boutique hotel in San Juan, Puerto Rico",2 Pools on property | Walk to the beach | Rosa...,Boutique hotel,San Juan,Puerto Rico,Jul,164.00,4.81,212.0
142,"Room in Acapulco, Mexico",Love nest when singing of the Sea!,Room,Acapulco,Mexico,Jun,41.00,4.68,266.0
143,"Home in Pinilla, Costa Rica",Casa La Paz vistas al mar @ Pinilla Highlands,Home,Pinilla,Costa Rica,Jul,146.00,4.86,7.0
144,"Farm stay in Siler City, North Carolina, US",Lovely farm cabin experience,Farm stay,Siler City,"North Carolina, US",Jun,114.00,5.00,5.0
145,"Tiny home in Horning's Mills, Canada",Pine River Bunkies: Heron’s Landing Off Grid C...,Tiny home,Horning's Mills,Canada,Jun,120.00,4.89,103.0
146,"Camper/RV in Ashford, Washington, US",The Alpine Airstream at Mt. Rainier with Hot Tub,Camper/RV,Ashford,"Washington, US",Jun,286.00,5.00,11.0
147,"Bungalow in Newport Beach, California, US","Surf, Sand & Sunsets - Goldenrod CdM BEACH STUDIO",Bungalow,Newport Beach,"California, US",Jul,229.00,4.80,289.0
148,"Hut in Guarne, Colombia",Refugio LOS PAPIROS,Hut,Guarne,Colombia,Jun,18.00,4.89,66.0
149,"Room in Acapulco, Mexico",Beach crab.,Room,Acapulco,Mexico,Jun,43.00,4.74,270.0
150,"Cabin in Fennville, Michigan, US",Fire & Water | Rejuvenating Stay on the Riverbend,Cabin,Fennville,"Michigan, US",Jun,743.00,4.83,175.0
151,"Home in Tamanique, El Salvador",Black rose -Right house-,Home,Tamanique,El Salvador,Jun,243.00,4.63,275.0

In [68]:
# Rename columns
airbnb.rename(columns={
    "Title": "Property Name",
    "Detail": "Amenities",
    "BnB_Type": "Property Type",
    "Reviews": "Number of Reviews"
}, inplace=True)

# Check the updated columns
airbnb.columns.tolist()

['Property Name',
 'Amenities',
 'Property Type',
 'City',
 'Country',
 'Month',
 'Price(in dollar)',
 'Rating',
 'Number of Reviews']

In [69]:
display(airbnb.head())

,Property Name,Amenities,Property Type,City,Country,Month,Price(in dollar),Rating,Number of Reviews
0,"Chalet in Skykomish, Washington, US",Sky Haus - A-Frame Cabin,Chalet,Skykomish,"Washington, US",Jun,306.00,4.85,531.0
1,"Cabin in Hancock, New York, US",The Catskill A-Frame - Mid-Century Modern Cabin,Cabin,Hancock,"New York, US",Jun,485.00,4.77,146.0
2,"Cabin in West Farmington, Ohio, US",The Triangle: A-Frame Cabin for your city retreat,Cabin,West Farmington,"Ohio, US",Jul,119.00,4.91,515.0
3,"Home in Blue Ridge, Georgia, US",*Summer Sizzle* 5 Min to Blue Ridge* Pets* Hot...,Home,Blue Ridge,"Georgia, US",Jun,192.00,4.94,88.0
4,"Treehouse in Grandview, Texas, US",Luxury Treehouse Couples Getaway w/ Peaceful V...,Treehouse,Grandview,"Texas, US",Jun,232.00,4.99,222.0

In [74]:
airbnb = airbnb.sort_values(
    by=["Rating", "Number of Reviews"],
    ascending=[False, False]
)

airbnb["Rating Rank"] = range(1, len(airbnb) + 1)

airbnb.head(20)

,Property Name,Amenities,Property Type,City,Country,Month,Price(in dollar),Rating,Number of Reviews,Rating Rank,Price Rank,Rating Category
68,"Guesthouse in Peachland, Canada",Romantic lakefront estate with lake view & deck,Guesthouse,Peachland,Canada,Jun,271.00,5.0,311.0,1,132,Excellent
34,"Dome in Sandgate, Vermont, US",“Whimsical Stone Abode” - Boston Magazine,Dome,Sandgate,"Vermont, US",Jun,301.00,5.0,244.0,2,119,Excellent
124,"Treehouse in Río Grande, Puerto Rico",Charming Treehouse with Pool,Treehouse,Río Grande,Puerto Rico,Sep,217.00,5.0,172.0,3,173,Excellent
621,"Villa in Seririt, Indonesia",Wake up to the Sea of Bali: Beachfront luxury ...,Villa,Seririt,Indonesia,Oct,194.00,5.0,139.0,4,187,Excellent
633,"Villa in Seririt, Indonesia",Wake up to the Sea of Bali: Beachfront luxury ...,Villa,Seririt,Indonesia,Oct,194.00,5.0,139.0,5,187,Excellent
651,"Villa in Seririt, Indonesia",Wake up to the Sea of Bali: Beachfront luxury ...,Villa,Seririt,Indonesia,Oct,194.00,5.0,139.0,6,187,Excellent
537,"Villa in Kathu, Thailand",Tiny Poolvilla in the heart of Phuket,Villa,Kathu,Thailand,Jul,119.00,5.0,98.0,7,248,Excellent
541,"Villa in Kathu, Thailand",Tiny Poolvilla in the heart of Phuket,Villa,Kathu,Thailand,Jul,119.00,5.0,98.0,8,248,Excellent
271,"Farm stay in Girvan, UK",Secluded Hand crafted log cabin,Farm stay,Girvan,UK,Jun,139.00,5.0,68.0,9,229,Excellent
360,"Cabin in Millbrook, UK",Romantic Ocean View Couples Retreat Cornwall,Cabin,Millbrook,UK,Jun,357.00,5.0,61.0,10,100,Excellent
370,"Cabin in Millbrook, UK",Romantic Ocean View Couples Retreat Cornwall,Cabin,Millbrook,UK,Jun,357.00,5.0,61.0,11,100,Excellent
490,"Treehouse in Klungkung, Indonesia",Cliffside Bamboo Treehouse - Private Pool & View,Treehouse,Klungkung,Indonesia,Nov,484.00,5.0,59.0,12,68,Excellent
364,"Tiny home in Muldenhammer, Germany",Hascherle Hitt,Tiny home,Muldenhammer,Germany,Jun,86.00,5.0,57.0,13,16,Excellent
377,"Tiny home in Muldenhammer, Germany",Hascherle Hitt,Tiny home,Muldenhammer,Germany,Jun,86.00,5.0,57.0,14,16,Excellent
7,"Chalet in Grand Étang, Canada",• Cedar Peak • 2 Bedroom Barrier-Free Chalet,Chalet,Grand Étang,Canada,Jun,381.00,5.0,48.0,15,93,Excellent
302,"Condo in Kremasti, Greece",L & C Deluxe Apartment - luxury and comfort,Condo,Kremasti,Greece,Jun,136.00,5.0,45.0,16,232,Excellent
173,"Cabin in Mineral Bluff, Georgia, US",Scenic Solitude-Amazing Mountain views on 5 acres,Cabin,Mineral Bluff,"Georgia, US",Jun,302.00,5.0,44.0,17,118,Excellent
464,"Room in Kecamatan Denpasar Selatan, Indonesia",Poolside room in large villa. 5 minutes to beach.,Room,Kecamatan Denpasar Selatan,Indonesia,Aug,34.00,5.0,37.0,18,104,Excellent
523,"Tiny home in Concepcion, Philippines",Tiny House by The Modern Escape,Tiny home,Concepcion,Philippines,Jul,128.00,5.0,32.0,19,240,Excellent
63,"Tent in Island Park, Idaho, US","Yellowstone Luxury Tent; sleeps 3, 1 king +1 f...",Tent,Island Park,"Idaho, US",Jun,224.00,5.0,31.0,20,165,Excellent

In [75]:
# Create Price Rank (Highest Price = Rank 1)
airbnb["Price Rank"] = airbnb["Price(in dollar)"].rank(
    ascending=False,
    method="dense"
).astype(int)

# Sort from highest price to lowest
airbnb = airbnb.sort_values(
    by="Price(in dollar)",
    ascending=False
)

# Display the result
airbnb.head(20)

,Property Name,Amenities,Property Type,City,Country,Month,Price(in dollar),Rating,Number of Reviews,Rating Rank,Price Rank,Rating Category
170,"Farm stay in Saint Marys, Canada",Cozy Farm Stay Getaway,Farm stay,Saint Marys,Canada,Jun,99.00,4.86,183.0,385,1,Very Good
184,"Farm stay in Saint Marys, Canada",Cozy Farm Stay Getaway,Farm stay,Saint Marys,Canada,Jun,99.00,4.86,183.0,386,1,Very Good
207,"Guesthouse in Naalehu, Hawaii, US",The Ohana,Guesthouse,Naalehu,"Hawaii, US",Jun,99.00,4.86,182.0,387,1,Very Good
211,"Guesthouse in Naalehu, Hawaii, US",The Ohana,Guesthouse,Naalehu,"Hawaii, US",Jun,99.00,4.86,182.0,388,1,Very Good
477,"Villa in Koh Yao Noi, Thailand","Eagles Nest, Luxury Villa, Koh Yao Noi",Villa,Koh Yao Noi,Thailand,Jun,986.00,4.95,43.0,175,2,Excellent
659,"Loft in Jelutong, Malaysia",#Maritime*3*The Rhythm of the Sea @ 日出无敌全海景,Loft,Jelutong,Malaysia,Jun,98.00,4.56,93.0,649,3,Good
320,"Treehouse in Fountana, Greece",Nasos' Treehouse,Treehouse,Fountana,Greece,Jun,98.00,4.91,32.0,279,3,Excellent
415,"Cabin in Rosenthal-Bielatal, Germany",Mountain hut in the Elbe sandstone with log ca...,Cabin,Rosenthal-Bielatal,Germany,Jun,98.00,4.78,169.0,544,3,Very Good
405,"Treehouse in Verson, France",2 Cabins perched above a pond!,Treehouse,Verson,France,Jun,98.00,4.94,530.0,185,3,Excellent
310,"Treehouse in Fountana, Greece",Nasos' Treehouse,Treehouse,Fountana,Greece,Jun,98.00,4.81,98.0,501,3,Very Good
391,"Treehouse in Verson, France",2 Cabins perched above a pond!,Treehouse,Verson,France,Jun,98.00,4.91,68.0,273,3,Excellent
213,"Apartment in Carolina, Puerto Rico",Isla Verde Beach Studio {105},Apartment,Carolina,Puerto Rico,Jul,97.00,4.67,433.0,614,4,Good
471,"Villa in Thành phố Hội An, Vietnam",Private pool two bedroom villa - villa the cow,Villa,Thành phố Hội An,Vietnam,Jun,97.00,4.80,124.0,515,4,Very Good
353,"Room in Planos, Greece",Kimiro Hotel Tsilivi,Room,Planos,Greece,Jun,97.00,4.91,43.0,276,4,Excellent
480,"Villa in Langkawi, Malaysia",Alamanda Tropical Wooden Villa - Pool View,Villa,Langkawi,Malaysia,Jun,97.00,4.87,196.0,364,4,Very Good
171,"Tiny home in Mill Village, Canada",UpStream (Waterfront Cabin With Wood Stove & W...,Tiny home,Mill Village,Canada,Jun,97.00,4.87,101.0,369,4,Very Good
594,"Home in Lembang, Indonesia",Minimax House by wiandra,Home,Lembang,Indonesia,Jun,96.00,4.84,81.0,449,5,Very Good
465,"Room in Bangkok, Thailand",Ba hao Residence x MAITRI CHIT ROOM,Room,Bangkok,Thailand,Aug,96.00,4.93,431.0,210,5,Excellent
292,"Cabin in Nowy Targ, Poland",Gruszkówka 1 Cottage (7 km from Białka ),Cabin,Nowy Targ,Poland,Jun,96.00,4.98,86.0,88,5,Excellent
455,"Tiny home in Kecamatan Ubud, Indonesia",Tiny Tall Haus Ubud Getaway!,Tiny home,Kecamatan Ubud,Indonesia,Jun,95.00,4.87,104.0,368,6,Very Good

In [78]:
airbnb["Property Name"].duplicated().sum()

np.int64(145)

In [80]:
airbnb[
    airbnb.duplicated(
        subset=["Property Name", "Country"],
        keep=False
    )
].sort_values(["Property Name", "Country"])

,Property Name,Amenities,Property Type,City,Country,Month,Price(in dollar),Rating,Number of Reviews,Rating Rank,Price Rank,Rating Category
358,"Apartment in Areti, Greece",Echoes Exclusive Suite,Apartment,Areti,Greece,Jun,526.00,4.98,40.0,102,58,Excellent
368,"Apartment in Areti, Greece",Echoes Exclusive Suite,Apartment,Areti,Greece,Jun,526.00,4.98,40.0,103,58,Excellent
228,"Apartment in Cancún, Mexico",Cancun Suites (Standard Room),Apartment,Cancún,Mexico,Jul,81.00,4.47,192.0,662,21,Needs Improvement
243,"Apartment in Cancún, Mexico",1208 Beach property part ocean & pool view,Apartment,Cancún,Mexico,Jun,79.00,4.64,148.0,627,23,Good
126,"Apartment in Cancún, Mexico",Majestic Ocean Front Terrace II,Apartment,Cancún,Mexico,Jul,57.00,4.83,240.0,459,53,Very Good
158,"Apartment in Cancún, Mexico",Amazing Ocean Front II,Apartment,Cancún,Mexico,Jul,45.00,4.88,306.0,331,81,Very Good
155,"Apartment in Cancún, Mexico",Free Transportation / Premium Beach Loft 1711th,Apartment,Cancún,Mexico,Jun,138.00,5.00,15.0,32,230,Excellent
162,"Apartment in Gordonville, Pennsylvania, US",“What a wonderful world” - Modern Farmhouse,Apartment,Gordonville,"Pennsylvania, US",Jun,165.00,4.87,478.0,353,208,Very Good
176,"Apartment in Gordonville, Pennsylvania, US",“What a wonderful world” - Modern Farmhouse,Apartment,Gordonville,"Pennsylvania, US",Jun,165.00,4.87,478.0,354,208,Very Good
674,"Apartment in Kuala Lumpur, Malaysia",Admire Deluxe Marble Walls at a Highrise Resor...,Apartment,Kuala Lumpur,Malaysia,Jun,85.00,4.85,135.0,413,17,Very Good
576,"Apartment in Kuala Lumpur, Malaysia",Walk to Petronas Towers from a Stylish Apartment,Apartment,Kuala Lumpur,Malaysia,Jun,71.00,4.89,296.0,309,33,Very Good
646,"Apartment in Kuala Lumpur, Malaysia",Premier Lux Studio Large Tv Free Netflix | City,Apartment,Kuala Lumpur,Malaysia,Jun,62.00,4.90,166.0,292,47,Excellent
542,"Apartment in Kuala Lumpur, Malaysia",Instagrammable Loft Studio in EkoCheras KL,Apartment,Kuala Lumpur,Malaysia,Jul,60.00,4.94,84.0,203,50,Excellent
627,"Apartment in Kuala Lumpur, Malaysia",EXPRESSIONZ-1Bedroom-Junior-Suite-KLCC-Sky-Pool,Apartment,Kuala Lumpur,Malaysia,Jun,53.00,4.78,408.0,538,57,Very Good
639,"Apartment in Kuala Lumpur, Malaysia",EXPRESSIONZ-1Bedroom-Junior-Suite-KLCC-Sky-Pool,Apartment,Kuala Lumpur,Malaysia,Jun,53.00,4.78,408.0,539,57,Very Good
605,"Apartment in Kuala Lumpur, Malaysia",1min KLCC Twin Tower & Pavilion/Ins cottage fo...,Apartment,Kuala Lumpur,Malaysia,Jun,38.00,4.91,278.0,261,94,Excellent
164,"Apartment in Marina del Rey, California, US",Romantic Ocean Penthouse w/ panoramic marina v...,Apartment,Marina del Rey,"California, US",Jun,247.00,4.77,111.0,559,147,Very Good
181,"Apartment in Marina del Rey, California, US",Romantic Ocean Penthouse w/ panoramic marina v...,Apartment,Marina del Rey,"California, US",Jun,247.00,4.77,111.0,560,147,Very Good
551,"Apartment in Melaka, Malaysia",Yuma • Atlantis Melaka/3BR 8Pax WiFi Balcony S...,Apartment,Melaka,Malaysia,Jun,40.00,4.43,7.0,671,89,Needs Improvement
614,"Apartment in Melaka, Malaysia",B1933B/5 min drive to Jonker/Seaview/Imperio/4...,Apartment,Melaka,Malaysia,Jun,24.00,4.69,196.0,604,151,Good
652,"Apartment in Muang Pattaya, Thailand",#18 2022 Newest! Downtown Lux Fun Sea View Condo,Apartment,Muang Pattaya,Thailand,Jun,63.00,5.00,27.0,21,45,Excellent
467,"Apartment in Muang Pattaya, Thailand",[VR] 2BR High Skyline Ocean View @ Pattaya,Apartment,Muang Pattaya,Thailand,Jun,136.00,4.69,85.0,607,232,Good
564,"Apartment in PHUKET, Thailand",★Studio in Seafront Private Villa w/infinity p...,Apartment,PHUKET,Thailand,Jun,53.00,4.83,93.0,465,57,Very Good
579,"Apartment in PHUKET, Thailand",★Studio in Seafront Private Villa w/infinity p...,Apartment,PHUKET,Thailand,Jun,53.00,4.83,93.0,466,57,Very Good
589,"Apartment in PHUKET, Thailand",Studio in Beachfront Private Villa w/Infinity ...,Apartment,PHUKET,Thailand,Jun,38.00,4.88,64.0,344,94,Very Good
558,"Apartment in Phuket, Thailand","Luxury room & Sky pool, in Phuket town",Apartment,Phuket,Thailand,Jun,40.00,4.81,210.0,497,89,Very Good
574,"Apartment in Phuket, Thailand","Luxury room & Sky pool, in Phuket town",Apartment,Phuket,Thailand,Jun,40.00,4.81,210.0,498,89,Very Good
568,"Apartment in Phuket, Thailand",Cozy Place near Shopping Center,Apartment,Phuket,Thailand,Jun,35.00,4.96,237.0,136,102,Excellent
73,"Apartment in Playa del Carmen, Mexico","Su mejor opción en Playa del Carmen, a pasos d...",Apartment,Playa del Carmen,Mexico,Jun,89.00,4.78,231.0,543,14,Very Good
235,"Apartment in Playa del Carmen, Mexico",It Hotel & Residences - Studio Rental in PDC,Apartment,Playa del Carmen,Mexico,Jun,75.00,4.79,253.0,528,28,Very Good
107,"Apartment in Playa del Carmen, Mexico",BoHo lofts & studios new modern w/ ocean-view ...,Apartment,Playa del Carmen,Mexico,Jun,38.00,4.59,183.0,640,94,Good
187,"Apartment in Punta Cana, Dominican Republic",Charming Beach Condo in Bavaro Top Location,Apartment,Punta Cana,Dominican Republic,Jun,57.00,4.76,200.0,567,53,Very Good
105,"Apartment in Punta Cana, Dominican Republic",Pool View Beach Residence / Private Beach Access,Apartment,Punta Cana,Dominican Republic,Jun,37.00,4.71,156.0,595,96,Very Good
645,"Apartment in Quận 4, Vietnam",DANNY’s HIGH VIEW STUDIO near District1 Ben Th...,Apartment,Quận 4,Vietnam,Jun,44.00,4.78,167.0,545,82,Very Good
663,"Apartment in Quận 4, Vietnam",DANNY’s HIGH VIEW STUDIO near District1 Ben Th...,Apartment,Quận 4,Vietnam,Jun,44.00,4.78,167.0,546,82,Very Good
619,"Apartment in Tambon Kamala, Thailand",(A)Charming Pool Access One Bedroom Apartment,Apartment,Tambon Kamala,Thailand,Jun,65.00,4.82,68.0,487,42,Very Good
632,"Apartment in Tambon Kamala, Thailand",(A)Charming Pool Access One Bedroom Apartment,Apartment,Tambon Kamala,Thailand,Jun,65.00,4.82,68.0,488,42,Very Good
650,"Apartment in Tambon Kamala, Thailand",(A)Charming Pool Access One Bedroom Apartment,Apartment,Tambon Kamala,Thailand,Jun,65.00,4.82,68.0,489,42,Very Good
655,"Apartment in Tambon Patong, Thailand",SUNSET SEAVIEW DELUXE PATONG - POOL+TERRACE,Apartment,Tambon Patong,Thailand,Jun,64.00,4.80,159.0,513,44,Very Good
624,"Apartment in Tambon Patong, Thailand",SUNSET SEAVIEW DELUXE PATONG - POOL+TERRACE,Apartment,Tambon Patong,Thailand,Jun,64.00,4.80,159.0,511,44,Very Good
636,"Apartment in Tambon Patong, Thailand",SUNSET SEAVIEW DELUXE PATONG - POOL+TERRACE,Apartment,Tambon Patong,Thailand,Jun,64.00,4.80,159.0,512,44,Very Good
475,"Apartment in Tambon Patong, Thailand",One-Bedroom Suite in Patong Beach,Apartment,Tambon Patong,Thailand,Jun,49.00,4.73,67.0,584,66,Very Good
670,"Apartment in Tambon Patong, Thailand",1 BR Phuket Modern Luxury Living,Apartment,Tambon Patong,Thailand,Jun,44.00,4.68,202.0,609,82,Good
61,"Apartment in Tulum, Mexico",☆King Bed Apartment☆ Suk-Ha ☆ La Veleta,Apartment,Tulum,Mexico,Jun,55.00,4.60,73.0,637,55,Good
134,"Apartment in Tulum, Mexico",Design Casa Patchouli with private pool and lo...,Apartment,Tulum,Mexico,Jun,283.00,4.98,80.0,89,128,Excellent
106,"Boat in Stuart, Florida, US",Modern Houseboat On the water,Boat,Stuart,"Florida, US",Aug,173.00,4.97,264.0,107,200,Excellent
203,"Boat in Stuart, Florida, US",House Boat Sunset Bay Marina Stuart Fl,Boat,Stuart,"Florida, US",Sep,127.00,4.92,279.0,235,241,Excellent
356,"Bungalow in Izmir, Turkey",İzmir Bungalow. ( Urla treehouse 1),Bungalow,Izmir,Turkey,Jun,74.00,4.82,223.0,476,30,Very Good
366,"Bungalow in Izmir, Turkey",İzmir Bungalow. ( Urla treehouse 1),Bungalow,Izmir,Turkey,Jun,74.00,4.82,223.0,477,30,Very Good
200,"Cabin in Bowen Island, Canada",the legendary wildwood cabins ~ CABIN 4,Cabin,Bowen Island,Canada,Jul,173.00,4.98,678.0,76,200,Excellent
189,"Cabin in Bowen Island, Canada",the legendary wildwood cabins ~ CABIN 2,Cabin,Bowen Island,Canada,Sep,126.00,4.99,742.0,63,242,Excellent
398,"Cabin in Bridge of Earn, UK","The Haven Hut, warm, cosy and cute.",Cabin,Bridge of Earn,UK,Jun,64.00,4.67,9.0,620,44,Good
411,"Cabin in Bridge of Earn, UK","The Haven Hut, warm, cosy and cute.",Cabin,Bridge of Earn,UK,Jun,64.00,4.77,69.0,562,44,Very Good
394,"Cabin in County Wicklow, Ireland",House with breathtaking views!,Cabin,County Wicklow,Ireland,Jul,222.00,4.97,104.0,114,167,Excellent
408,"Cabin in County Wicklow, Ireland",House with breathtaking views!,Cabin,County Wicklow,Ireland,Jul,222.00,4.85,26.0,430,167,Very Good
634,"Cabin in Lazi, Philippines",Enchanted River cabin w/private garden and kit...,Cabin,Lazi,Philippines,Aug,51.00,4.85,127.0,415,61,Very Good
622,"Cabin in Lazi, Philippines",Enchanted River cabin w/private garden and kit...,Cabin,Lazi,Philippines,Aug,51.00,4.85,127.0,414,61,Very Good
653,"Cabin in Lazi, Philippines",Enchanted River cabin w/private garden and kit...,Cabin,Lazi,Philippines,Aug,51.00,4.85,127.0,416,61,Very Good
323,"Cabin in Llandissilio, UK",The Llama Lodge - a Log Cabin on a Llama Farm,Cabin,Llandissilio,UK,Jun,205.00,4.95,111.0,171,180,Excellent
313,"Cabin in Llandissilio, UK",The Llama Lodge - a Log Cabin on a Llama Farm,Cabin,Llandissilio,UK,Jun,205.00,4.92,60.0,251,180,Excellent
370,"Cabin in Millbrook, UK",Romantic Ocean View Couples Retreat Cornwall,Cabin,Millbrook,UK,Jun,357.00,5.00,61.0,11,100,Excellent
360,"Cabin in Millbrook, UK",Romantic Ocean View Couples Retreat Cornwall,Cabin,Millbrook,UK,Jun,357.00,5.00,61.0,10,100,Excellent
409,"Cabin in Serrazone, Italy",King's Windmill - A little house in the woods,Cabin,Serrazone,Italy,Jul,111.00,4.54,201.0,653,256,Good
396,"Cabin in Serrazone, Italy",King's Windmill - A little house in the woods,Cabin,Serrazone,Italy,Jul,111.00,4.54,201.0,652,256,Good
631,"Cabin in Tambon Ko Pha-ngan, Thailand","BOHO CABIN, Hin Kong Beachfront, West Coast.",Cabin,Tambon Ko Pha-ngan,Thailand,Jul,132.00,4.98,44.0,99,236,Excellent
647,"Cabin in Tambon Ko Pha-ngan, Thailand","BOHO CABIN, Hin Kong Beachfront, West Coast.",Cabin,Tambon Ko Pha-ngan,Thailand,Jul,132.00,4.98,44.0,100,236,Excellent
618,"Cabin in Tambon Ko Pha-ngan, Thailand","BOHO CABIN, Hin Kong Beachfront, West Coast.",Cabin,Tambon Ko Pha-ngan,Thailand,Jul,132.00,4.98,44.0,98,236,Excellent
309,"Cabin in Totana, Spain",Rural Aledo - El Estrecho,Cabin,Totana,Spain,Jun,76.00,4.78,24.0,552,27,Very Good
319,"Cabin in Totana, Spain",Rural Aledo - El Estrecho,Cabin,Totana,Spain,Jun,76.00,4.78,24.0,553,27,Very Good
316,"Castle in Winningen, Germany",Magazine - Oskar Schwebel -,Castle,Winningen,Germany,Jun,136.00,4.66,277.0,623,232,Good
306,"Castle in Winningen, Germany",Magazine - Oskar Schwebel -,Castle,Winningen,Germany,Jun,136.00,4.66,277.0,622,232,Good
315,"Cave in Mesaria, Greece",Luxury Triple cave room,Cave,Mesaria,Greece,Jun,129.00,4.72,32.0,592,239,Very Good
304,"Cave in Mesaria, Greece",Luxury Triple cave room,Cave,Mesaria,Greece,Jun,129.00,4.72,32.0,591,239,Very Good
116,"Condo in Atlantic City, New Jersey, US",Highest Reviewed - Ocean Front + Free Parking!,Condo,Atlantic City,"New Jersey, US",Jun,170.00,4.85,278.0,404,202,Very Good
214,"Condo in Atlantic City, New Jersey, US",Beachfront Condo Now Available! Sleeps 4 + Par...,Condo,Atlantic City,"New Jersey, US",Jun,133.00,4.51,88.0,659,235,Good
607,"Condo in Cebu City, Philippines",5-Star Experience at the Heart of Cebu,Condo,Cebu City,Philippines,Aug,49.00,4.96,280.0,133,66,Excellent
597,"Condo in Cebu City, Philippines",Scenic Cebu City View Condo in Ayala,Condo,Cebu City,Philippines,Jun,41.00,4.98,315.0,78,87,Excellent
635,"Condo in Cebu City, Philippines",Cozy City Condo at Horizons 101 [ W/ WIFI ].,Condo,Cebu City,Philippines,Jun,26.00,4.44,220.0,666,138,Needs Improvement
654,"Condo in Cebu City, Philippines",Cozy City Condo at Horizons 101 [ W/ WIFI ].,Condo,Cebu City,Philippines,Jun,26.00,4.44,220.0,667,138,Needs Improvement
642,"Condo in Cebu City, Philippines",Cozy Studio across Ayala Mall iT Park 1min walk,Condo,Cebu City,Philippines,Jul,26.00,4.78,235.0,542,138,Very Good
623,"Condo in Cebu City, Philippines",Cozy City Condo at Horizons 101 [ W/ WIFI ].,Condo,Cebu City,Philippines,Jun,26.00,4.44,220.0,665,138,Needs Improvement
626,"Condo in Chiang Mai, Thailand",Cozy room 48.5 sq.m @The Astra near Night market,Condo,Chiang Mai,Thailand,Jun,45.00,4.89,190.0,311,81,Very Good
637,"Condo in Chiang Mai, Thailand",Cozy room 48.5 sq.m @The Astra near Night market,Condo,Chiang Mai,Thailand,Jun,45.00,4.89,190.0,312,81,Very Good
656,"Condo in Chiang Mai, Thailand",Cozy room 48.5 sq.m @The Astra near Night market,Condo,Chiang Mai,Thailand,Jun,45.00,4.89,190.0,313,81,Very Good
522,"Condo in Johor Bahru, Malaysia","Baby & kids friendly, JB CIQ, Romantic Duplex",Condo,Johor Bahru,Malaysia,Jun,75.00,4.82,182.0,479,28,Very Good
648,"Condo in Johor Bahru, Malaysia",【R&F】Studio of Dual-Key Homely Getaway byⓗⓢ,Condo,Johor Bahru,Malaysia,Jun,44.00,4.78,139.0,547,82,Very Good
178,"Condo in Luquillo, Puerto Rico",“Playa Luna”- Breathtaking Ocean and City Views,Condo,Luquillo,Puerto Rico,Jul,138.00,4.88,159.0,335,230,Very Good
222,"Condo in Luquillo, Puerto Rico",AHHH-MAZING VIEWS! Beach Front Apt.,Condo,Luquillo,Puerto Rico,Sep,121.00,4.88,490.0,329,246,Very Good
50,"Condo in Malibu, California, US","Malibu, Carbon Beach - Suite Seven",Condo,Malibu,"California, US",Jun,898.00,4.86,311.0,382,13,Very Good
169,"Condo in Malibu, California, US","Malibu, Carbon Beach - Suite Three",Condo,Malibu,"California, US",Jun,649.00,4.80,425.0,504,43,Very Good
611,"Condo in Manila, Philippines","Amazing Manila Bay View! Spacious Comfy, Clean...",Condo,Manila,Philippines,Jun,69.00,4.90,154.0,294,35,Excellent
665,"Condo in Manila, Philippines",[50mbps+NETFLIX] Your home in the heart of Manila,Condo,Manila,Philippines,Jun,28.00,4.73,159.0,581,130,Very Good
657,"Condo in Melaka, Malaysia",B2733/Seaview/5mins to Jonker/Imperio/Studio/4pax,Condo,Melaka,Malaysia,Jun,30.00,4.71,230.0,594,120,Very Good
675,"Condo in Melaka, Malaysia",B1706/5 mins drive to Jonker/Imperio/Studio/4pax,Condo,Melaka,Malaysia,Jun,29.00,4.79,195.0,530,124,Very Good
595,"Condo in Melaka, Malaysia",B1731/Seaview/5 mine drive to Jonker/Imperio/4...,Condo,Melaka,Malaysia,Jun,23.00,4.54,209.0,651,160,Good
108,"Condo in Miami Beach, Florida, US",Oceanfront 14th Floor Brand New Beachfront Flat,Condo,Miami Beach,"Florida, US",Jun,302.00,4.85,646.0,400,118,Very Good
240,"Condo in Miami Beach, Florida, US",New 16th Floor Beachfront 180º Oceanview Apart...,Condo,Miami Beach,"Florida, US",Jun,302.00,4.87,659.0,352,118,Very Good
217,"Condo in Miami Beach, Florida, US",Oceanfront 16th Floor Brand New Beachfront Flat,Condo,Miami Beach,"Florida, US",Jun,302.00,4.83,683.0,454,118,Very Good
580,"Condo in Na Chom Thian, Thailand",Veranda Residence pattaya 2bedroom partial sea...,Condo,Na Chom Thian,Thailand,Jun,83.00,4.89,186.0,315,19,Very Good
565,"Condo in Na Chom Thian, Thailand",Veranda Residence pattaya 2bedroom partial sea...,Condo,Na Chom Thian,Thailand,Jun,83.00,4.89,186.0,314,19,Very Good
159,"Condo in Rosarito, Mexico",LUXE & STYLISH/3BR/LAS OLAS CONDO/12TH FLR/ROS...,Condo,Rosarito,Mexico,Jun,173.00,4.80,207.0,509,200,Very Good
115,"Condo in Rosarito, Mexico",Elegant Ocean Front Condo! Rosarito Beach !WOW!!,Condo,Rosarito,Mexico,Jun,171.00,4.81,245.0,494,201,Very Good
374,"Cottage in Benalauría, Spain","""La Parra"", rural tourism. Your home in paradise.",Cottage,Benalauría,Spain,Sep,67.00,4.99,335.0,65,40,Excellent
363,"Cottage in Benalauría, Spain","""La Parra"", rural tourism. Your home in paradise.",Cottage,Benalauría,Spain,Sep,67.00,4.99,335.0,64,40,Excellent
393,"Cottage in Boscastle, UK","A Boscastle barn, rustic simplicity stunning v...",Cottage,Boscastle,UK,Jun,141.00,5.00,9.0,49,227,Excellent
406,"Cottage in Boscastle, UK","A Boscastle barn, rustic simplicity stunning v...",Cottage,Boscastle,UK,Jun,141.00,5.00,18.0,30,227,Excellent
175,"Cottage in Islamorada, Florida, US",1 BD PRIVATE HOUSEBOAT/ COTTAGE TARPON,Cottage,Islamorada,"Florida, US",Aug,229.00,4.85,74.0,419,161,Very Good
161,"Cottage in Islamorada, Florida, US",1 BD PRIVATE HOUSEBOAT/ COTTAGE TARPON,Cottage,Islamorada,"Florida, US",Aug,229.00,4.85,74.0,418,161,Very Good
163,"Cottage in Quintana Roo, Mexico",Glass Roof House #2 at Glass 20.87,Cottage,Quintana Roo,Mexico,Jun,221.00,4.93,68.0,222,168,Excellent
177,"Cottage in Quintana Roo, Mexico",Glass Roof House #2 at Glass 20.87,Cottage,Quintana Roo,Mexico,Jun,221.00,4.93,68.0,223,168,Excellent
359,"Dome in Wapnica, Poland",Delightfull Dome with Hot tub & sauna on the b...,Dome,Wapnica,Poland,Jun,319.00,4.98,52.0,91,113,Excellent
369,"Dome in Wapnica, Poland",Delightfull Dome with Hot tub & sauna on the b...,Dome,Wapnica,Poland,Jun,319.00,4.98,52.0,92,113,Excellent
448,"Earthen home in Mueang Chiang Mai District, Th...",Leafy Greens Chiangmai : Mushroom M2,Earthen home,Mueang Chiang Mai District,Thailand,Jun,22.00,4.87,210.0,361,170,Very Good
451,"Earthen home in Mueang Chiang Mai District, Th...",Leafy Greens Chiangmai : Mushroom M2,Earthen home,Mueang Chiang Mai District,Thailand,Jun,22.00,4.87,210.0,362,170,Very Good
170,"Farm stay in Saint Marys, Canada",Cozy Farm Stay Getaway,Farm stay,Saint Marys,Canada,Jun,99.00,4.86,183.0,385,1,Very Good
184,"Farm stay in Saint Marys, Canada",Cozy Farm Stay Getaway,Farm stay,Saint Marys,Canada,Jun,99.00,4.86,183.0,386,1,Very Good
506,"Guest suite in Bingin Beach, Indonesia",Suite 2 - Beachfront Luxury Suite on Bingin Beach,Guest suite,Bingin Beach,Indonesia,Oct,267.00,4.93,96.0,221,134,Excellent
501,"Guest suite in Bingin Beach, Indonesia",Suite 2 - Beachfront Luxury Suite on Bingin Beach,Guest suite,Bingin Beach,Indonesia,Oct,267.00,4.93,96.0,220,134,Excellent
361,"Guest suite in La Marsa, Tunisia",THE AQUARIUM … waterfront 🧜🏾‍♂️,Guest suite,La Marsa,Tunisia,Jun,61.00,4.72,103.0,589,48,Very Good
371,"Guest suite in La Marsa, Tunisia",THE AQUARIUM … waterfront 🧜🏾‍♂️,Guest suite,La Marsa,Tunisia,Jun,61.00,4.72,103.0,590,48,Very Good
207,"Guesthouse in Naalehu, Hawaii, US",The Ohana,Guesthouse,Naalehu,"Hawaii, US",Jun,99.00,4.86,182.0,387,1,Very Good
211,"Guesthouse in Naalehu, Hawaii, US",The Ohana,Guesthouse,Naalehu,"Hawaii, US",Jun,99.00,4.86,182.0,388,1,Very Good
367,"Guesthouse in Perranwell Station, UK",The Folly - Cornwall,Guesthouse,Perranwell Station,UK,Jun,111.00,5.00,11.0,45,256,Excellent
357,"Guesthouse in Perranwell Station, UK",The Folly - Cornwall,Guesthouse,Perranwell Station,UK,Jun,111.00,5.00,11.0,44,256,Excellent
365,"Home in Audierne, France",Villa Trouz Ar Mor,Home,Audierne,France,Jul,135.00,4.85,13.0,432,233,Very Good
379,"Home in Audierne, France",Villa Trouz Ar Mor,Home,Audierne,France,Jul,135.00,4.85,13.0,433,233,Very Good
403,"Home in Bad Sankt Leonhard im Lavanttal, Austria",1A chalet resting crickets + hiking with indoo...,Home,Bad Sankt Leonhard im Lavanttal,Austria,Jun,123.00,4.67,110.0,619,244,Good
389,"Home in Bad Sankt Leonhard im Lavanttal, Austria",1A chalet resting crickets + hiking with indoo...,Home,Bad Sankt Leonhard im Lavanttal,Austria,Jun,123.00,4.67,110.0,618,244,Good
317,"Home in Baião, Portugal",CasasdoCasinhotoD-Rustic House (pool; river view),Home,Baião,Portugal,Jun,131.00,4.81,43.0,503,237,Very Good
307,"Home in Baião, Portugal",CasasdoCasinhotoD-Rustic House (pool; river view),Home,Baião,Portugal,Jun,131.00,4.81,43.0,502,237,Very Good
168,"Home in Cape Coral, Florida, US",Amazing Modern Home with Pool and Hot Tub!,Home,Cape Coral,"Florida, US",Jul,167.00,4.84,136.0,445,206,Very Good
183,"Home in Cape Coral, Florida, US",Amazing Modern Home with Pool and Hot Tub!,Home,Cape Coral,"Florida, US",Jul,167.00,4.84,136.0,446,206,Very Good
399,"Home in Chalkida, Greece",Seaside & Garden Single family home,Home,Chalkida,Greece,Jun,104.00,4.94,33.0,208,261,Excellent
385,"Home in Chalkida, Greece",Seaside & Garden Single family home,Home,Chalkida,Greece,Jun,104.00,4.94,33.0,207,261,Excellent
87,"Home in Hilbert, Wisconsin, US",State Park A-Frame with Hiking Trails & Arcade,Home,Hilbert,"Wisconsin, US",Jun,239.00,4.97,29.0,123,152,Excellent

In [81]:
duplicates = airbnb[
    airbnb.duplicated(
        subset=["Property Name"],
        keep=False
    )
].sort_values("Property Name")

duplicates

,Property Name,Amenities,Property Type,City,Country,Month,Price(in dollar),Rating,Number of Reviews,Rating Rank,Price Rank,Rating Category
368,"Apartment in Areti, Greece",Echoes Exclusive Suite,Apartment,Areti,Greece,Jun,526.00,4.98,40.0,103,58,Excellent
358,"Apartment in Areti, Greece",Echoes Exclusive Suite,Apartment,Areti,Greece,Jun,526.00,4.98,40.0,102,58,Excellent
155,"Apartment in Cancún, Mexico",Free Transportation / Premium Beach Loft 1711th,Apartment,Cancún,Mexico,Jun,138.00,5.00,15.0,32,230,Excellent
228,"Apartment in Cancún, Mexico",Cancun Suites (Standard Room),Apartment,Cancún,Mexico,Jul,81.00,4.47,192.0,662,21,Needs Improvement
158,"Apartment in Cancún, Mexico",Amazing Ocean Front II,Apartment,Cancún,Mexico,Jul,45.00,4.88,306.0,331,81,Very Good
243,"Apartment in Cancún, Mexico",1208 Beach property part ocean & pool view,Apartment,Cancún,Mexico,Jun,79.00,4.64,148.0,627,23,Good
126,"Apartment in Cancún, Mexico",Majestic Ocean Front Terrace II,Apartment,Cancún,Mexico,Jul,57.00,4.83,240.0,459,53,Very Good
176,"Apartment in Gordonville, Pennsylvania, US",“What a wonderful world” - Modern Farmhouse,Apartment,Gordonville,"Pennsylvania, US",Jun,165.00,4.87,478.0,354,208,Very Good
162,"Apartment in Gordonville, Pennsylvania, US",“What a wonderful world” - Modern Farmhouse,Apartment,Gordonville,"Pennsylvania, US",Jun,165.00,4.87,478.0,353,208,Very Good
605,"Apartment in Kuala Lumpur, Malaysia",1min KLCC Twin Tower & Pavilion/Ins cottage fo...,Apartment,Kuala Lumpur,Malaysia,Jun,38.00,4.91,278.0,261,94,Excellent
646,"Apartment in Kuala Lumpur, Malaysia",Premier Lux Studio Large Tv Free Netflix | City,Apartment,Kuala Lumpur,Malaysia,Jun,62.00,4.90,166.0,292,47,Excellent
576,"Apartment in Kuala Lumpur, Malaysia",Walk to Petronas Towers from a Stylish Apartment,Apartment,Kuala Lumpur,Malaysia,Jun,71.00,4.89,296.0,309,33,Very Good
627,"Apartment in Kuala Lumpur, Malaysia",EXPRESSIONZ-1Bedroom-Junior-Suite-KLCC-Sky-Pool,Apartment,Kuala Lumpur,Malaysia,Jun,53.00,4.78,408.0,538,57,Very Good
639,"Apartment in Kuala Lumpur, Malaysia",EXPRESSIONZ-1Bedroom-Junior-Suite-KLCC-Sky-Pool,Apartment,Kuala Lumpur,Malaysia,Jun,53.00,4.78,408.0,539,57,Very Good
674,"Apartment in Kuala Lumpur, Malaysia",Admire Deluxe Marble Walls at a Highrise Resor...,Apartment,Kuala Lumpur,Malaysia,Jun,85.00,4.85,135.0,413,17,Very Good
542,"Apartment in Kuala Lumpur, Malaysia",Instagrammable Loft Studio in EkoCheras KL,Apartment,Kuala Lumpur,Malaysia,Jul,60.00,4.94,84.0,203,50,Excellent
181,"Apartment in Marina del Rey, California, US",Romantic Ocean Penthouse w/ panoramic marina v...,Apartment,Marina del Rey,"California, US",Jun,247.00,4.77,111.0,560,147,Very Good
164,"Apartment in Marina del Rey, California, US",Romantic Ocean Penthouse w/ panoramic marina v...,Apartment,Marina del Rey,"California, US",Jun,247.00,4.77,111.0,559,147,Very Good
551,"Apartment in Melaka, Malaysia",Yuma • Atlantis Melaka/3BR 8Pax WiFi Balcony S...,Apartment,Melaka,Malaysia,Jun,40.00,4.43,7.0,671,89,Needs Improvement
614,"Apartment in Melaka, Malaysia",B1933B/5 min drive to Jonker/Seaview/Imperio/4...,Apartment,Melaka,Malaysia,Jun,24.00,4.69,196.0,604,151,Good
652,"Apartment in Muang Pattaya, Thailand",#18 2022 Newest! Downtown Lux Fun Sea View Condo,Apartment,Muang Pattaya,Thailand,Jun,63.00,5.00,27.0,21,45,Excellent
467,"Apartment in Muang Pattaya, Thailand",[VR] 2BR High Skyline Ocean View @ Pattaya,Apartment,Muang Pattaya,Thailand,Jun,136.00,4.69,85.0,607,232,Good
579,"Apartment in PHUKET, Thailand",★Studio in Seafront Private Villa w/infinity p...,Apartment,PHUKET,Thailand,Jun,53.00,4.83,93.0,466,57,Very Good
589,"Apartment in PHUKET, Thailand",Studio in Beachfront Private Villa w/Infinity ...,Apartment,PHUKET,Thailand,Jun,38.00,4.88,64.0,344,94,Very Good
564,"Apartment in PHUKET, Thailand",★Studio in Seafront Private Villa w/infinity p...,Apartment,PHUKET,Thailand,Jun,53.00,4.83,93.0,465,57,Very Good
558,"Apartment in Phuket, Thailand","Luxury room & Sky pool, in Phuket town",Apartment,Phuket,Thailand,Jun,40.00,4.81,210.0,497,89,Very Good
574,"Apartment in Phuket, Thailand","Luxury room & Sky pool, in Phuket town",Apartment,Phuket,Thailand,Jun,40.00,4.81,210.0,498,89,Very Good
568,"Apartment in Phuket, Thailand",Cozy Place near Shopping Center,Apartment,Phuket,Thailand,Jun,35.00,4.96,237.0,136,102,Excellent
73,"Apartment in Playa del Carmen, Mexico","Su mejor opción en Playa del Carmen, a pasos d...",Apartment,Playa del Carmen,Mexico,Jun,89.00,4.78,231.0,543,14,Very Good
235,"Apartment in Playa del Carmen, Mexico",It Hotel & Residences - Studio Rental in PDC,Apartment,Playa del Carmen,Mexico,Jun,75.00,4.79,253.0,528,28,Very Good
107,"Apartment in Playa del Carmen, Mexico",BoHo lofts & studios new modern w/ ocean-view ...,Apartment,Playa del Carmen,Mexico,Jun,38.00,4.59,183.0,640,94,Good
187,"Apartment in Punta Cana, Dominican Republic",Charming Beach Condo in Bavaro Top Location,Apartment,Punta Cana,Dominican Republic,Jun,57.00,4.76,200.0,567,53,Very Good
105,"Apartment in Punta Cana, Dominican Republic",Pool View Beach Residence / Private Beach Access,Apartment,Punta Cana,Dominican Republic,Jun,37.00,4.71,156.0,595,96,Very Good
645,"Apartment in Quận 4, Vietnam",DANNY’s HIGH VIEW STUDIO near District1 Ben Th...,Apartment,Quận 4,Vietnam,Jun,44.00,4.78,167.0,545,82,Very Good
663,"Apartment in Quận 4, Vietnam",DANNY’s HIGH VIEW STUDIO near District1 Ben Th...,Apartment,Quận 4,Vietnam,Jun,44.00,4.78,167.0,546,82,Very Good
619,"Apartment in Tambon Kamala, Thailand",(A)Charming Pool Access One Bedroom Apartment,Apartment,Tambon Kamala,Thailand,Jun,65.00,4.82,68.0,487,42,Very Good
632,"Apartment in Tambon Kamala, Thailand",(A)Charming Pool Access One Bedroom Apartment,Apartment,Tambon Kamala,Thailand,Jun,65.00,4.82,68.0,488,42,Very Good
650,"Apartment in Tambon Kamala, Thailand",(A)Charming Pool Access One Bedroom Apartment,Apartment,Tambon Kamala,Thailand,Jun,65.00,4.82,68.0,489,42,Very Good
475,"Apartment in Tambon Patong, Thailand",One-Bedroom Suite in Patong Beach,Apartment,Tambon Patong,Thailand,Jun,49.00,4.73,67.0,584,66,Very Good
624,"Apartment in Tambon Patong, Thailand",SUNSET SEAVIEW DELUXE PATONG - POOL+TERRACE,Apartment,Tambon Patong,Thailand,Jun,64.00,4.80,159.0,511,44,Very Good
636,"Apartment in Tambon Patong, Thailand",SUNSET SEAVIEW DELUXE PATONG - POOL+TERRACE,Apartment,Tambon Patong,Thailand,Jun,64.00,4.80,159.0,512,44,Very Good
670,"Apartment in Tambon Patong, Thailand",1 BR Phuket Modern Luxury Living,Apartment,Tambon Patong,Thailand,Jun,44.00,4.68,202.0,609,82,Good
655,"Apartment in Tambon Patong, Thailand",SUNSET SEAVIEW DELUXE PATONG - POOL+TERRACE,Apartment,Tambon Patong,Thailand,Jun,64.00,4.80,159.0,513,44,Very Good
61,"Apartment in Tulum, Mexico",☆King Bed Apartment☆ Suk-Ha ☆ La Veleta,Apartment,Tulum,Mexico,Jun,55.00,4.60,73.0,637,55,Good
134,"Apartment in Tulum, Mexico",Design Casa Patchouli with private pool and lo...,Apartment,Tulum,Mexico,Jun,283.00,4.98,80.0,89,128,Excellent
106,"Boat in Stuart, Florida, US",Modern Houseboat On the water,Boat,Stuart,"Florida, US",Aug,173.00,4.97,264.0,107,200,Excellent
203,"Boat in Stuart, Florida, US",House Boat Sunset Bay Marina Stuart Fl,Boat,Stuart,"Florida, US",Sep,127.00,4.92,279.0,235,241,Excellent
356,"Bungalow in Izmir, Turkey",İzmir Bungalow. ( Urla treehouse 1),Bungalow,Izmir,Turkey,Jun,74.00,4.82,223.0,476,30,Very Good
366,"Bungalow in Izmir, Turkey",İzmir Bungalow. ( Urla treehouse 1),Bungalow,Izmir,Turkey,Jun,74.00,4.82,223.0,477,30,Very Good
200,"Cabin in Bowen Island, Canada",the legendary wildwood cabins ~ CABIN 4,Cabin,Bowen Island,Canada,Jul,173.00,4.98,678.0,76,200,Excellent
189,"Cabin in Bowen Island, Canada",the legendary wildwood cabins ~ CABIN 2,Cabin,Bowen Island,Canada,Sep,126.00,4.99,742.0,63,242,Excellent
411,"Cabin in Bridge of Earn, UK","The Haven Hut, warm, cosy and cute.",Cabin,Bridge of Earn,UK,Jun,64.00,4.77,69.0,562,44,Very Good
398,"Cabin in Bridge of Earn, UK","The Haven Hut, warm, cosy and cute.",Cabin,Bridge of Earn,UK,Jun,64.00,4.67,9.0,620,44,Good
394,"Cabin in County Wicklow, Ireland",House with breathtaking views!,Cabin,County Wicklow,Ireland,Jul,222.00,4.97,104.0,114,167,Excellent
408,"Cabin in County Wicklow, Ireland",House with breathtaking views!,Cabin,County Wicklow,Ireland,Jul,222.00,4.85,26.0,430,167,Very Good
653,"Cabin in Lazi, Philippines",Enchanted River cabin w/private garden and kit...,Cabin,Lazi,Philippines,Aug,51.00,4.85,127.0,416,61,Very Good
622,"Cabin in Lazi, Philippines",Enchanted River cabin w/private garden and kit...,Cabin,Lazi,Philippines,Aug,51.00,4.85,127.0,414,61,Very Good
634,"Cabin in Lazi, Philippines",Enchanted River cabin w/private garden and kit...,Cabin,Lazi,Philippines,Aug,51.00,4.85,127.0,415,61,Very Good
313,"Cabin in Llandissilio, UK",The Llama Lodge - a Log Cabin on a Llama Farm,Cabin,Llandissilio,UK,Jun,205.00,4.92,60.0,251,180,Excellent
323,"Cabin in Llandissilio, UK",The Llama Lodge - a Log Cabin on a Llama Farm,Cabin,Llandissilio,UK,Jun,205.00,4.95,111.0,171,180,Excellent
370,"Cabin in Millbrook, UK",Romantic Ocean View Couples Retreat Cornwall,Cabin,Millbrook,UK,Jun,357.00,5.00,61.0,11,100,Excellent
360,"Cabin in Millbrook, UK",Romantic Ocean View Couples Retreat Cornwall,Cabin,Millbrook,UK,Jun,357.00,5.00,61.0,10,100,Excellent
396,"Cabin in Serrazone, Italy",King's Windmill - A little house in the woods,Cabin,Serrazone,Italy,Jul,111.00,4.54,201.0,652,256,Good
409,"Cabin in Serrazone, Italy",King's Windmill - A little house in the woods,Cabin,Serrazone,Italy,Jul,111.00,4.54,201.0,653,256,Good
631,"Cabin in Tambon Ko Pha-ngan, Thailand","BOHO CABIN, Hin Kong Beachfront, West Coast.",Cabin,Tambon Ko Pha-ngan,Thailand,Jul,132.00,4.98,44.0,99,236,Excellent
647,"Cabin in Tambon Ko Pha-ngan, Thailand","BOHO CABIN, Hin Kong Beachfront, West Coast.",Cabin,Tambon Ko Pha-ngan,Thailand,Jul,132.00,4.98,44.0,100,236,Excellent
618,"Cabin in Tambon Ko Pha-ngan, Thailand","BOHO CABIN, Hin Kong Beachfront, West Coast.",Cabin,Tambon Ko Pha-ngan,Thailand,Jul,132.00,4.98,44.0,98,236,Excellent
319,"Cabin in Totana, Spain",Rural Aledo - El Estrecho,Cabin,Totana,Spain,Jun,76.00,4.78,24.0,553,27,Very Good
309,"Cabin in Totana, Spain",Rural Aledo - El Estrecho,Cabin,Totana,Spain,Jun,76.00,4.78,24.0,552,27,Very Good
316,"Castle in Winningen, Germany",Magazine - Oskar Schwebel -,Castle,Winningen,Germany,Jun,136.00,4.66,277.0,623,232,Good
306,"Castle in Winningen, Germany",Magazine - Oskar Schwebel -,Castle,Winningen,Germany,Jun,136.00,4.66,277.0,622,232,Good
315,"Cave in Mesaria, Greece",Luxury Triple cave room,Cave,Mesaria,Greece,Jun,129.00,4.72,32.0,592,239,Very Good
304,"Cave in Mesaria, Greece",Luxury Triple cave room,Cave,Mesaria,Greece,Jun,129.00,4.72,32.0,591,239,Very Good
214,"Condo in Atlantic City, New Jersey, US",Beachfront Condo Now Available! Sleeps 4 + Par...,Condo,Atlantic City,"New Jersey, US",Jun,133.00,4.51,88.0,659,235,Good
116,"Condo in Atlantic City, New Jersey, US",Highest Reviewed - Ocean Front + Free Parking!,Condo,Atlantic City,"New Jersey, US",Jun,170.00,4.85,278.0,404,202,Very Good
654,"Condo in Cebu City, Philippines",Cozy City Condo at Horizons 101 [ W/ WIFI ].,Condo,Cebu City,Philippines,Jun,26.00,4.44,220.0,667,138,Needs Improvement
642,"Condo in Cebu City, Philippines",Cozy Studio across Ayala Mall iT Park 1min walk,Condo,Cebu City,Philippines,Jul,26.00,4.78,235.0,542,138,Very Good
635,"Condo in Cebu City, Philippines",Cozy City Condo at Horizons 101 [ W/ WIFI ].,Condo,Cebu City,Philippines,Jun,26.00,4.44,220.0,666,138,Needs Improvement
607,"Condo in Cebu City, Philippines",5-Star Experience at the Heart of Cebu,Condo,Cebu City,Philippines,Aug,49.00,4.96,280.0,133,66,Excellent
623,"Condo in Cebu City, Philippines",Cozy City Condo at Horizons 101 [ W/ WIFI ].,Condo,Cebu City,Philippines,Jun,26.00,4.44,220.0,665,138,Needs Improvement
597,"Condo in Cebu City, Philippines",Scenic Cebu City View Condo in Ayala,Condo,Cebu City,Philippines,Jun,41.00,4.98,315.0,78,87,Excellent
637,"Condo in Chiang Mai, Thailand",Cozy room 48.5 sq.m @The Astra near Night market,Condo,Chiang Mai,Thailand,Jun,45.00,4.89,190.0,312,81,Very Good
656,"Condo in Chiang Mai, Thailand",Cozy room 48.5 sq.m @The Astra near Night market,Condo,Chiang Mai,Thailand,Jun,45.00,4.89,190.0,313,81,Very Good
626,"Condo in Chiang Mai, Thailand",Cozy room 48.5 sq.m @The Astra near Night market,Condo,Chiang Mai,Thailand,Jun,45.00,4.89,190.0,311,81,Very Good
648,"Condo in Johor Bahru, Malaysia",【R&F】Studio of Dual-Key Homely Getaway byⓗⓢ,Condo,Johor Bahru,Malaysia,Jun,44.00,4.78,139.0,547,82,Very Good
522,"Condo in Johor Bahru, Malaysia","Baby & kids friendly, JB CIQ, Romantic Duplex",Condo,Johor Bahru,Malaysia,Jun,75.00,4.82,182.0,479,28,Very Good
178,"Condo in Luquillo, Puerto Rico",“Playa Luna”- Breathtaking Ocean and City Views,Condo,Luquillo,Puerto Rico,Jul,138.00,4.88,159.0,335,230,Very Good
222,"Condo in Luquillo, Puerto Rico",AHHH-MAZING VIEWS! Beach Front Apt.,Condo,Luquillo,Puerto Rico,Sep,121.00,4.88,490.0,329,246,Very Good
50,"Condo in Malibu, California, US","Malibu, Carbon Beach - Suite Seven",Condo,Malibu,"California, US",Jun,898.00,4.86,311.0,382,13,Very Good
169,"Condo in Malibu, California, US","Malibu, Carbon Beach - Suite Three",Condo,Malibu,"California, US",Jun,649.00,4.80,425.0,504,43,Very Good
611,"Condo in Manila, Philippines","Amazing Manila Bay View! Spacious Comfy, Clean...",Condo,Manila,Philippines,Jun,69.00,4.90,154.0,294,35,Excellent
665,"Condo in Manila, Philippines",[50mbps+NETFLIX] Your home in the heart of Manila,Condo,Manila,Philippines,Jun,28.00,4.73,159.0,581,130,Very Good
595,"Condo in Melaka, Malaysia",B1731/Seaview/5 mine drive to Jonker/Imperio/4...,Condo,Melaka,Malaysia,Jun,23.00,4.54,209.0,651,160,Good
675,"Condo in Melaka, Malaysia",B1706/5 mins drive to Jonker/Imperio/Studio/4pax,Condo,Melaka,Malaysia,Jun,29.00,4.79,195.0,530,124,Very Good
657,"Condo in Melaka, Malaysia",B2733/Seaview/5mins to Jonker/Imperio/Studio/4pax,Condo,Melaka,Malaysia,Jun,30.00,4.71,230.0,594,120,Very Good
108,"Condo in Miami Beach, Florida, US",Oceanfront 14th Floor Brand New Beachfront Flat,Condo,Miami Beach,"Florida, US",Jun,302.00,4.85,646.0,400,118,Very Good
240,"Condo in Miami Beach, Florida, US",New 16th Floor Beachfront 180º Oceanview Apart...,Condo,Miami Beach,"Florida, US",Jun,302.00,4.87,659.0,352,118,Very Good
217,"Condo in Miami Beach, Florida, US",Oceanfront 16th Floor Brand New Beachfront Flat,Condo,Miami Beach,"Florida, US",Jun,302.00,4.83,683.0,454,118,Very Good
580,"Condo in Na Chom Thian, Thailand",Veranda Residence pattaya 2bedroom partial sea...,Condo,Na Chom Thian,Thailand,Jun,83.00,4.89,186.0,315,19,Very Good
565,"Condo in Na Chom Thian, Thailand",Veranda Residence pattaya 2bedroom partial sea...,Condo,Na Chom Thian,Thailand,Jun,83.00,4.89,186.0,314,19,Very Good
115,"Condo in Rosarito, Mexico",Elegant Ocean Front Condo! Rosarito Beach !WOW!!,Condo,Rosarito,Mexico,Jun,171.00,4.81,245.0,494,201,Very Good
159,"Condo in Rosarito, Mexico",LUXE & STYLISH/3BR/LAS OLAS CONDO/12TH FLR/ROS...,Condo,Rosarito,Mexico,Jun,173.00,4.80,207.0,509,200,Very Good
363,"Cottage in Benalauría, Spain","""La Parra"", rural tourism. Your home in paradise.",Cottage,Benalauría,Spain,Sep,67.00,4.99,335.0,64,40,Excellent
374,"Cottage in Benalauría, Spain","""La Parra"", rural tourism. Your home in paradise.",Cottage,Benalauría,Spain,Sep,67.00,4.99,335.0,65,40,Excellent
393,"Cottage in Boscastle, UK","A Boscastle barn, rustic simplicity stunning v...",Cottage,Boscastle,UK,Jun,141.00,5.00,9.0,49,227,Excellent
406,"Cottage in Boscastle, UK","A Boscastle barn, rustic simplicity stunning v...",Cottage,Boscastle,UK,Jun,141.00,5.00,18.0,30,227,Excellent
175,"Cottage in Islamorada, Florida, US",1 BD PRIVATE HOUSEBOAT/ COTTAGE TARPON,Cottage,Islamorada,"Florida, US",Aug,229.00,4.85,74.0,419,161,Very Good
161,"Cottage in Islamorada, Florida, US",1 BD PRIVATE HOUSEBOAT/ COTTAGE TARPON,Cottage,Islamorada,"Florida, US",Aug,229.00,4.85,74.0,418,161,Very Good
163,"Cottage in Quintana Roo, Mexico",Glass Roof House #2 at Glass 20.87,Cottage,Quintana Roo,Mexico,Jun,221.00,4.93,68.0,222,168,Excellent
177,"Cottage in Quintana Roo, Mexico",Glass Roof House #2 at Glass 20.87,Cottage,Quintana Roo,Mexico,Jun,221.00,4.93,68.0,223,168,Excellent
359,"Dome in Wapnica, Poland",Delightfull Dome with Hot tub & sauna on the b...,Dome,Wapnica,Poland,Jun,319.00,4.98,52.0,91,113,Excellent
369,"Dome in Wapnica, Poland",Delightfull Dome with Hot tub & sauna on the b...,Dome,Wapnica,Poland,Jun,319.00,4.98,52.0,92,113,Excellent
448,"Earthen home in Mueang Chiang Mai District, Th...",Leafy Greens Chiangmai : Mushroom M2,Earthen home,Mueang Chiang Mai District,Thailand,Jun,22.00,4.87,210.0,361,170,Very Good
451,"Earthen home in Mueang Chiang Mai District, Th...",Leafy Greens Chiangmai : Mushroom M2,Earthen home,Mueang Chiang Mai District,Thailand,Jun,22.00,4.87,210.0,362,170,Very Good
184,"Farm stay in Saint Marys, Canada",Cozy Farm Stay Getaway,Farm stay,Saint Marys,Canada,Jun,99.00,4.86,183.0,386,1,Very Good
170,"Farm stay in Saint Marys, Canada",Cozy Farm Stay Getaway,Farm stay,Saint Marys,Canada,Jun,99.00,4.86,183.0,385,1,Very Good
506,"Guest suite in Bingin Beach, Indonesia",Suite 2 - Beachfront Luxury Suite on Bingin Beach,Guest suite,Bingin Beach,Indonesia,Oct,267.00,4.93,96.0,221,134,Excellent
501,"Guest suite in Bingin Beach, Indonesia",Suite 2 - Beachfront Luxury Suite on Bingin Beach,Guest suite,Bingin Beach,Indonesia,Oct,267.00,4.93,96.0,220,134,Excellent
371,"Guest suite in La Marsa, Tunisia",THE AQUARIUM … waterfront 🧜🏾‍♂️,Guest suite,La Marsa,Tunisia,Jun,61.00,4.72,103.0,590,48,Very Good
361,"Guest suite in La Marsa, Tunisia",THE AQUARIUM … waterfront 🧜🏾‍♂️,Guest suite,La Marsa,Tunisia,Jun,61.00,4.72,103.0,589,48,Very Good
211,"Guesthouse in Naalehu, Hawaii, US",The Ohana,Guesthouse,Naalehu,"Hawaii, US",Jun,99.00,4.86,182.0,388,1,Very Good
207,"Guesthouse in Naalehu, Hawaii, US",The Ohana,Guesthouse,Naalehu,"Hawaii, US",Jun,99.00,4.86,182.0,387,1,Very Good
357,"Guesthouse in Perranwell Station, UK",The Folly - Cornwall,Guesthouse,Perranwell Station,UK,Jun,111.00,5.00,11.0,44,256,Excellent
367,"Guesthouse in Perranwell Station, UK",The Folly - Cornwall,Guesthouse,Perranwell Station,UK,Jun,111.00,5.00,11.0,45,256,Excellent
365,"Home in Audierne, France",Villa Trouz Ar Mor,Home,Audierne,France,Jul,135.00,4.85,13.0,432,233,Very Good
379,"Home in Audierne, France",Villa Trouz Ar Mor,Home,Audierne,France,Jul,135.00,4.85,13.0,433,233,Very Good
389,"Home in Bad Sankt Leonhard im Lavanttal, Austria",1A chalet resting crickets + hiking with indoo...,Home,Bad Sankt Leonhard im Lavanttal,Austria,Jun,123.00,4.67,110.0,618,244,Good
403,"Home in Bad Sankt Leonhard im Lavanttal, Austria",1A chalet resting crickets + hiking with indoo...,Home,Bad Sankt Leonhard im Lavanttal,Austria,Jun,123.00,4.67,110.0,619,244,Good
307,"Home in Baião, Portugal",CasasdoCasinhotoD-Rustic House (pool; river view),Home,Baião,Portugal,Jun,131.00,4.81,43.0,502,237,Very Good
317,"Home in Baião, Portugal",CasasdoCasinhotoD-Rustic House (pool; river view),Home,Baião,Portugal,Jun,131.00,4.81,43.0,503,237,Very Good
183,"Home in Cape Coral, Florida, US",Amazing Modern Home with Pool and Hot Tub!,Home,Cape Coral,"Florida, US",Jul,167.00,4.84,136.0,446,206,Very Good
168,"Home in Cape Coral, Florida, US",Amazing Modern Home with Pool and Hot Tub!,Home,Cape Coral,"Florida, US",Jul,167.00,4.84,136.0,445,206,Very Good
399,"Home in Chalkida, Greece",Seaside & Garden Single family home,Home,Chalkida,Greece,Jun,104.00,4.94,33.0,208,261,Excellent
385,"Home in Chalkida, Greece",Seaside & Garden Single family home,Home,Chalkida,Greece,Jun,104.00,4.94,33.0,207,261,Excellent
87,"Home in Hilbert, Wisconsin, US",State Park A-Frame with Hiking Trails & Arcade,Home,Hilbert,"Wisconsin, US",Jun,239.00,4.97,29.0,123,152,Excellent

In [82]:
duplicates = airbnb[
    airbnb.duplicated(
        subset=[
            "Property Name",
            "Amenities",
            "Property Type",
            "City",
            "Country",
            "Month",
            "Price(in dollar)",
            "Rating",
            "Number of Reviews",
            "Rating Category"
        ],
        keep=False
    )
].sort_values(
    by=[
        "Property Name",
        "City",
        "Country"
    ]
)

display(duplicates)

,Property Name,Amenities,Property Type,City,Country,Month,Price(in dollar),Rating,Number of Reviews,Rating Rank,Price Rank,Rating Category
358,"Apartment in Areti, Greece",Echoes Exclusive Suite,Apartment,Areti,Greece,Jun,526.00,4.98,40.0,102,58,Excellent
368,"Apartment in Areti, Greece",Echoes Exclusive Suite,Apartment,Areti,Greece,Jun,526.00,4.98,40.0,103,58,Excellent
162,"Apartment in Gordonville, Pennsylvania, US",“What a wonderful world” - Modern Farmhouse,Apartment,Gordonville,"Pennsylvania, US",Jun,165.00,4.87,478.0,353,208,Very Good
176,"Apartment in Gordonville, Pennsylvania, US",“What a wonderful world” - Modern Farmhouse,Apartment,Gordonville,"Pennsylvania, US",Jun,165.00,4.87,478.0,354,208,Very Good
627,"Apartment in Kuala Lumpur, Malaysia",EXPRESSIONZ-1Bedroom-Junior-Suite-KLCC-Sky-Pool,Apartment,Kuala Lumpur,Malaysia,Jun,53.00,4.78,408.0,538,57,Very Good
639,"Apartment in Kuala Lumpur, Malaysia",EXPRESSIONZ-1Bedroom-Junior-Suite-KLCC-Sky-Pool,Apartment,Kuala Lumpur,Malaysia,Jun,53.00,4.78,408.0,539,57,Very Good
164,"Apartment in Marina del Rey, California, US",Romantic Ocean Penthouse w/ panoramic marina v...,Apartment,Marina del Rey,"California, US",Jun,247.00,4.77,111.0,559,147,Very Good
181,"Apartment in Marina del Rey, California, US",Romantic Ocean Penthouse w/ panoramic marina v...,Apartment,Marina del Rey,"California, US",Jun,247.00,4.77,111.0,560,147,Very Good
564,"Apartment in PHUKET, Thailand",★Studio in Seafront Private Villa w/infinity p...,Apartment,PHUKET,Thailand,Jun,53.00,4.83,93.0,465,57,Very Good
579,"Apartment in PHUKET, Thailand",★Studio in Seafront Private Villa w/infinity p...,Apartment,PHUKET,Thailand,Jun,53.00,4.83,93.0,466,57,Very Good
558,"Apartment in Phuket, Thailand","Luxury room & Sky pool, in Phuket town",Apartment,Phuket,Thailand,Jun,40.00,4.81,210.0,497,89,Very Good
574,"Apartment in Phuket, Thailand","Luxury room & Sky pool, in Phuket town",Apartment,Phuket,Thailand,Jun,40.00,4.81,210.0,498,89,Very Good
645,"Apartment in Quận 4, Vietnam",DANNY’s HIGH VIEW STUDIO near District1 Ben Th...,Apartment,Quận 4,Vietnam,Jun,44.00,4.78,167.0,545,82,Very Good
663,"Apartment in Quận 4, Vietnam",DANNY’s HIGH VIEW STUDIO near District1 Ben Th...,Apartment,Quận 4,Vietnam,Jun,44.00,4.78,167.0,546,82,Very Good
619,"Apartment in Tambon Kamala, Thailand",(A)Charming Pool Access One Bedroom Apartment,Apartment,Tambon Kamala,Thailand,Jun,65.00,4.82,68.0,487,42,Very Good
632,"Apartment in Tambon Kamala, Thailand",(A)Charming Pool Access One Bedroom Apartment,Apartment,Tambon Kamala,Thailand,Jun,65.00,4.82,68.0,488,42,Very Good
650,"Apartment in Tambon Kamala, Thailand",(A)Charming Pool Access One Bedroom Apartment,Apartment,Tambon Kamala,Thailand,Jun,65.00,4.82,68.0,489,42,Very Good
655,"Apartment in Tambon Patong, Thailand",SUNSET SEAVIEW DELUXE PATONG - POOL+TERRACE,Apartment,Tambon Patong,Thailand,Jun,64.00,4.80,159.0,513,44,Very Good
624,"Apartment in Tambon Patong, Thailand",SUNSET SEAVIEW DELUXE PATONG - POOL+TERRACE,Apartment,Tambon Patong,Thailand,Jun,64.00,4.80,159.0,511,44,Very Good
636,"Apartment in Tambon Patong, Thailand",SUNSET SEAVIEW DELUXE PATONG - POOL+TERRACE,Apartment,Tambon Patong,Thailand,Jun,64.00,4.80,159.0,512,44,Very Good
356,"Bungalow in Izmir, Turkey",İzmir Bungalow. ( Urla treehouse 1),Bungalow,Izmir,Turkey,Jun,74.00,4.82,223.0,476,30,Very Good
366,"Bungalow in Izmir, Turkey",İzmir Bungalow. ( Urla treehouse 1),Bungalow,Izmir,Turkey,Jun,74.00,4.82,223.0,477,30,Very Good
634,"Cabin in Lazi, Philippines",Enchanted River cabin w/private garden and kit...,Cabin,Lazi,Philippines,Aug,51.00,4.85,127.0,415,61,Very Good
622,"Cabin in Lazi, Philippines",Enchanted River cabin w/private garden and kit...,Cabin,Lazi,Philippines,Aug,51.00,4.85,127.0,414,61,Very Good
653,"Cabin in Lazi, Philippines",Enchanted River cabin w/private garden and kit...,Cabin,Lazi,Philippines,Aug,51.00,4.85,127.0,416,61,Very Good
370,"Cabin in Millbrook, UK",Romantic Ocean View Couples Retreat Cornwall,Cabin,Millbrook,UK,Jun,357.00,5.00,61.0,11,100,Excellent
360,"Cabin in Millbrook, UK",Romantic Ocean View Couples Retreat Cornwall,Cabin,Millbrook,UK,Jun,357.00,5.00,61.0,10,100,Excellent
409,"Cabin in Serrazone, Italy",King's Windmill - A little house in the woods,Cabin,Serrazone,Italy,Jul,111.00,4.54,201.0,653,256,Good
396,"Cabin in Serrazone, Italy",King's Windmill - A little house in the woods,Cabin,Serrazone,Italy,Jul,111.00,4.54,201.0,652,256,Good
631,"Cabin in Tambon Ko Pha-ngan, Thailand","BOHO CABIN, Hin Kong Beachfront, West Coast.",Cabin,Tambon Ko Pha-ngan,Thailand,Jul,132.00,4.98,44.0,99,236,Excellent
647,"Cabin in Tambon Ko Pha-ngan, Thailand","BOHO CABIN, Hin Kong Beachfront, West Coast.",Cabin,Tambon Ko Pha-ngan,Thailand,Jul,132.00,4.98,44.0,100,236,Excellent
618,"Cabin in Tambon Ko Pha-ngan, Thailand","BOHO CABIN, Hin Kong Beachfront, West Coast.",Cabin,Tambon Ko Pha-ngan,Thailand,Jul,132.00,4.98,44.0,98,236,Excellent
309,"Cabin in Totana, Spain",Rural Aledo - El Estrecho,Cabin,Totana,Spain,Jun,76.00,4.78,24.0,552,27,Very Good
319,"Cabin in Totana, Spain",Rural Aledo - El Estrecho,Cabin,Totana,Spain,Jun,76.00,4.78,24.0,553,27,Very Good
316,"Castle in Winningen, Germany",Magazine - Oskar Schwebel -,Castle,Winningen,Germany,Jun,136.00,4.66,277.0,623,232,Good
306,"Castle in Winningen, Germany",Magazine - Oskar Schwebel -,Castle,Winningen,Germany,Jun,136.00,4.66,277.0,622,232,Good
315,"Cave in Mesaria, Greece",Luxury Triple cave room,Cave,Mesaria,Greece,Jun,129.00,4.72,32.0,592,239,Very Good
304,"Cave in Mesaria, Greece",Luxury Triple cave room,Cave,Mesaria,Greece,Jun,129.00,4.72,32.0,591,239,Very Good
635,"Condo in Cebu City, Philippines",Cozy City Condo at Horizons 101 [ W/ WIFI ].,Condo,Cebu City,Philippines,Jun,26.00,4.44,220.0,666,138,Needs Improvement
654,"Condo in Cebu City, Philippines",Cozy City Condo at Horizons 101 [ W/ WIFI ].,Condo,Cebu City,Philippines,Jun,26.00,4.44,220.0,667,138,Needs Improvement
623,"Condo in Cebu City, Philippines",Cozy City Condo at Horizons 101 [ W/ WIFI ].,Condo,Cebu City,Philippines,Jun,26.00,4.44,220.0,665,138,Needs Improvement
626,"Condo in Chiang Mai, Thailand",Cozy room 48.5 sq.m @The Astra near Night market,Condo,Chiang Mai,Thailand,Jun,45.00,4.89,190.0,311,81,Very Good
637,"Condo in Chiang Mai, Thailand",Cozy room 48.5 sq.m @The Astra near Night market,Condo,Chiang Mai,Thailand,Jun,45.00,4.89,190.0,312,81,Very Good
656,"Condo in Chiang Mai, Thailand",Cozy room 48.5 sq.m @The Astra near Night market,Condo,Chiang Mai,Thailand,Jun,45.00,4.89,190.0,313,81,Very Good
580,"Condo in Na Chom Thian, Thailand",Veranda Residence pattaya 2bedroom partial sea...,Condo,Na Chom Thian,Thailand,Jun,83.00,4.89,186.0,315,19,Very Good
565,"Condo in Na Chom Thian, Thailand",Veranda Residence pattaya 2bedroom partial sea...,Condo,Na Chom Thian,Thailand,Jun,83.00,4.89,186.0,314,19,Very Good
374,"Cottage in Benalauría, Spain","""La Parra"", rural tourism. Your home in paradise.",Cottage,Benalauría,Spain,Sep,67.00,4.99,335.0,65,40,Excellent
363,"Cottage in Benalauría, Spain","""La Parra"", rural tourism. Your home in paradise.",Cottage,Benalauría,Spain,Sep,67.00,4.99,335.0,64,40,Excellent
175,"Cottage in Islamorada, Florida, US",1 BD PRIVATE HOUSEBOAT/ COTTAGE TARPON,Cottage,Islamorada,"Florida, US",Aug,229.00,4.85,74.0,419,161,Very Good
161,"Cottage in Islamorada, Florida, US",1 BD PRIVATE HOUSEBOAT/ COTTAGE TARPON,Cottage,Islamorada,"Florida, US",Aug,229.00,4.85,74.0,418,161,Very Good
163,"Cottage in Quintana Roo, Mexico",Glass Roof House #2 at Glass 20.87,Cottage,Quintana Roo,Mexico,Jun,221.00,4.93,68.0,222,168,Excellent
177,"Cottage in Quintana Roo, Mexico",Glass Roof House #2 at Glass 20.87,Cottage,Quintana Roo,Mexico,Jun,221.00,4.93,68.0,223,168,Excellent
359,"Dome in Wapnica, Poland",Delightfull Dome with Hot tub & sauna on the b...,Dome,Wapnica,Poland,Jun,319.00,4.98,52.0,91,113,Excellent
369,"Dome in Wapnica, Poland",Delightfull Dome with Hot tub & sauna on the b...,Dome,Wapnica,Poland,Jun,319.00,4.98,52.0,92,113,Excellent
448,"Earthen home in Mueang Chiang Mai District, Th...",Leafy Greens Chiangmai : Mushroom M2,Earthen home,Mueang Chiang Mai District,Thailand,Jun,22.00,4.87,210.0,361,170,Very Good
451,"Earthen home in Mueang Chiang Mai District, Th...",Leafy Greens Chiangmai : Mushroom M2,Earthen home,Mueang Chiang Mai District,Thailand,Jun,22.00,4.87,210.0,362,170,Very Good
170,"Farm stay in Saint Marys, Canada",Cozy Farm Stay Getaway,Farm stay,Saint Marys,Canada,Jun,99.00,4.86,183.0,385,1,Very Good
184,"Farm stay in Saint Marys, Canada",Cozy Farm Stay Getaway,Farm stay,Saint Marys,Canada,Jun,99.00,4.86,183.0,386,1,Very Good
506,"Guest suite in Bingin Beach, Indonesia",Suite 2 - Beachfront Luxury Suite on Bingin Beach,Guest suite,Bingin Beach,Indonesia,Oct,267.00,4.93,96.0,221,134,Excellent
501,"Guest suite in Bingin Beach, Indonesia",Suite 2 - Beachfront Luxury Suite on Bingin Beach,Guest suite,Bingin Beach,Indonesia,Oct,267.00,4.93,96.0,220,134,Excellent
361,"Guest suite in La Marsa, Tunisia",THE AQUARIUM … waterfront 🧜🏾‍♂️,Guest suite,La Marsa,Tunisia,Jun,61.00,4.72,103.0,589,48,Very Good
371,"Guest suite in La Marsa, Tunisia",THE AQUARIUM … waterfront 🧜🏾‍♂️,Guest suite,La Marsa,Tunisia,Jun,61.00,4.72,103.0,590,48,Very Good
207,"Guesthouse in Naalehu, Hawaii, US",The Ohana,Guesthouse,Naalehu,"Hawaii, US",Jun,99.00,4.86,182.0,387,1,Very Good
211,"Guesthouse in Naalehu, Hawaii, US",The Ohana,Guesthouse,Naalehu,"Hawaii, US",Jun,99.00,4.86,182.0,388,1,Very Good
367,"Guesthouse in Perranwell Station, UK",The Folly - Cornwall,Guesthouse,Perranwell Station,UK,Jun,111.00,5.00,11.0,45,256,Excellent
357,"Guesthouse in Perranwell Station, UK",The Folly - Cornwall,Guesthouse,Perranwell Station,UK,Jun,111.00,5.00,11.0,44,256,Excellent
365,"Home in Audierne, France",Villa Trouz Ar Mor,Home,Audierne,France,Jul,135.00,4.85,13.0,432,233,Very Good
379,"Home in Audierne, France",Villa Trouz Ar Mor,Home,Audierne,France,Jul,135.00,4.85,13.0,433,233,Very Good
403,"Home in Bad Sankt Leonhard im Lavanttal, Austria",1A chalet resting crickets + hiking with indoo...,Home,Bad Sankt Leonhard im Lavanttal,Austria,Jun,123.00,4.67,110.0,619,244,Good
389,"Home in Bad Sankt Leonhard im Lavanttal, Austria",1A chalet resting crickets + hiking with indoo...,Home,Bad Sankt Leonhard im Lavanttal,Austria,Jun,123.00,4.67,110.0,618,244,Good
317,"Home in Baião, Portugal",CasasdoCasinhotoD-Rustic House (pool; river view),Home,Baião,Portugal,Jun,131.00,4.81,43.0,503,237,Very Good
307,"Home in Baião, Portugal",CasasdoCasinhotoD-Rustic House (pool; river view),Home,Baião,Portugal,Jun,131.00,4.81,43.0,502,237,Very Good
168,"Home in Cape Coral, Florida, US",Amazing Modern Home with Pool and Hot Tub!,Home,Cape Coral,"Florida, US",Jul,167.00,4.84,136.0,445,206,Very Good
183,"Home in Cape Coral, Florida, US",Amazing Modern Home with Pool and Hot Tub!,Home,Cape Coral,"Florida, US",Jul,167.00,4.84,136.0,446,206,Very Good
399,"Home in Chalkida, Greece",Seaside & Garden Single family home,Home,Chalkida,Greece,Jun,104.00,4.94,33.0,208,261,Excellent
385,"Home in Chalkida, Greece",Seaside & Garden Single family home,Home,Chalkida,Greece,Jun,104.00,4.94,33.0,207,261,Excellent
87,"Home in Hilbert, Wisconsin, US",State Park A-Frame with Hiking Trails & Arcade,Home,Hilbert,"Wisconsin, US",Jun,239.00,4.97,29.0,123,152,Excellent
90,"Home in Hilbert, Wisconsin, US",State Park A-Frame with Hiking Trails & Arcade,Home,Hilbert,"Wisconsin, US",Jun,239.00,4.97,29.0,124,152,Excellent
566,"Home in Hua Hin, Thailand",Cool Home w Garden near Sea,Home,Hua Hin,Thailand,Jul,77.00,4.81,360.0,492,25,Very Good
581,"Home in Hua Hin, Thailand",Cool Home w Garden near Sea,Home,Hua Hin,Thailand,Jul,77.00,4.81,360.0,493,25,Very Good
536,"Home in Kecamatan Selat, Indonesia",The Nude House,Home,Kecamatan Selat,Indonesia,Jul,305.00,4.68,19.0,612,117,Good
540,"Home in Kecamatan Selat, Indonesia",The Nude House,Home,Kecamatan Selat,Indonesia,Jul,305.00,4.68,19.0,613,117,Good
534,"Home in Kecamatan Ubud, Indonesia",PROMO! Luxury Villa Escape in Ubud 2 BR,Home,Kecamatan Ubud,Indonesia,Sep,306.00,5.00,4.0,60,116,Excellent
539,"Home in Kecamatan Ubud, Indonesia",PROMO! Luxury Villa Escape in Ubud 2 BR,Home,Kecamatan Ubud,Indonesia,Sep,306.00,5.00,4.0,61,116,Excellent
362,"Home in Positano, Italy",Villa Laurito,Home,Positano,Italy,Oct,185.00,4.88,66.0,342,192,Very Good
372,"Home in Positano, Italy",Villa Laurito,Home,Positano,Italy,Oct,185.00,4.88,66.0,343,192,Very Good
569,"Home in Tabanan, Indonesia",Ocean View Pool Villa @ Balian Beach,Home,Tabanan,Indonesia,Jun,170.00,4.76,282.0,564,202,Very Good
585,"Home in Tabanan, Indonesia",Ocean View Pool Villa @ Balian Beach,Home,Tabanan,Indonesia,Jun,170.00,4.76,282.0,565,202,Very Good
592,"Home in ตำบล บ้านใต้, Thailand","❤️THE LOFT, Romantic Beachfront Home, HIN KONG.",Home,ตำบล บ้านใต้,Thailand,Aug,198.00,4.96,56.0,148,185,Excellent
591,"Home in ตำบล บ้านใต้, Thailand","❤️THE LOFT, Romantic Beachfront Home, HIN KONG.",Home,ตำบล บ้านใต้,Thailand,Aug,198.00,4.96,56.0,147,185,Excellent
505,"Hotel in Tambon Ratsada, Thailand",Hotel Room with Private Plunge Pool Siray Bay#2,Hotel,Tambon Ratsada,Thailand,Jun,71.00,5.00,13.0,39,33,Excellent
500,"Hotel in Tambon Ratsada, Thailand",Hotel Room with Private Plunge Pool Siray Bay#2,Hotel,Tambon Ratsada,Thailand,Jun,71.00,5.00,13.0,38,33,Excellent
182,"Hotel in Tepoztlán, Mexico",Posada Sarita,Hotel,Tepoztlán,Mexico,Jun,50.00,4.56,176.0,648,63,Good
165,"Hotel in Tepoztlán, Mexico",Posada Sarita,Hotel,Tepoztlán,Mexico,Jun,50.00,4.56,176.0,647,63,Good
102,"Hut in Uvero Alto - Bavaro - Punta Cana, Domin...",Hut #2 Romantic Luxury on the sand,Hut,Uvero Alto - Bavaro - Punta Cana,Dominican Republic,Aug,186.00,4.94,226.0,192,191,Excellent
104,"Hut in Uvero Alto - Bavaro - Punta Cana, Domin...",Hut #2 Romantic Luxury on the sand,Hut,Uvero Alto - Bavaro - Punta Cana,Dominican Republic,Aug,186.00,4.94,226.0,193,191,Excellent
410,"Lighthouse in Ploemeur, France",Q3 BNB Premium Residence - The Engineering Tower,Lighthouse,Ploemeur,France,Jun,147.00,4.80,10.0,522,222,Very Good
397,"Lighthouse in Ploemeur, France",Q3 BNB Premium Residence - The Engineering Tower,Lighthouse,Ploemeur,France,Jun,147.00,4.80,10.0,521,222,Very Good
387,"Loft in Baošići, Montenegro",Porto Bello Lux ( Sea View & Swimming Pool),Loft,Baošići,Montenegro,Jun,58.00,4.90,110.0,296,52,Excellent
401,"Loft in Baošići, Montenegro",Porto Bello Lux ( Sea View & Swimming Pool),Loft,Baošići,Montenegro,Jun,58.00,4.90,110.0,297,52,Excellent
617,"Loft in George Town, Malaysia",Coastline Seaview Duplex Level 19 Executive Floor,Loft,George Town,Malaysia,Jun,87.00,4.92,437.0,231,15,Excellent
628,"Loft in George Town, Malaysia",Coastline Seaview Duplex Level 19 Executive Floor,Loft,George Town,Malaysia,Jun,87.00,4.92,437.0,232,15,Excellent
567,"Loft in Pasig, Philippines",Cozy & Modern Loft w/ high speed wi-fi and Net...,Loft,Pasig,Philippines,Jul,35.00,4.92,196.0,239,102,Excellent
583,"Loft in Pasig, Philippines",Cozy & Modern Loft w/ high speed wi-fi and Net...,Loft,Pasig,Philippines,Jul,35.00,4.92,196.0,240,102,Excellent
318,"Nature lodge in Highland Council, UK",Elegant Little Wyvis Lodge - Sleeps 2,Nature lodge,Highland Council,UK,Jun,159.00,4.96,95.0,145,214,Excellent
308,"Nature lodge in Highland Council, UK",Elegant Little Wyvis Lodge - Sleeps 2,Nature lodge,Highland Council,UK,Jun,159.00,4.96,95.0,144,214,Excellent
560,"Place to stay in Nusa Penida, Indonesia",Tide 2 in Penida Tides Cottage,Place to stay,Nusa Penida,Indonesia,Jul,32.00,4.85,68.0,420,112,Very Good
575,"Place to stay in Nusa Penida, Indonesia",Tide 2 in Penida Tides Cottage,Place to stay,Nusa Penida,Indonesia,Jul,32.00,4.85,68.0,421,112,Very Good
86,"Place to stay in Punta Cana, Dominican Republic",Hut #3 Romantic Luxury on the sand,Place to stay,Punta Cana,Dominican Republic,Jul,132.00,4.86,29.0,394,236,Very Good
89,"Place to stay in Punta Cana, Dominican Republic",Hut #3 Romantic Luxury on the sand,Place to stay,Punta Cana,Dominican Republic,Jul,132.00,4.86,29.0,395,236,Very Good
400,"Place to stay in Scottish Borders, UK","16th Century Scottish Borders Tower, by Earlston",Place to stay,Scottish Borders,UK,Jul,252.00,4.96,464.0,129,143,Excellent
386,"Place to stay in Scottish Borders, UK","16th Century Scottish Borders Tower, by Earlston",Place to stay,Scottish Borders,UK,Jul,252.00,4.96,464.0,128,143,Excellent
312,"Room in Borgo Valsugana, Italy","La Tana del Lupo B&B, family and outdoor sports",Room,Borgo Valsugana,Italy,Sep,73.00,4.99,121.0,71,31,Excellent
322,"Room in Borgo Valsugana, Italy","La Tana del Lupo B&B, family and outdoor sports",Room,Borgo Valsugana,Italy,Sep,73.00,4.99,121.0,72,31,Excellent
577,"Room in Kabupaten Badung, Indonesia",Private room4 Legian/breakfast/close to Kuta b...,Room,Kabupaten Badung,Indonesia,Jun,81.00,4.91,34.0,278,21,Excellent
562,"Room in Kabupaten Badung, Indonesia",Private room4 Legian/breakfast/close to Kuta b...,Room,Kabupaten Badung,Indonesia,Jun,81.00,4.91,34.0,277,21,Excellent
160,"Room in New York, New York, US","Lovely Private Room-Manhattan, 70s-Upper East ...",Room,New York,"New York, US",Jul,103.00,4.93,30.0,226,262,Excellent
174,"Room in New York, New York, US","Lovely Private Room-Manhattan, 70s-Upper East ...",Room,New York,"New York, US",Jul,103.00,4.93,30.0,227,262,Excellent
661,"Room in Tebet, Indonesia",The LOJI @ Patra Kuningan # 3,Room,Tebet,Indonesia,Jun,24.00,4.83,69.0,469,151,Very Good
641,"Room in Tebet, Indonesia",The LOJI @ Patra Kuningan # 3,Room,Tebet,Indonesia,Jun,24.00,4.83,69.0,468,151,Very Good
314,"Room in Torreglia, Italy",Country House,Room,Torreglia,Italy,Jun,69.00,4.94,84.0,202,35,Excellent
303,"Room in Torreglia, Italy",Country House,Room,Torreglia,Italy,Jun,69.00,4.94,84.0,201,35,Excellent
138,Shipping container in Puerto Viejo de Talamanc...,Mimosa Y - Beautiful Unique Container Home w' ...,Shipping container,Puerto Viejo de Talamanca,Costa Rica,Jun,90.00,4.85,54.0,426,12,Very Good
137,Shipping container in Puerto Viejo de Talamanc...,Mimosa Y - Beautiful Unique Container Home w' ...,Shipping container,Puerto Viejo de Talamanca,Costa Rica,Jun,90.00,4.85,54.0,425,12,Very Good
364,"Tiny home in Muldenhammer, Germany",Hascherle Hitt,Tiny home,Muldenhammer,Germany,Jun,86.00,5.00,57.0,13,16,Excellent
377,"Tiny home in Muldenhammer, Germany",Hascherle Hitt,Tiny home,Muldenhammer,Germany,Jun,86.00,5.00,57.0,14,16,Excellent
588,"Treehouse in Bali, Indonesia",Lounge Poolside Under Lush Greenery at an Orga...,Treehouse,Bali,Indonesia,Jul,69.00,4.71,98.0,597,35,Very Good
573,"Treehouse in Bali, Indonesia",Lounge Poolside Under Lush Greenery at an Orga...,Treehouse,Bali,Indonesia,Jul,69.00,4.71,98.0,596,35,Very Good
533,"Treehouse in Kecamatan Ubud, Indonesia",Bamboo Turtle cabin river view 5km to Ubud center,Treehouse,Kecamatan Ubud,Indonesia,Jul,118.00,4.88,75.0,340,249,Very Good
538,"Treehouse in Kecamatan Ubud, Indonesia",Bamboo Turtle cabin river view 5km to Ubud center,Treehouse,Kecamatan Ubud,Indonesia,Jul,118.00,4.88,75.0,341,249,Very Good
390,"Vacation home in Punta Prima, Spain",Beachfront apartment with perfect seaview,Vacation home,Punta Prima,Spain,Jun,231.00,4.85,204.0,407,158,Very Good
404,"Vacation home in Punta Prima, Spain",Beachfront apartment with perfect seaview,Vacation home,Punta Prima,Spain,Jun,231.00,4.85,204.0,408,158,Very Good
502,"Villa in Bacnotan, La Union, Philippines","Private Modern Beachfront Villa: Pool, Sunset ...",Villa,Bacnotan,"La Union, Philippines",Jun,628.00,5.00,15.0,34,46,Excellent
497,"Villa in Bacnotan, La Union, Philippines","Private Modern Beachfront Villa: Pool, Sunset ...",Villa,Bacnotan,"La Union, Philippines",Jun,628.00,5.00,15.0,33,46,Excellent
570,"Villa in General Luna, Philippines",Oceanfront Pool Villa,Villa,General Luna,Philippines,Jul,163.00,4.96,23.0,155,210,Excellent
587,"Villa in General Luna, Philippines",Oceanfront Pool Villa,Villa,General Luna,Philippines,Jul,163.00,4.96,23.0,156,210,Excellent

In [83]:
print("Number of duplicate rows:", len(duplicates))

Number of duplicate rows: 149

In [84]:
print(
    "Number of duplicated properties:",
    duplicates["Property Name"].nunique()
)

Number of duplicated properties: 71

In [85]:
duplicates.groupby("Property Name").size().sort_values(ascending=False)

Property Name
Villa in Seririt, Indonesia                                    3
Cabin in Tambon Ko Pha-ngan, Thailand                          3
Condo in Chiang Mai, Thailand                                  3
Condo in Cebu City, Philippines                                3
Apartment in Tambon Kamala, Thailand                           3
Apartment in Tambon Patong, Thailand                           3
Cabin in Lazi, Philippines                                     3
Room in Borgo Valsugana, Italy                                 2
Place to stay in Scottish Borders, UK                          2
Place to stay in Punta Cana, Dominican Republic                2
Place to stay in Nusa Penida, Indonesia                        2
Nature lodge in Highland Council, UK                           2
Loft in George Town, Malaysia                                  2
Loft in Pasig, Philippines                                     2
Room in New York, New York, US                                 2
Loft in Baošići, Montenegro                                    2
Lighthouse in Ploemeur, France                                 2
Hut in Uvero Alto - Bavaro - Punta Cana, Dominican Republic    2
Hotel in Tepoztlán, Mexico                                     2
Hotel in Tambon Ratsada, Thailand                              2
Home in ตำบล บ้านใต้, Thailand                                 2
Room in Kabupaten Badung, Indonesia                            2
Shipping container in Puerto Viejo de Talamanca, Costa Rica    2
Room in Tebet, Indonesia                                       2
Room in Torreglia, Italy                                       2
Home in Positano, Italy                                        2
Tiny home in Muldenhammer, Germany                             2
Treehouse in Bali, Indonesia                                   2
Treehouse in Kecamatan Ubud, Indonesia                         2
Vacation home in Punta Prima, Spain                            2
Villa in Bacnotan, La Union, Philippines                       2
Villa in General Luna, Philippines                             2
Villa in Karangasem, Indonesia                                 2
Villa in Kathu, Thailand                                       2
Villa in Kecamatan Kuta Utara, Indonesia                       2
Villa in Lian, Philippines                                     2
Villa in Pemuteran, Indonesia                                  2
Home in Tabanan, Indonesia                                     2
Apartment in Areti, Greece                                     2
Home in Kecamatan Ubud, Indonesia                              2
Home in Kecamatan Selat, Indonesia                             2
Apartment in Kuala Lumpur, Malaysia                            2
Apartment in Marina del Rey, California, US                    2
Apartment in PHUKET, Thailand                                  2
Apartment in Phuket, Thailand                                  2
Apartment in Quận 4, Vietnam                                   2
Bungalow in Izmir, Turkey                                      2
Cabin in Millbrook, UK                                         2
Cabin in Serrazone, Italy                                      2
Cabin in Totana, Spain                                         2
Castle in Winningen, Germany                                   2
Cave in Mesaria, Greece                                        2
Condo in Na Chom Thian, Thailand                               2
Cottage in Benalauría, Spain                                   2
Cottage in Islamorada, Florida, US                             2
Cottage in Quintana Roo, Mexico                                2
Dome in Wapnica, Poland                                        2
Earthen home in Mueang Chiang Mai District, Thailand           2
Farm stay in Saint Marys, Canada                               2
Guest suite in Bingin Beach, Indonesia                         2
Guest suite in La Marsa, Tunisia                               2
Guesthouse in Naalehu, Hawaii, US                              2
Guesthouse in Perranwell Station, UK                           2
Home in Audierne, France                                       2
Home in Bad Sankt Leonhard im Lavanttal, Austria               2
Home in Baião, Portugal                                        2
Home in Cape Coral, Florida, US                                2
Home in Chalkida, Greece                                       2
Apartment in Gordonville, Pennsylvania, US                     2
Home in Hua Hin, Thailand                                      2
Home in Hilbert, Wisconsin, US                                 2
dtype: int64

In [86]:
airbnb = airbnb.drop_duplicates(
    subset=[
        "Property Name",
        "Amenities",
        "Property Type",
        "City",
        "Country",
        "Month",
        "Price(in dollar)",
        "Rating",
        "Number of Reviews",
        "Rating Category"
    ]
).reset_index(drop=True)

print("Remaining rows:", len(airbnb))

Remaining rows: 604

In [88]:
airbnb["Price(in dollar)"].dtype

dtype('O')

In [89]:
airbnb["Price(in dollar)"].head(10)

0     99.00
1     99.00
2    986.00
3     98.00
4     98.00
5     98.00
6     98.00
7     98.00
8     98.00
9     97.00
Name: Price(in dollar), dtype: object

In [90]:
airbnb["Price(in dollar)"] = (
    airbnb["Price(in dollar)"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .str.replace("$", "", regex=False)
    .str.strip()
)

airbnb["Price(in dollar)"] = pd.to_numeric(
    airbnb["Price(in dollar)"],
    errors="coerce"
)

In [91]:
airbnb["Price(in dollar)"].dtype

dtype('float64')

In [92]:
airbnb[airbnb["Price(in dollar)"].isna()]

Empty DataFrame
Columns: [Property Name, Amenities, Property Type, City, Country, Month, Price(in dollar), Rating, Number of Reviews, Rating Rank, Price Rank, Rating Category]
Index: []

In [93]:
airbnb["Price(in dollar)"].sample(10)

452    162.0
206    450.0
369    225.0
0       99.0
1       99.0
438    169.0
134     63.0
426    176.0
237     39.0
406    196.0
Name: Price(in dollar), dtype: float64

In [94]:
airbnb["Price(in dollar)"].sort_values(ascending=False)

603    1463.0
2       986.0
34      913.0
40      898.0
86      764.0
97      743.0
120     688.0
122     673.0
123     670.0
126     658.0
129     649.0
137     628.0
146     607.0
172     526.0
174     513.0
180     506.0
183     497.0
184     490.0
190     485.0
191     484.0
192     484.0
193     483.0
194     480.0
195     474.0
196     473.0
198     469.0
199     468.0
200     468.0
201     463.0
202     460.0
205     458.0
204     458.0
206     450.0
219     424.0
220     420.0
229     402.0
235     398.0
236     392.0
239     381.0
238     381.0
244     370.0
246     363.0
247     363.0
248     360.0
249     359.0
250     357.0
251     354.0
254     346.0
260     336.0
261     335.0
262     335.0
263     332.0
269     328.0
270     325.0
271     322.0
272     322.0
276     319.0
277     315.0
282     306.0
283     306.0
284     305.0
285     305.0
286     302.0
287     302.0
288     302.0
289     302.0
290     302.0
291     301.0
298     298.0
299     294.0
301     291.0
300     291.0
307     287.0
308     287.0
311     286.0
309     286.0
310     286.0
312     286.0
313     285.0
315     283.0
314     283.0
316     280.0
319     276.0
320     276.0
321     271.0
322     268.0
323     267.0
324     264.0
325     262.0
326     261.0
327     261.0
332     258.0
333     255.0
334     254.0
335     253.0
337     252.0
338     252.0
336     252.0
340     252.0
339     252.0
341     251.0
343     248.0
344     247.0
345     246.0
346     243.0
348     240.0
347     240.0
353     239.0
354     238.0
355     237.0
356     235.0
357     233.0
358     232.0
359     232.0
360     231.0
361     230.0
366     229.0
365     229.0
364     229.0
363     229.0
367     228.0
368     227.0
369     225.0
370     225.0
371     224.0
372     223.0
373     222.0
374     222.0
376     221.0
377     221.0
375     221.0
381     220.0
379     220.0
380     220.0
378     220.0
383     219.0
384     219.0
385     218.0
386     217.0
387     217.0
388     216.0
389     212.0
390     210.0
391     209.0
392     209.0
393     207.0
394     207.0
395     206.0
399     205.0
397     205.0
398     205.0
396     205.0
400     202.0
401     201.0
402     201.0
403     200.0
404     199.0
405     198.0
406     196.0
407     194.0
408     194.0
409     192.0
411     189.0
412     189.0
413     186.0
414     186.0
416     185.0
415     185.0
417     184.0
418     184.0
419     184.0
421     183.0
420     183.0
422     181.0
425     178.0
424     178.0
427     176.0
426     176.0
428     174.0
431     173.0
430     173.0
429     173.0
434     171.0
433     171.0
432     171.0
436     170.0
435     170.0
438     169.0
439     169.0
440     169.0
441     168.0
442     167.0
443     167.0
445     166.0
444     166.0
446     165.0
449     164.0
448     164.0
447     164.0
450     163.0
451     163.0
452     162.0
454     162.0
455     162.0
453     162.0
456     160.0
460     159.0
458     159.0
459     159.0
461     158.0
462     157.0
463     157.0
464     155.0
465     155.0
466     155.0
467     154.0
468     154.0
469     154.0
470     154.0
471     153.0
472     149.0
474     148.0
475     148.0
473     148.0
476     148.0
479     147.0
477     147.0
478     147.0
480     146.0
481     146.0
483     144.0
484     144.0
485     144.0
482     144.0
488     143.0
487     143.0
486     143.0
492     142.0
491     142.0
490     142.0
489     142.0
493     141.0
494     141.0
496     141.0
495     141.0
498     140.0
497     140.0
499     139.0
501     138.0
500     138.0
503     138.0
502     138.0
505     137.0
504     137.0
510     136.0
509     136.0
506     136.0
508     136.0
507     136.0
516     135.0
514     135.0
511     135.0
512     135.0
513     135.0
515     135.0
517     134.0
518     133.0
519     133.0
520     133.0
522     132.0
523     132.0
521     132.0
525     131.0
526     131.0
524     131.0
529     130.0
528     130.0
527     130.0
530     129.0
531     129.0
534     128.0
533     128.0
535     128.0
532     128.0
539     127.0
536     127.0
537     127.0
538     127.0
540     126.0
541     126.0
542     126.0
545     125.0
544     125.0
543     125.0
546     123.0
547     123.0
548     122.0
550     121.0
551     121.0
549     121.0
552     120.0
553     119.0
554     119.0
557     118.0
556     118.0
555     118.0
559     117.0
560     117.0
561     117.0
558     117.0
562     116.0
563     116.0
566     115.0
564     115.0
565     115.0
567     114.0
568     114.0
569     113.0
570     112.0
574     112.0
573     112.0
571     112.0
572     112.0
580     111.0
575     111.0
576     111.0
579     111.0
577     111.0
581     111.0
578     111.0
582     111.0
583     111.0
584     111.0
585     109.0
586     108.0
587     108.0
588     108.0
591     107.0
592     107.0
590     107.0
589     107.0
593     105.0
594     105.0
595     104.0
596     103.0
597     102.0
598     102.0
599     101.0
600     100.0
601     100.0
602     100.0
0        99.0
1        99.0
3        98.0
4        98.0
5        98.0
6        98.0
7        98.0
8        98.0
12       97.0
9        97.0
10       97.0
11       97.0
13       97.0
14       96.0
15       96.0
16       96.0
18       95.0
19       95.0
17       95.0
20       94.0
21       94.0
23       93.0
22       93.0
24       93.0
25       93.0
26       93.0
31       92.0
32       92.0
33       92.0
30       92.0
29       92.0
27       92.0
28       92.0
35       91.0
36       91.0
39       90.0
37       90.0
38       90.0
44       89.0
46       89.0
41       89.0
43       89.0
42       89.0
45       89.0
47       87.0
54       86.0
51       86.0
53       86.0
52       86.0
50       86.0
49       86.0
48       86.0
55       85.0
56       85.0
58       85.0
57       85.0
59       84.0
60       83.0
61       83.0
62       82.0
63       82.0
64       82.0
65       82.0
70       81.0
69       81.0
67       81.0
66       81.0
68       81.0
71       80.0
72       80.0
73       80.0
74       80.0
75       80.0
77       79.0
78       79.0
76       79.0
79       78.0
80       78.0
81       78.0
82       78.0
83       78.0
84       77.0
85       77.0
90       76.0
89       76.0
88       76.0
87       76.0
91       75.0
92       75.0
93       75.0
94       75.0
95       75.0
96       75.0
98       74.0
99       74.0
103      73.0
102      73.0
101      73.0
100      73.0
104      72.0
105      72.0
106      72.0
107      72.0
108      71.0
109      71.0
110      71.0
111      71.0
112      71.0
113      70.0
119      69.0
118      69.0
117      69.0
116      69.0
115      69.0
114      69.0
121      68.0
124      67.0
125      67.0
127      65.0
128      65.0
130      64.0
131      64.0
132      64.0
133      64.0
134      63.0
135      63.0
136      63.0
138      62.0
139      62.0
140      61.0
141      61.0
142      61.0
143      61.0
144      61.0
145      61.0
147      60.0
148      60.0
149      59.0
151      58.0
152      58.0
150      58.0
154      57.0
155      57.0
156      57.0
157      57.0
158      57.0
153      57.0
159      56.0
161      55.0
162      55.0
163      55.0
164      55.0
165      55.0
166      55.0
160      55.0
167      54.0
170      53.0
171      53.0
169      53.0
168      53.0
173      52.0
175      51.0
176      51.0
177      51.0
178      51.0
179      51.0
181      50.0
182      50.0
188      49.0
189      49.0
186      49.0
187      49.0
185      49.0
197      47.0
203      46.0
207      45.0
208      45.0
213      44.0
212      44.0
211      44.0
209      44.0
210      44.0
218      43.0
217      43.0
216      43.0
215      43.0
214      43.0
222      42.0
224      42.0
225      42.0
221      42.0
223      42.0
226      41.0
227      41.0
228      41.0
233      40.0
234      40.0
232      40.0
230      40.0
231      40.0
237      39.0
240      38.0
241      38.0
242      38.0
243      38.0
245      37.0
252      35.0
253      35.0
259      34.0
256      34.0
255      34.0
258      34.0
257      34.0
265      33.0
266      33.0
267      33.0
268      33.0
264      33.0
275      32.0
274      32.0
273      32.0
278      31.0
280      31.0
281      31.0
279      31.0
292      30.0
293      30.0
294      30.0
295      30.0
296      30.0
297      30.0
302      29.0
303      29.0
304      29.0
305      29.0
306      29.0
317      28.0
318      28.0
328      26.0
331      26.0
330      26.0
329      26.0
342      25.0
350      24.0
349      24.0
351      24.0
352      24.0
362      23.0
382      22.0
410      19.0
423      18.0
437      17.0
457      16.0
Name: Price(in dollar), dtype: float64

In [98]:
airbnb.sort_values(
    by="Price(in dollar)",
    ascending=False
)[
    [
        "Property Name",
        "Property Type",
        "Amenities",
        "City",
        "Country",
        "Price(in dollar)",
        "Rating",
        "Number of Reviews"
    ]
].head(20)

,Property Name,Property Type,Amenities,City,Country,Price(in dollar),Rating,Number of Reviews
603,"Home in Moss Beach, California, US",Home,Walk to the Beach from this Ocean Front Home,Moss Beach,"California, US",1463.0,4.94,149.0
2,"Villa in Koh Yao Noi, Thailand",Villa,"Eagles Nest, Luxury Villa, Koh Yao Noi",Koh Yao Noi,Thailand,986.0,4.95,43.0
34,"Treehouse in Klungkung, Indonesia",Treehouse,3 Bdr - The Dream Cliffside Bamboo Villa By Avana,Klungkung,Indonesia,913.0,4.97,30.0
40,"Condo in Malibu, California, US",Condo,"Malibu, Carbon Beach - Suite Seven",Malibu,"California, US",898.0,4.86,311.0
86,"Cottage in Wheatley, Canada",Cottage,"Cozy Modern Beach House w/ Pool, Hot Tub & More!",Wheatley,Canada,764.0,4.74,19.0
97,"Cabin in Fennville, Michigan, US",Cabin,Fire & Water | Rejuvenating Stay on the Riverbend,Fennville,"Michigan, US",743.0,4.83,175.0
120,"Home in Port Angeles, Washington, US",Home,Lake Sutherland Waterfront Cabin w/ Expansive ...,Port Angeles,"Washington, US",688.0,4.82,83.0
122,"Villa in Uluwatu, Indonesia",Villa,"Spectacular Ocean View Villa in Uluwatu, Bali",Uluwatu,Indonesia,673.0,4.94,143.0
123,"Cottage in Bodega Bay, California, US",Cottage,"Seamist Beach Cottage, Private Beach & Ocean v...",Bodega Bay,"California, US",670.0,4.70,256.0
126,"Treehouse in Fredericksburg, Texas, US",Treehouse,Luxury Tree House X Magical Romantic Forest! P...,Fredericksburg,"Texas, US",658.0,4.91,142.0
129,"Condo in Malibu, California, US",Condo,"Malibu, Carbon Beach - Suite Three",Malibu,"California, US",649.0,4.80,425.0
137,"Villa in Bacnotan, La Union, Philippines",Villa,"Private Modern Beachfront Villa: Pool, Sunset ...",Bacnotan,"La Union, Philippines",628.0,5.00,15.0
146,"Home in Saco, Maine, US",Home,The Beach House. Oceanfront & Sunrise Views!,Saco,"Maine, US",607.0,4.64,90.0
172,"Apartment in Areti, Greece",Apartment,Echoes Exclusive Suite,Areti,Greece,526.0,4.98,40.0
174,"Villa in Abiansemal, Indonesia",Villa,"Aura House 2bds Eco Bamboo House, Pool, River ...",Abiansemal,Indonesia,513.0,4.87,209.0
180,"Villa in Tampaksiring, Indonesia",Villa,Luxury 5 BDR Resort w/ Gym & Ricefield View,Tampaksiring,Indonesia,506.0,4.78,101.0
183,"Cabin in Ucluelet, Canada",Cabin,Peace Cabin - private waterfront forest retreat,Ucluelet,Canada,497.0,4.99,69.0
184,"Room in UbudUbud, Gianyar, Indonesia",Room,Luxe Suite: Villacellabella Ubud Bali Instaworthy,UbudUbud,"Gianyar, Indonesia",490.0,4.92,167.0
190,"Cabin in Hancock, New York, US",Cabin,The Catskill A-Frame - Mid-Century Modern Cabin,Hancock,"New York, US",485.0,4.77,146.0
191,"Cabin in Klungkung, Indonesia",Cabin,Dreamy Cliffside Bamboo Villa with Pool and View,Klungkung,Indonesia,484.0,4.98,58.0